/*        Generated by TAPENADE     (INRIA, Ecuador team)
    Tapenade 3.16 (develop) - 25 Oct 2024 09:00
*/
#include <math.h>
#include <stdio.h>

/*
  Differentiation of cdf_n in forward (tangent) mode:
   variations   of useful results: cdf_n
   with respect to varying inputs: x
*/
double cdf_n_d(double x, double xd, double *cdf_n) {
    *cdf_n = 0.5*erfc(x*-0.70710678118654746);
    return 0.5*1.1283791671*exp(-(-(0.70710678118654746*x)*-(
    0.70710678118654746*x)))*0.70710678118654746*xd;
}

/*
  Differentiation of call_price in forward (tangent) mode:
   variations   of useful results: call_price
   with respect to varying inputs: v K S T
   RW status of diff variables: v:in call_price:out K:in S:in
                T:in
*/
double call_price_d(double S, double Sd, double K, double Kd, double v, double
        vd, double T, double Td, double *call_price) {
    double totalvol;
    double totalvold;
    double result1;
    double result1d;
    double result2;
    double result2d;
    double temp;
    double temp0;
    temp = sqrt(T);
    result1d = (T == 0.0 ? 0.0 : Td/(2.0*temp));
    result1 = temp;
    totalvold = result1*vd + v*result1d;
    totalvol = v*result1;
    temp = S/K;
    temp0 = log(temp)/totalvol;
    double d1 = temp0 + 0.5*totalvol;
    double d1d = ((Sd-temp*Kd)/(temp*K)-temp0*totalvold)/totalvol + 0.5*
    totalvold;
    double d2 = d1 - totalvol;
    double d2d = d1d - totalvold;
    result1d = cdf_n_d(d1, d1d, &result1);
    result2d = cdf_n_d(d2, d2d, &result2);
    *call_price = S*result1 - K*result2;
    return result1*Sd + S*result1d - result2*Kd - K*result2d;
}
