/*        Generated by TAPENADE     (INRIA, Ecuador team)
    Tapenade 3.16 (develop) - 25 Oct 2024 09:00
*/
/*        Generated by TAPENADE     (INRIA, Ecuador team)
    Tapenade 3.16 (develop) - 25 Oct 2024 09:00

        Generated by TAPENADE     (INRIA, Ecuador team)
    Tapenade 3.16 (develop) - 25 Oct 2024 09:00
*/
#include <math.h>
#include <stdio.h>

/*
  Differentiation of cdf_n_d_d in forward (tangent) mode:
   variations   of useful results: *cdf_nd *cdf_n_d cdf_n_d_d
                *cdf_n
   with respect to varying inputs: xdd xd x *cdf_nd *cdf_n_d *cdf_n
                xd0
   Plus diff mem management of: cdf_nd:in cdf_n_d:in cdf_n:in


  Differentiation of cdf_n_d in forward (tangent) mode:
   variations   of useful results: cdf_n_d *cdf_n
   with respect to varying inputs: xd x *cdf_n
   Plus diff mem management of: cdf_n:in


  Differentiation of cdf_n in forward (tangent) mode:
   variations   of useful results: cdf_n
   with respect to varying inputs: x
*/
double cdf_n_d_d_d(double x, double xd1, double xd0, double xd0d, double xd, 
        double xdd0, double xdd, double xddd, double *cdf_n, double *cdf_nd0, 
        double *cdf_nd, double *cdf_ndd, double *cdf_n_d, double *cdf_n_dd, 
        double *cdf_n_d_d) {
    double arg1;
    double arg1d0;
    double arg1d;
    double arg1dd;
    double temp;
    double tempd;
    double arg10;
    double arg10d;
    double temp0;
    arg10d = -(0.70710678118654746*0.70710678118654746*2*x*xd1);
    arg10 = -(-(0.70710678118654746*x)*-(0.70710678118654746*x));
    temp0 = exp(arg10);
    *cdf_ndd = 1.1283791671*0.70710678118654746*0.5*(xd0*exp(arg10)*arg10d+
        temp0*xd0d);
    *cdf_nd = 1.1283791671*0.70710678118654746*0.5*(temp0*xd0);
    *cdf_nd0 = 0.5*1.1283791671*exp(-(-(0.70710678118654746*x)*-(
        0.70710678118654746*x)))*0.70710678118654746*xd1;
    *cdf_n = 0.5*erfc(x*-0.70710678118654746);
    arg1dd = -(0.70710678118654746*0.70710678118654746*2*(xd0*xd1+x*xd0d));
    arg1d = -(0.70710678118654746*0.70710678118654746*2*x*xd0);
    arg1d0 = -(0.70710678118654746*0.70710678118654746*2*x*xd1);
    arg1 = -(-(0.70710678118654746*x)*-(0.70710678118654746*x));
    tempd = exp(arg1)*arg1d0;
    temp = exp(arg1);
    *cdf_n_dd = 0.70710678118654746*0.5*1.1283791671*(xd*tempd+temp*xdd0);
    *cdf_n_d = 1.1283791671*0.70710678118654746*0.5*(temp*xd);
    temp0 = exp(arg1);
    *cdf_n_d_d = 0.70710678118654746*0.5*1.1283791671*(temp0*(xd*arg1d)+temp*
        xdd);
    return 0.70710678118654746*0.5*1.1283791671*(xd*arg1d*exp(arg1)*arg1d0+
    temp0*(arg1d*xdd0+xd*arg1dd)+xdd*tempd+temp*xddd);
}

/*
  Differentiation of call_price_d_d in forward (tangent) mode:
   variations   of useful results: *call_price_d *call_price *call_priced
                call_price_d_d
   with respect to varying inputs: Td Sd0 v Kd0 Tdd Kd *call_price_d
                vd0 *call_price vd Sdd *call_priced Td0 Sd Kdd
                K S T vdd
   RW status of diff variables: Td:in Sd0:in v:in Kd0:in Tdd:in
                Kd:in call_price_d:(loc) *call_price_d:in-out
                vd0:in call_price:(loc) *call_price:in-out vd:in
                Sdd:in call_priced:(loc) *call_priced:in-out Td0:in
                Sd:in Kdd:in K:in call_price_d_d:out S:in T:in
                vdd:in
   Plus diff mem management of: call_price_d:in call_price:in
                call_priced:in


  Differentiation of call_price_d in forward (tangent) mode:
   variations   of useful results: call_price_d *call_price
   with respect to varying inputs: Td v Kd *call_price vd Sd K
                S T
   RW status of diff variables: Td:in v:in Kd:in call_price_d:out
                call_price:(loc) *call_price:in-out vd:in Sd:in
                K:in S:in T:in
   Plus diff mem management of: call_price:in


  Differentiation of call_price in forward (tangent) mode:
   variations   of useful results: call_price
   with respect to varying inputs: v K S T
   RW status of diff variables: v:in call_price:out K:in S:in
                T:in
*/
double call_price_d_d_d(double S, double Sd1, double Sd0, double Sd0d, double 
        Sd, double Sdd0, double Sdd, double Sddd, double K, double Kd1, double
        Kd0, double Kd0d, double Kd, double Kdd0, double Kdd, double Kddd, 
        double v, double vd1, double vd0, double vd0d, double vd, double vdd0,
        double vdd, double vddd, double T, double Td1, double Td0, double Td0d
        , double Td, double Tdd0, double Tdd, double Tddd, double *call_price,
        double *call_priced0, double *call_priced, double *call_pricedd, 
        double *call_price_d, double *call_price_dd, double *call_price_d_d) {
    double totalvol;
    double totalvold1;
    double totalvold0;
    double totalvold0d;
    double totalvold;
    double totalvoldd0;
    double totalvoldd;
    double totalvolddd;
    double result1;
    double result1d1;
    double result1d0;
    double result1d0d;
    double result1d;
    double result1dd0;
    double result1dd;
    double result1ddd;
    double result2;
    double result2d1;
    double result2d0;
    double result2d0d;
    double result2d;
    double result2dd0;
    double result2dd;
    double result2ddd;
    double temp;
    double tempd0;
    double tempd;
    double tempdd;
    double temp0;
    double temp0d0;
    double temp0d;
    double temp0dd;
    double temp1;
    double temp1d;
    double temp2;
    double temp2d;
    double temp3;
    double temp4;
    double temp5;
    temp3 = sqrt(T);
    temp1d = (T == 0.0 ? 0.0 : Td1/(2.0*temp3));
    temp1 = temp3;
    temp3 = Td0/(2.0*temp1);
    tempdd = (T == 0.0 ? 0.0 : (Td0d-temp3*2.0*temp1d)/(2.0*temp1));
    tempd = (T == 0.0 ? 0.0 : temp3);
    tempd0 = temp1d;
    temp = temp1;
    temp3 = Td/(2.0*temp);
    temp1d = (Tdd0-temp3*2.0*tempd0)/(2.0*temp);
    temp1 = temp3;
    temp3 = (Tdd-2.0*temp1*tempd)/(2.0*temp);
    result1ddd = (T == 0.0 ? 0.0 : (Tddd-2.0*(tempd*temp1d+temp1*tempdd)-temp3
        *2.0*tempd0)/(2.0*temp));
    result1dd = (T == 0.0 ? 0.0 : temp3);
    result1dd0 = (T == 0.0 ? 0.0 : temp1d);
    result1d = (T == 0.0 ? 0.0 : temp1);
    result1d0d = tempdd;
    result1d0 = tempd;
    result1d1 = tempd0;
    result1 = temp;
    totalvolddd = result1d0*vdd0 + vd*result1d0d + vdd*result1d1 + result1*
        vddd + vd0*result1dd0 + result1d*vd0d + result1dd*vd1 + v*result1ddd;
    totalvoldd = vd*result1d0 + result1*vdd + result1d*vd0 + v*result1dd;
    totalvoldd0 = vd*result1d1 + result1*vdd0 + result1d*vd1 + v*result1dd0;
    totalvold = result1*vd + v*result1d;
    totalvold0d = vd0*result1d1 + result1*vd0d + result1d0*vd1 + v*result1d0d;
    totalvold0 = result1*vd0 + v*result1d0;
    totalvold1 = result1*vd1 + v*result1d1;
    totalvol = v*result1;
    temp3 = S*Kd0/K;
    temp4 = (Sd0-temp3)/K;
    tempdd = (Sd0d-(Kd0*Sd1+S*Kd0d-temp3*Kd1)/K-temp4*Kd1)/K;
    tempd = temp4;
    tempd0 = (Sd1-S*Kd1/K)/K;
    temp = S/K;
    temp4 = log(temp)/totalvol;
    temp1d = (tempd0/temp-temp4*totalvold1)/totalvol;
    temp1 = temp4;
    temp4 = (tempd/temp-temp1*totalvold0)/totalvol;
    temp0dd = ((tempdd-tempd*tempd0/temp)/temp-totalvold0*temp1d-temp1*
        totalvold0d-temp4*totalvold1)/totalvol;
    temp0d = temp4;
    temp0d0 = temp1d;
    temp0 = temp1;
    double d1 = temp0 + 0.5*totalvol;
    double d1d1 = temp0d0 + 0.5*totalvold1;
    double d1d0 = temp0d + 0.5*totalvold0;
    double d1d0d = temp0dd + 0.5*totalvold0d;
    temp4 = (Sd-temp*Kd)/(temp*K);
    temp1d = (Sdd0-Kd*tempd0-temp*Kdd0-temp4*(K*tempd0+temp*Kd1))/(temp*K);
    temp1 = temp4;
    temp4 = (temp1-temp0*totalvold)/totalvol;
    temp2d = (temp1d-totalvold*temp0d0-temp0*totalvoldd0-temp4*totalvold1)/
        totalvol;
    temp2 = temp4;
    double d1d = temp2 + 0.5*totalvold;
    double d1dd0 = temp2d + 0.5*totalvoldd0;
    temp4 = K*tempd + temp*Kd0;
    temp3 = (Sdd-Kd*tempd-temp*Kdd-temp1*temp4)/(temp*K);
    temp5 = (temp3-totalvold*temp0d-temp0*totalvoldd-temp2*totalvold0)/
        totalvol;
    double d1dd = temp5 + 0.5*totalvoldd;
    double d1ddd = ((Sddd-tempd*Kdd0-Kd*tempdd-Kdd*tempd0-temp*Kddd-temp4*
    temp1d-temp1*(tempd*Kd1+K*tempdd+Kd0*tempd0+temp*Kd0d)-temp3*(K*tempd0+
    temp*Kd1))/(temp*K)-temp0d*totalvoldd0-totalvold*temp0dd-totalvoldd*
    temp0d0-temp0*totalvolddd-totalvold0*temp2d-temp2*totalvold0d-temp5*
    totalvold1)/totalvol + 0.5*totalvolddd;
    double d2 = d1 - totalvol;
    double d2d1 = d1d1 - totalvold1;
    double d2d0 = d1d0 - totalvold0;
    double d2d0d = d1d0d - totalvold0d;
    double d2d = d1d - totalvold;
    double d2dd0 = d1dd0 - totalvoldd0;
    double d2dd = d1dd - totalvoldd;
    double d2ddd = d1ddd - totalvolddd;
    result1ddd = cdf_n_d_d_d(d1, d1d1, d1d0, d1d0d, d1d, d1dd0, d1dd, d1ddd, &
                             result1, &result1d1, &result1d0, &result1d0d, &
                             result1d, &result1dd0, &result1dd);
    result2d0d = 0.0;
    result2d0 = 0.0;
    result2dd0 = 0.0;
    result2d0d = 0.0;
    result2d1 = 0.0;
    result2ddd = cdf_n_d_d_d(d2, d2d1, d2d0, d2d0d, d2d, d2dd0, d2dd, d2ddd, &
                             result2, &result2d1, &result2d0, &result2d0d, &
                             result2d, &result2dd0, &result2dd);
    *call_pricedd = Sd0*result1d1 + result1*Sd0d + result1d0*Sd1 + S*
        result1d0d - Kd0*result2d1 - result2*Kd0d - result2d0*Kd1 - K*
        result2d0d;
    *call_priced = result1*Sd0 + S*result1d0 - result2*Kd0 - K*result2d0;
    *call_priced0 = result1*Sd1 + S*result1d1 - result2*Kd1 - K*result2d1;
    *call_price = S*result1 - K*result2;
    *call_price_dd = Sd*result1d1 + result1*Sdd0 + result1d*Sd1 + S*result1dd0
        - Kd*result2d1 - result2*Kdd0 - result2d*Kd1 - K*result2dd0;
    *call_price_d = result1*Sd + S*result1d - result2*Kd - K*result2d;
    *call_price_d_d = Sd*result1d0 + result1*Sdd + result1d*Sd0 + S*result1dd 
        - Kd*result2d0 - result2*Kdd - result2d*Kd0 - K*result2dd;
    return result1d0*Sdd0 + Sd*result1d0d + Sdd*result1d1 + result1*Sddd + Sd0
    *result1dd0 + result1d*Sd0d + result1dd*Sd1 + S*result1ddd - result2d0*
    Kdd0 - Kd*result2d0d - Kdd*result2d1 - result2*Kddd - Kd0*result2dd0 - 
    result2d*Kd0d - result2dd*Kd1 - K*result2ddd;
}
