/*        Generated by TAPENADE     (INRIA, Ecuador team)
    Tapenade 3.16 (develop) - 25 Oct 2024 09:00
*/
#include <adStack.h>
/*        Generated by TAPENADE     (INRIA, Ecuador team)
    Tapenade 3.16 (develop) - 25 Oct 2024 09:00

        Generated by TAPENADE     (INRIA, Ecuador team)
    Tapenade 3.16 (develop) - 25 Oct 2024 09:00

        Generated by TAPENADE     (INRIA, Ecuador team)
    Tapenade 3.16 (develop) - 25 Oct 2024 09:00
*/
#include <math.h>
#include <stdio.h>

/*
  Differentiation of cdf_n_d_d_d in reverse (adjoint) mode:
   gradient     of useful results: *cdf_ndd *cdf_n_dd *cdf_nd
                *cdf_n_d *cdf_nd0 *cdf_n_d_d *cdf_n cdf_n_d_d_d
   with respect to varying inputs: *cdf_ndd xd0d *cdf_n_dd xddd
                xdd xd x *cdf_nd *cdf_n_d *cdf_nd0 *cdf_n_d_d
                *cdf_n xdd0 xd0 xd1
   Plus diff mem management of: cdf_ndd:in cdf_n_dd:in cdf_nd:in
                cdf_n_d:in cdf_nd0:in cdf_n_d_d:in cdf_n:in


  Differentiation of cdf_n_d_d in forward (tangent) mode:
   variations   of useful results: *cdf_nd *cdf_n_d cdf_n_d_d
                *cdf_n
   with respect to varying inputs: xdd xd x *cdf_nd *cdf_n_d *cdf_n
                xd0
   Plus diff mem management of: cdf_nd:in cdf_n_d:in cdf_n:in


  Differentiation of cdf_n_d in forward (tangent) mode:
   variations   of useful results: cdf_n_d *cdf_n
   with respect to varying inputs: xd x *cdf_n
   Plus diff mem management of: cdf_n:in


  Differentiation of cdf_n in forward (tangent) mode:
   variations   of useful results: cdf_n
   with respect to varying inputs: x
*/
void cdf_n_d_d_d_b(double x, double *xb, double xd1, double *xd1b, double xd0,
        double *xd0b, double xd0d, double *xd0db, double xd, double *xdb, 
        double xdd0, double *xdd0b, double xdd, double *xddb, double xddd, 
        double *xdddb, double *cdf_n, double *cdf_nb, double *cdf_nd0, double 
        *cdf_nd0b, double *cdf_nd, double *cdf_ndb, double *cdf_ndd, double *
        cdf_nddb, double *cdf_n_d, double *cdf_n_db, double *cdf_n_dd, double 
        *cdf_n_ddb, double *cdf_n_d_d, double *cdf_n_d_db, double cdf_n_d_d_db
) {
    double arg1;
    double arg1b;
    double arg1d0;
    double arg1d0b;
    double arg1d;
    double arg1db;
    double arg1dd;
    double arg1ddb;
    double temp;
    double tempb;
    double tempd;
    double tempdb;
    double arg10;
    double arg10b;
    double arg10d;
    double arg10db;
    double temp0;
    double temp0b;
    double tempb0;
    double temp1;
    double tempb1;
    double tempb2;
    arg10d = -(0.70710678118654746*0.70710678118654746*2*x*xd1);
    arg10 = -(-(0.70710678118654746*x)*-(0.70710678118654746*x));
    temp0 = exp(arg10);
    arg1dd = -(0.70710678118654746*0.70710678118654746*2*(xd0*xd1+x*xd0d));
    arg1d = -(0.70710678118654746*0.70710678118654746*2*x*xd0);
    arg1d0 = -(0.70710678118654746*0.70710678118654746*2*x*xd1);
    arg1 = -(-(0.70710678118654746*x)*-(0.70710678118654746*x));
    tempd = exp(arg1)*arg1d0;
    temp = exp(arg1);
    pushReal8(temp0);
    temp0 = exp(arg1);
    tempb1 = 0.5*1.1283791671*0.70710678118654746*cdf_n_d_d_db;
    tempb0 = exp(arg1)*tempb1;
    arg1b = exp(arg1)*xd*arg1d*arg1d0*tempb1;
    temp0b = (arg1d*xdd0+xd*arg1dd)*tempb1;
    tempb2 = temp0*tempb1;
    *xddb = tempd*tempb1;
    tempdb = xdd*tempb1;
    tempb = xddd*tempb1;
    *xdddb = temp*tempb1;
    arg1ddb = xd*tempb2;
    tempb1 = 0.5*1.1283791671*0.70710678118654746*(*cdf_n_d_db);
    arg1db = xdd0*tempb2 + xd*arg1d0*tempb0 + temp0*xd*tempb1;
    *xdb = arg1dd*tempb2 + arg1d*arg1d0*tempb0 + temp0*arg1d*tempb1;
    *cdf_n_d_db = 0.0;
    temp0b = temp0b + xd*arg1d*tempb1;
    tempb = tempb + xdd*tempb1;
    *xddb = *xddb + temp*tempb1;
    popReal8(&temp0);
    tempb1 = 0.5*1.1283791671*0.70710678118654746*(*cdf_n_ddb);
    *xdd0b = arg1d*tempb2 + temp*tempb1;
    tempb = tempb + xd*0.70710678118654746*0.5*1.1283791671*(*cdf_n_db) + xdd0
        *tempb1;
    *xdb = *xdb + temp*0.70710678118654746*0.5*1.1283791671*(*cdf_n_db) + 
        tempd*tempb1;
    *cdf_n_db = 0.0;
    *cdf_n_ddb = 0.0;
    tempdb = tempdb + xd*tempb1;
    arg1d0b = xd*arg1d*tempb0 + exp(arg1)*tempdb;
    arg1b = arg1b + exp(arg1)*temp0b + exp(arg1)*tempb + exp(arg1)*arg1d0*
        tempdb;
    tempb1 = -(0.70710678118654746*0.70710678118654746*2*arg1ddb);
    *xb = xd0d*tempb1 - 2*x*(0.70710678118654746*0.70710678118654746)*arg1b - 
        xd1*(0.70710678118654746*0.70710678118654746)*2*arg1d0b - xd0*(
        0.70710678118654746*0.70710678118654746)*2*arg1db;
    *xd1b = xd0*tempb1 - x*(0.70710678118654746*0.70710678118654746)*2*arg1d0b
    ;
    *xd0b = xd1*tempb1 - x*(0.70710678118654746*0.70710678118654746)*2*arg1db;
    temp1 = -(0.70710678118654746*0.70710678118654746*(x*x));
    tempb0 = 0.70710678118654746*0.5*1.1283791671*(*cdf_nddb);
    *xd0db = x*tempb1 + temp0*tempb0;
    temp0b = xd0*0.70710678118654746*0.5*1.1283791671*(*cdf_ndb) + xd0d*tempb0
    ;
    *cdf_nddb = 0.0;
    arg10b = exp(arg10)*xd0*arg10d*tempb0 + exp(arg10)*temp0b;
    tempb1 = exp(arg10)*tempb0;
    *xd0b = *xd0b + temp0*0.70710678118654746*0.5*1.1283791671*(*cdf_ndb) + 
        arg10d*tempb1;
    *cdf_ndb = 0.0;
    arg10db = xd0*tempb1;
    *xb = *xb + 0.70710678118654746*1.1283791671*exp(-(-(0.70710678118654746*x
        )*-(0.70710678118654746*x)))*0.5*(*cdf_nb) - 2*x*pow(
        0.70710678118654746, 3)*exp(temp1)*xd1*1.1283791671*0.5*(*cdf_nd0b) - 
        2*x*(0.70710678118654746*0.70710678118654746)*arg10b - xd1*(
        0.70710678118654746*0.70710678118654746)*2*arg10db;
    *cdf_nb = 0.0;
    *xd1b = *xd1b + exp(temp1)*1.1283791671*0.70710678118654746*0.5*(*cdf_nd0b
        ) - x*(0.70710678118654746*0.70710678118654746)*2*arg10db;
    *cdf_nd0b = 0.0;
}

/*
  Differentiation of cdf_n_d_d in forward (tangent) mode:
   variations   of useful results: *cdf_nd *cdf_n_d cdf_n_d_d
                *cdf_n
   with respect to varying inputs: xdd xd x *cdf_nd *cdf_n_d *cdf_n
                xd0
   Plus diff mem management of: cdf_nd:in cdf_n_d:in cdf_n:in


  Differentiation of cdf_n_d in forward (tangent) mode:
   variations   of useful results: cdf_n_d *cdf_n
   with respect to varying inputs: xd x *cdf_n
   Plus diff mem management of: cdf_n:in


  Differentiation of cdf_n in forward (tangent) mode:
   variations   of useful results: cdf_n
   with respect to varying inputs: x
*/
double cdf_n_d_d_d_nodiff(double x, double xd1, double xd0, double xd0d, 
        double xd, double xdd0, double xdd, double xddd, double *cdf_n, double
        *cdf_nd0, double *cdf_nd, double *cdf_ndd, double *cdf_n_d, double *
        cdf_n_dd, double *cdf_n_d_d) {
    double arg1;
    double arg1d0;
    double arg1d;
    double arg1dd;
    double temp;
    double tempd;
    double arg10;
    double arg10d;
    double temp0;
    arg10d = -(0.70710678118654746*0.70710678118654746*2*x*xd1);
    arg10 = -(-(0.70710678118654746*x)*-(0.70710678118654746*x));
    temp0 = exp(arg10);
    *cdf_ndd = 1.1283791671*0.70710678118654746*0.5*(xd0*exp(arg10)*arg10d+
        temp0*xd0d);
    *cdf_nd = 1.1283791671*0.70710678118654746*0.5*(temp0*xd0);
    *cdf_nd0 = 0.5*1.1283791671*exp(-(-(0.70710678118654746*x)*-(
        0.70710678118654746*x)))*0.70710678118654746*xd1;
    *cdf_n = 0.5*erfc(x*-0.70710678118654746);
    arg1dd = -(0.70710678118654746*0.70710678118654746*2*(xd0*xd1+x*xd0d));
    arg1d = -(0.70710678118654746*0.70710678118654746*2*x*xd0);
    arg1d0 = -(0.70710678118654746*0.70710678118654746*2*x*xd1);
    arg1 = -(-(0.70710678118654746*x)*-(0.70710678118654746*x));
    tempd = exp(arg1)*arg1d0;
    temp = exp(arg1);
    *cdf_n_dd = 0.70710678118654746*0.5*1.1283791671*(xd*tempd+temp*xdd0);
    *cdf_n_d = 1.1283791671*0.70710678118654746*0.5*(temp*xd);
    temp0 = exp(arg1);
    *cdf_n_d_d = 0.70710678118654746*0.5*1.1283791671*(temp0*(xd*arg1d)+temp*
        xdd);
    return 0.70710678118654746*0.5*1.1283791671*(xd*arg1d*exp(arg1)*arg1d0+
    temp0*(arg1d*xdd0+xd*arg1dd)+xdd*tempd+temp*xddd);
}

/*
  Differentiation of call_price_d_d_d in reverse (adjoint) mode:
   gradient     of useful results: Sdd0 Td Sd0 Sd1 Kd0d v Kd0
                Tdd Kd1 Kddd Kd vd0d *call_price_dd Td0d vddd
                *call_price_d Sd0d *call_priced0 Tddd vd0 vd1
                *call_price Sddd vd Sdd call_price_d_d_d *call_priced
                Td0 Td1 Kdd0 Sd Kdd K *call_price_d_d S T vdd0
                Tdd0 *call_pricedd vdd
   with respect to varying inputs: Sdd0 Td Sd0 Sd1 Kd0d v Kd0
                Tdd Kd1 Kddd Kd vd0d *call_price_dd Td0d vddd
                *call_price_d Sd0d *call_priced0 Tddd vd0 vd1
                *call_price Sddd vd Sdd *call_priced Td0 Td1 Kdd0
                Sd Kdd K *call_price_d_d S T vdd0 Tdd0 *call_pricedd
                vdd
   RW status of diff variables: Sdd0:incr Td:incr Sd0:incr Sd1:incr
                Kd0d:incr v:incr Kd0:incr Tdd:incr Kd1:incr Kddd:incr
                Kd:incr vd0d:incr call_price_dd:(loc) *call_price_dd:in-out
                Td0d:incr vddd:incr call_price_d:(loc) *call_price_d:in-out
                Sd0d:incr call_priced0:(loc) *call_priced0:in-out
                Tddd:incr vd0:incr vd1:incr call_price:(loc) *call_price:in-out
                Sddd:incr vd:incr Sdd:incr call_price_d_d_d:in-killed
                call_priced:(loc) *call_priced:in-out Td0:incr
                Td1:incr Kdd0:incr Sd:incr Kdd:incr K:incr call_price_d_d:(loc)
                *call_price_d_d:in-out S:incr T:incr vdd0:incr
                Tdd0:incr call_pricedd:(loc) *call_pricedd:in-out
                vdd:incr
   Plus diff mem management of: call_price_dd:in call_price_d:in
                call_priced0:in call_price:in call_priced:in call_price_d_d:in
                call_pricedd:in


  Differentiation of call_price_d_d in forward (tangent) mode:
   variations   of useful results: *call_price_d *call_price *call_priced
                call_price_d_d
   with respect to varying inputs: Td Sd0 v Kd0 Tdd Kd *call_price_d
                vd0 *call_price vd Sdd *call_priced Td0 Sd Kdd
                K S T vdd
   RW status of diff variables: Td:in Sd0:in v:in Kd0:in Tdd:in
                Kd:in call_price_d:(loc) *call_price_d:in-out
                vd0:in call_price:(loc) *call_price:in-out vd:in
                Sdd:in call_priced:(loc) *call_priced:in-out Td0:in
                Sd:in Kdd:in K:in call_price_d_d:out S:in T:in
                vdd:in
   Plus diff mem management of: call_price_d:in call_price:in
                call_priced:in


  Differentiation of call_price_d in forward (tangent) mode:
   variations   of useful results: call_price_d *call_price
   with respect to varying inputs: Td v Kd *call_price vd Sd K
                S T
   RW status of diff variables: Td:in v:in Kd:in call_price_d:out
                call_price:(loc) *call_price:in-out vd:in Sd:in
                K:in S:in T:in
   Plus diff mem management of: call_price:in


  Differentiation of call_price in forward (tangent) mode:
   variations   of useful results: call_price
   with respect to varying inputs: v K S T
   RW status of diff variables: v:in call_price:out K:in S:in
                T:in
*/
void call_price_d_d_d_b(double S, double *Sb, double Sd1, double *Sd1b, double
        Sd0, double *Sd0b, double Sd0d, double *Sd0db, double Sd, double *Sdb,
        double Sdd0, double *Sdd0b, double Sdd, double *Sddb, double Sddd, 
        double *Sdddb, double K, double *Kb, double Kd1, double *Kd1b, double 
        Kd0, double *Kd0b, double Kd0d, double *Kd0db, double Kd, double *Kdb,
        double Kdd0, double *Kdd0b, double Kdd, double *Kddb, double Kddd, 
        double *Kdddb, double v, double *vb, double vd1, double *vd1b, double 
        vd0, double *vd0b, double vd0d, double *vd0db, double vd, double *vdb,
        double vdd0, double *vdd0b, double vdd, double *vddb, double vddd, 
        double *vdddb, double T, double *Tb, double Td1, double *Td1b, double 
        Td0, double *Td0b, double Td0d, double *Td0db, double Td, double *Tdb,
        double Tdd0, double *Tdd0b, double Tdd, double *Tddb, double Tddd, 
        double *Tdddb, double *call_price, double *call_priceb, double *
        call_priced0, double *call_priced0b, double *call_priced, double *
        call_pricedb, double *call_pricedd, double *call_priceddb, double *
        call_price_d, double *call_price_db, double *call_price_dd, double *
        call_price_ddb, double *call_price_d_d, double *call_price_d_db, 
        double call_price_d_d_db) {
    double totalvol;
    double totalvolb;
    double totalvold1;
    double totalvold1b;
    double totalvold0;
    double totalvold0b;
    double totalvold0d;
    double totalvold0db;
    double totalvold;
    double totalvoldb;
    double totalvoldd0;
    double totalvoldd0b;
    double totalvoldd;
    double totalvolddb;
    double totalvolddd;
    double totalvoldddb;
    double result1;
    double result1b;
    double result1d1;
    double result1d1b;
    double result1d0;
    double result1d0b;
    double result1d0d;
    double result1d0db;
    double result1d;
    double result1db;
    double result1dd0;
    double result1dd0b;
    double result1dd;
    double result1ddb;
    double result1ddd;
    double result1dddb;
    double result2;
    double result2b;
    double result2d1;
    double result2d1b;
    double result2d0;
    double result2d0b;
    double result2d0d;
    double result2d0db;
    double result2d;
    double result2db;
    double result2dd0;
    double result2dd0b;
    double result2dd;
    double result2ddb;
    double result2ddd;
    double result2dddb;
    double temp;
    double tempb;
    double tempd0;
    double tempd0b;
    double tempd;
    double tempdb;
    double tempdd;
    double tempddb;
    double temp0;
    double temp0b;
    double temp0d0;
    double temp0d0b;
    double temp0d;
    double temp0db;
    double temp0dd;
    double temp0ddb;
    double temp1;
    double temp1b;
    double temp1d;
    double temp1db;
    double temp2;
    double temp2b;
    double temp2d;
    double temp2db;
    double temp3;
    double temp3b;
    double temp4;
    double temp4b;
    double temp5;
    double temp5b;
    double temp6;
    double tempb0;
    double temp7;
    double tempb1;
    double temp8;
    double tempb2;
    double temp9;
    double tempb3;
    double tempb4;
    temp3 = sqrt(T);
    temp1d = (T == 0.0 ? 0.0 : Td1/(2.0*temp3));
    temp1 = temp3;
    temp3 = Td0/(2.0*temp1);
    tempdd = (T == 0.0 ? 0.0 : (Td0d-temp3*2.0*temp1d)/(2.0*temp1));
    tempd = (T == 0.0 ? 0.0 : temp3);
    tempd0 = temp1d;
    temp = temp1;
    temp3 = Td/(2.0*temp);
    temp1d = (Tdd0-temp3*2.0*tempd0)/(2.0*temp);
    pushReal8(temp1);
    temp1 = temp3;
    temp3 = (Tdd-2.0*temp1*tempd)/(2.0*temp);
    result1ddd = (T == 0.0 ? 0.0 : (Tddd-2.0*(tempd*temp1d+temp1*tempdd)-temp3
        *2.0*tempd0)/(2.0*temp));
    result1dd = (T == 0.0 ? 0.0 : temp3);
    result1dd0 = (T == 0.0 ? 0.0 : temp1d);
    result1d = (T == 0.0 ? 0.0 : temp1);
    result1d0d = tempdd;
    result1d0 = tempd;
    result1d1 = tempd0;
    result1 = temp;
    totalvolddd = result1d0*vdd0 + vd*result1d0d + vdd*result1d1 + result1*
        vddd + vd0*result1dd0 + result1d*vd0d + result1dd*vd1 + v*result1ddd;
    totalvoldd = vd*result1d0 + result1*vdd + result1d*vd0 + v*result1dd;
    totalvoldd0 = vd*result1d1 + result1*vdd0 + result1d*vd1 + v*result1dd0;
    totalvold = result1*vd + v*result1d;
    totalvold0d = vd0*result1d1 + result1*vd0d + result1d0*vd1 + v*result1d0d;
    totalvold0 = result1*vd0 + v*result1d0;
    totalvold1 = result1*vd1 + v*result1d1;
    totalvol = v*result1;
    temp3 = S*Kd0/K;
    temp4 = (Sd0-temp3)/K;
    tempdd = (Sd0d-(Kd0*Sd1+S*Kd0d-temp3*Kd1)/K-temp4*Kd1)/K;
    pushReal8(tempd);
    tempd = temp4;
    pushReal8(tempd0);
    tempd0 = (Sd1-S*Kd1/K)/K;
    pushReal8(temp);
    temp = S/K;
    temp4 = log(temp)/totalvol;
    temp1d = (tempd0/temp-temp4*totalvold1)/totalvol;
    pushReal8(temp1);
    temp1 = temp4;
    pushReal8(temp4);
    temp4 = (tempd/temp-temp1*totalvold0)/totalvol;
    temp0dd = ((tempdd-tempd*tempd0/temp)/temp-totalvold0*temp1d-temp1*
        totalvold0d-temp4*totalvold1)/totalvol;
    temp0d = temp4;
    temp0d0 = temp1d;
    temp0 = temp1;
    double d1 = temp0 + 0.5*totalvol;
    double d1b = 0.0;
    double d1d1 = temp0d0 + 0.5*totalvold1;
    double d1d1b = 0.0;
    double d1d0 = temp0d + 0.5*totalvold0;
    double d1d0b = 0.0;
    double d1d0d = temp0dd + 0.5*totalvold0d;
    double d1d0db = 0.0;
    temp4 = (Sd-temp*Kd)/(temp*K);
    pushReal8(temp1d);
    temp1d = (Sdd0-Kd*tempd0-temp*Kdd0-temp4*(K*tempd0+temp*Kd1))/(temp*K);
    pushReal8(temp1);
    temp1 = temp4;
    temp4 = (temp1-temp0*totalvold)/totalvol;
    temp2d = (temp1d-totalvold*temp0d0-temp0*totalvoldd0-temp4*totalvold1)/
        totalvol;
    temp2 = temp4;
    double d1d = temp2 + 0.5*totalvold;
    double d1db = 0.0;
    double d1dd0 = temp2d + 0.5*totalvoldd0;
    double d1dd0b = 0.0;
    temp4 = K*tempd + temp*Kd0;
    temp3 = (Sdd-Kd*tempd-temp*Kdd-temp1*temp4)/(temp*K);
    temp5 = (temp3-totalvold*temp0d-temp0*totalvoldd-temp2*totalvold0)/
        totalvol;
    double d1dd = temp5 + 0.5*totalvoldd;
    double d1ddb = 0.0;
    double d1ddd = ((Sddd-tempd*Kdd0-Kd*tempdd-Kdd*tempd0-temp*Kddd-temp4*
    temp1d-temp1*(tempd*Kd1+K*tempdd+Kd0*tempd0+temp*Kd0d)-temp3*(K*tempd0+
    temp*Kd1))/(temp*K)-temp0d*totalvoldd0-totalvold*temp0dd-totalvoldd*
    temp0d0-temp0*totalvolddd-totalvold0*temp2d-temp2*totalvold0d-temp5*
    totalvold1)/totalvol + 0.5*totalvolddd;
    double d1dddb = 0.0;
    double d2 = d1 - totalvol;
    double d2b = 0.0;
    double d2d1 = d1d1 - totalvold1;
    double d2d1b = 0.0;
    double d2d0 = d1d0 - totalvold0;
    double d2d0b = 0.0;
    double d2d0d = d1d0d - totalvold0d;
    double d2d0db = 0.0;
    double d2d = d1d - totalvold;
    double d2db = 0.0;
    double d2dd0 = d1dd0 - totalvoldd0;
    double d2dd0b = 0.0;
    double d2dd = d1dd - totalvoldd;
    double d2ddb = 0.0;
    double d2ddd = d1ddd - totalvolddd;
    double d2dddb = 0.0;
    pushReal8(result1ddd);
    pushReal8(result1dd);
    pushReal8(result1dd0);
    pushReal8(result1d);
    pushReal8(result1d0d);
    pushReal8(result1d0);
    pushReal8(result1d1);
    pushReal8(result1);
    result1ddd = cdf_n_d_d_d_nodiff(d1, d1d1, d1d0, d1d0d, d1d, d1dd0, d1dd, 
                                    d1ddd, &result1, &result1d1, &result1d0, &
                                    result1d0d, &result1d, &result1dd0, &
                                    result1dd);
    result2d0 = 0.0;
    result2dd0 = 0.0;
    result2d0d = 0.0;
    result2d1 = 0.0;
    result2ddd = cdf_n_d_d_d_nodiff(d2, d2d1, d2d0, d2d0d, d2d, d2dd0, d2dd, 
                                    d2ddd, &result2, &result2d1, &result2d0, &
                                    result2d0d, &result2d, &result2dd0, &
                                    result2dd);
    result1d0b = Sdd0*call_price_d_d_db + Sd*(*call_price_d_db) + S*(*
        call_pricedb) + Sd1*(*call_priceddb);
    *Sdd0b = *Sdd0b + result1d0*call_price_d_d_db + result1*(*call_price_ddb);
    *Sdb = *Sdb + result1d0d*call_price_d_d_db + result1d0*(*call_price_d_db) 
        + result1*(*call_price_db) + result1d1*(*call_price_ddb);
    result1d0db = Sd*call_price_d_d_db + S*(*call_priceddb);
    *Sddb = *Sddb + result1d1*call_price_d_d_db + result1*(*call_price_d_db);
    result1d1b = Sdd*call_price_d_d_db + Sd*(*call_price_ddb) + S*(*
        call_priced0b) + Sd0*(*call_priceddb);
    result1b = Sddd*call_price_d_d_db + Sdd*(*call_price_d_db) + Sd*(*
        call_price_db) + Sdd0*(*call_price_ddb) + S*(*call_priceb) + Sd1*(*
        call_priced0b) + Sd0*(*call_pricedb) + Sd0d*(*call_priceddb);
    *Sdddb = *Sdddb + result1*call_price_d_d_db;
    *Sd0b = *Sd0b + result1dd0*call_price_d_d_db + result1d*(*call_price_d_db)
        + result1*(*call_pricedb) + result1d1*(*call_priceddb);
    result1dd0b = Sd0*call_price_d_d_db + S*(*call_price_ddb);
    result1db = Sd0d*call_price_d_d_db + Sd0*(*call_price_d_db) + S*(*
        call_price_db) + Sd1*(*call_price_ddb);
    *Sd0db = *Sd0db + result1d*call_price_d_d_db + result1*(*call_priceddb);
    result1ddb = Sd1*call_price_d_d_db + S*(*call_price_d_db);
    *Sd1b = *Sd1b + result1dd*call_price_d_d_db + result1d*(*call_price_ddb) +
        result1*(*call_priced0b) + result1d0*(*call_priceddb);
    *Sb = *Sb + result1ddd*call_price_d_d_db + result1dd*(*call_price_d_db) + 
        result1d*(*call_price_db) + result1dd0*(*call_price_ddb) + result1*(*
        call_priceb) + result1d1*(*call_priced0b) + result1d0*(*call_pricedb) 
        + result1d0d*(*call_priceddb);
    result1dddb = S*call_price_d_d_db;
    result2d0b = -(Kdd0*call_price_d_d_db) - Kd*(*call_price_d_db) - K*(*
        call_pricedb) - Kd1*(*call_priceddb);
    *Kdd0b = *Kdd0b - result2d0*call_price_d_d_db - result2*(*call_price_ddb);
    *Kdb = *Kdb - result2d0d*call_price_d_d_db - result2d0*(*call_price_d_db) 
        - result2*(*call_price_db) - result2d1*(*call_price_ddb);
    result2d0db = -(Kd*call_price_d_d_db) - K*(*call_priceddb);
    *Kddb = *Kddb - result2d1*call_price_d_d_db - result2*(*call_price_d_db);
    result2d1b = -(Kdd*call_price_d_d_db) - Kd*(*call_price_ddb) - K*(*
        call_priced0b) - Kd0*(*call_priceddb);
    result2b = -(Kddd*call_price_d_d_db) - Kdd*(*call_price_d_db) - Kd*(*
        call_price_db) - Kdd0*(*call_price_ddb) - K*(*call_priceb) - Kd1*(*
        call_priced0b) - Kd0*(*call_pricedb) - Kd0d*(*call_priceddb);
    *Kdddb = *Kdddb - result2*call_price_d_d_db;
    *Kd0b = *Kd0b - result2dd0*call_price_d_d_db - result2d*(*call_price_d_db)
        - result2*(*call_pricedb) - result2d1*(*call_priceddb);
    result2dd0b = -(Kd0*call_price_d_d_db) - K*(*call_price_ddb);
    result2db = -(Kd0d*call_price_d_d_db) - Kd0*(*call_price_d_db) - K*(*
        call_price_db) - Kd1*(*call_price_ddb);
    *Kd0db = *Kd0db - result2d*call_price_d_d_db - result2*(*call_priceddb);
    result2ddb = -(Kd1*call_price_d_d_db) - K*(*call_price_d_db);
    *Kd1b = *Kd1b - result2dd*call_price_d_d_db - result2d*(*call_price_ddb) -
        result2*(*call_priced0b) - result2d0*(*call_priceddb);
    *Kb = *Kb - result2ddd*call_price_d_d_db - result2dd*(*call_price_d_db) - 
        result2d*(*call_price_db) - result2dd0*(*call_price_ddb) - result2*(*
        call_priceb) - result2d1*(*call_priced0b) - result2d0*(*call_pricedb) 
        - result2d0d*(*call_priceddb);
    result2dddb = -(K*call_price_d_d_db);
    *call_price_d_db = 0.0;
    *call_price_db = 0.0;
    *call_price_ddb = 0.0;
    *call_priceb = 0.0;
    *call_priced0b = 0.0;
    *call_pricedb = 0.0;
    *call_priceddb = 0.0;
    d2b = 0.0;
    d2d1b = 0.0;
    d2d0b = 0.0;
    d2d0db = 0.0;
    d2db = 0.0;
    d2dd0b = 0.0;
    d2ddb = 0.0;
    d2dddb = 0.0;
    cdf_n_d_d_d_b(d2, &d2b, d2d1, &d2d1b, d2d0, &d2d0b, d2d0d, &d2d0db, d2d, &
                  d2db, d2dd0, &d2dd0b, d2dd, &d2ddb, d2ddd, &d2dddb, &result2
                  , &result2b, &result2d1, &result2d1b, &result2d0, &
                  result2d0b, &result2d0d, &result2d0db, &result2d, &result2db
                  , &result2dd0, &result2dd0b, &result2dd, &result2ddb, 
                  result2dddb);
    popReal8(&result1);
    popReal8(&result1d1);
    popReal8(&result1d0);
    popReal8(&result1d0d);
    popReal8(&result1d);
    popReal8(&result1dd0);
    popReal8(&result1dd);
    popReal8(&result1ddd);
    d1b = 0.0;
    d1d1b = 0.0;
    d1d0b = 0.0;
    d1d0db = 0.0;
    d1db = 0.0;
    d1dd0b = 0.0;
    d1ddb = 0.0;
    d1dddb = 0.0;
    cdf_n_d_d_d_b(d1, &d1b, d1d1, &d1d1b, d1d0, &d1d0b, d1d0d, &d1d0db, d1d, &
                  d1db, d1dd0, &d1dd0b, d1dd, &d1ddb, d1ddd, &d1dddb, &result1
                  , &result1b, &result1d1, &result1d1b, &result1d0, &
                  result1d0b, &result1d0d, &result1d0db, &result1d, &result1db
                  , &result1dd0, &result1dd0b, &result1dd, &result1ddb, 
                  result1dddb);
    d1dddb = d1dddb + d2dddb;
    d1ddb = d1ddb + d2ddb;
    d1dd0b = d1dd0b + d2dd0b;
    d1db = d1db + d2db;
    d1d0db = d1d0db + d2d0db;
    d1d0b = d1d0b + d2d0b;
    d1d1b = d1d1b + d2d1b;
    d1b = d1b + d2b;
    temp6 = tempd*Kd1 + K*tempdd + Kd0*tempd0 + temp*Kd0d;
    temp9 = K*tempd0 + temp*Kd1;
    temp7 = (Sddd-tempd*Kdd0-Kd*tempdd-Kdd*tempd0-temp*Kddd-temp4*temp1d-temp1
        *temp6-temp3*temp9)/(temp*K);
    tempb2 = d1dddb/totalvol;
    totalvoldddb = 0.5*d1dddb - d2dddb - temp0*tempb2;
    totalvolddb = -d2ddb - temp0d0*tempb2;
    totalvoldd0b = -d2dd0b - temp0d*tempb2;
    totalvoldb = -d2db - temp0dd*tempb2;
    totalvold0db = -d2d0db - temp2*tempb2;
    totalvold0b = -d2d0b - temp2d*tempb2;
    totalvold1b = -d2d1b - temp5*tempb2;
    totalvolb = -d2b - (temp7-temp0d*totalvoldd0-totalvold*temp0dd-totalvoldd*
        temp0d0-temp0*totalvolddd-totalvold0*temp2d-temp2*totalvold0d-temp5*
        totalvold1)*tempb2/totalvol;
    tempb1 = tempb2/(temp*K);
    temp0db = -(totalvoldd0*tempb2);
    temp0ddb = d1d0db - totalvold*tempb2;
    temp0d0b = -(totalvoldd*tempb2);
    temp0b = -(totalvolddd*tempb2);
    temp2db = d1dd0b - totalvold0*tempb2;
    temp2b = -(totalvold0d*tempb2);
    temp5b = d1ddb - totalvold1*tempb2;
    *Sdddb = *Sdddb + tempb1;
    *Kdd0b = *Kdd0b - tempd*tempb1;
    tempd0b = -(Kdd*tempb1);
    tempb = -(Kddd*tempb1);
    *Kdddb = *Kdddb - temp*tempb1;
    temp1db = -(temp4*tempb1);
    tempb0 = -(temp1*tempb1);
    tempddb = K*tempb0 - Kd*tempb1;
    tempb3 = -(temp3*tempb1);
    tempb4 = -(temp7*tempb1);
    *Kd0db = *Kd0db + temp*tempb0;
    tempb2 = temp5b/totalvol;
    temp3b = tempb2 - temp9*tempb1;
    totalvolddb = totalvolddb + 0.5*d1ddb - temp0*tempb2;
    totalvoldb = totalvoldb - temp0d*tempb2;
    temp0db = temp0db + d1d0b - totalvold*tempb2;
    temp0b = temp0b - totalvoldd*tempb2;
    temp2b = temp2b + d1db - totalvold0*tempb2;
    totalvold0b = totalvold0b - temp2*tempb2;
    totalvolb = totalvolb - (temp3-totalvold*temp0d-temp0*totalvoldd-temp2*
        totalvold0)*tempb2/totalvol;
    tempb2 = temp3b/(temp*K);
    *Kdb = *Kdb - tempdd*tempb1 - tempd*tempb2;
    *Kddb = *Kddb - tempd0*tempb1 - temp*tempb2;
    temp4b = -(temp1d*tempb1) - temp1*tempb2;
    tempdb = Kd1*tempb0 - Kdd0*tempb1 + K*temp4b - Kd*tempb2;
    temp1b = -(temp6*tempb1) - temp4*tempb2;
    *Kd0b = *Kd0b + tempd0*tempb0 + temp*temp4b;
    *Sddb = *Sddb + tempb2;
    tempb1 = -((Sdd-Kd*tempd-temp*Kdd-temp1*temp4)*tempb2/(temp*K));
    tempb = tempb + K*tempb4 + Kd1*tempb3 + Kd0d*tempb0 + K*tempb1 - Kdd*
        tempb2 + Kd0*temp4b;
    *Kb = *Kb + temp*tempb4 + tempd0*tempb3 + tempdd*tempb0 + temp*tempb1 + 
        tempd*temp4b;
    temp4 = (temp1-temp0*totalvold)/totalvol;
    tempb2 = temp2db/totalvol;
    totalvoldd0b = totalvoldd0b + 0.5*d1dd0b - temp0*tempb2;
    totalvoldb = totalvoldb + 0.5*d1db - temp0d0*tempb2;
    temp4b = temp2b - totalvold1*tempb2;
    temp1db = temp1db + tempb2;
    temp0d0b = temp0d0b + d1d1b - totalvold*tempb2;
    temp0b = temp0b - totalvoldd0*tempb2;
    totalvold1b = totalvold1b - temp4*tempb2;
    totalvolb = totalvolb - (temp1d-totalvold*temp0d0-temp0*totalvoldd0-temp4*
        totalvold1)*tempb2/totalvol;
    tempb2 = temp4b/totalvol;
    temp1b = temp1b + tempb2;
    temp0b = temp0b + d1b - totalvold*tempb2;
    totalvoldb = totalvoldb - temp0*tempb2;
    totalvolb = totalvolb - (temp1-temp0*totalvold)*tempb2/totalvol;
    temp4 = (Sd-temp*Kd)/(temp*K);
    popReal8(&temp1);
    popReal8(&temp1d);
    temp7 = K*tempd0 + temp*Kd1;
    tempb2 = temp1db/(temp*K);
    temp4b = temp1b - temp7*tempb2;
    *Sdd0b = *Sdd0b + tempb2;
    *Kdb = *Kdb - tempd0*tempb2;
    *Kdd0b = *Kdd0b - temp*tempb2;
    tempb1 = -(temp4*tempb2);
    tempd0b = tempd0b + K*tempb3 + Kd0*tempb0 + K*tempb1 - Kd*tempb2;
    *Kd1b = *Kd1b + temp*tempb3 + tempd*tempb0 + temp*tempb1;
    tempb0 = -((Sdd0-Kd*tempd0-temp*Kdd0-temp4*temp7)*tempb2/(temp*K));
    tempb = tempb + K*tempb0 - Kdd0*tempb2 + Kd1*tempb1;
    *Kb = *Kb + temp*tempb0 + tempd0*tempb1;
    tempb2 = temp4b/(temp*K);
    *Sdb = *Sdb + tempb2;
    *Kdb = *Kdb - temp*tempb2;
    tempb1 = -((Sd-temp*Kd)*tempb2/(temp*K));
    tempb = tempb + K*tempb1 - Kd*tempb2;
    *Kb = *Kb + temp*tempb1;
    temp4 = (tempd/temp-temp1*totalvold0)/totalvol;
    temp8 = tempd*tempd0/temp;
    temp6 = (tempdd-temp8)/temp;
    tempb1 = temp0ddb/totalvol;
    totalvold0db = totalvold0db + 0.5*d1d0db - temp1*tempb1;
    totalvold0b = totalvold0b + 0.5*d1d0b - temp1d*tempb1;
    totalvold1b = totalvold1b + 0.5*d1d1b - temp4*tempb1;
    totalvolb = totalvolb + 0.5*d1b - (temp6-totalvold0*temp1d-temp1*
        totalvold0d-temp4*totalvold1)*tempb1/totalvol;
    temp1b = temp0b - totalvold0d*tempb1;
    temp1db = temp0d0b - totalvold0*tempb1;
    temp4b = temp0db - totalvold1*tempb1;
    tempb0 = tempb1/temp;
    tempddb = tempddb + tempb0;
    tempb2 = -(tempb0/temp);
    popReal8(&temp4);
    tempb1 = temp4b/totalvol;
    tempb = tempb - temp6*tempb0 - temp8*tempb2 - tempd*tempb1/(temp*temp);
    tempdb = tempdb + tempd0*tempb2 + tempb1/temp;
    temp1b = temp1b - totalvold0*tempb1;
    totalvold0b = totalvold0b - temp1*tempb1;
    totalvolb = totalvolb - (tempd/temp-temp1*totalvold0)*tempb1/totalvol;
    popReal8(&temp1);
    tempb1 = temp1db/totalvol;
    tempd0b = tempd0b + tempd*tempb2 + tempb1/temp;
    temp4b = temp1b - totalvold1*tempb1;
    tempb = tempb + temp4b/(temp*totalvol) - tempd0*tempb1/(temp*temp);
    totalvold1b = totalvold1b - temp4*tempb1;
    totalvolb = totalvolb - (tempd0/temp-temp4*totalvold1)*tempb1/totalvol - 
        log(temp)*temp4b/(totalvol*totalvol);
    temp3 = S*Kd0/K;
    temp4 = (Sd0-temp3)/K;
    popReal8(&temp);
    popReal8(&tempd0);
    temp6 = S*Kd1/K;
    tempb1 = tempd0b/K;
    *Sd1b = *Sd1b + tempb1;
    tempb0 = -(tempb1/K);
    *Sb = *Sb + tempb/K + Kd1*tempb0;
    *Kb = *Kb - S*tempb/(K*K) - (Sd1-temp6)*tempb1/K - temp6*tempb0;
    *Kd1b = *Kd1b + S*tempb0;
    popReal8(&tempd);
    temp6 = (Kd0*Sd1+S*Kd0d-temp3*Kd1)/K;
    tempb1 = tempddb/K;
    temp4b = tempdb - Kd1*tempb1;
    *Sd0db = *Sd0db + tempb1;
    tempb0 = -(tempb1/K);
    *Kd1b = *Kd1b - temp4*tempb1 - temp3*tempb0;
    *Kb = *Kb - (Sd0d-temp6-temp4*Kd1)*tempb1/K;
    *Sd1b = *Sd1b + Kd0*tempb0;
    *Kd0db = *Kd0db + S*tempb0;
    tempb1 = temp4b/K;
    temp3b = -(Kd1*tempb0) - tempb1;
    *Kb = *Kb - temp6*tempb0 - (Sd0-temp3)*tempb1/K;
    *Sd0b = *Sd0b + tempb1;
    tempb1 = temp3b/K;
    *Kd0b = *Kd0b + Sd1*tempb0 + S*tempb1;
    *Sb = *Sb + Kd0d*tempb0 + Kd0*tempb1;
    *Kb = *Kb - S*Kd0*tempb1/K;
    *vb = *vb + result1*totalvolb + result1d1*totalvold1b + result1d0*
        totalvold0b + result1d0d*totalvold0db + result1d*totalvoldb + 
        result1dd0*totalvoldd0b + result1dd*totalvolddb + result1ddd*
        totalvoldddb;
    result1b = result1b + v*totalvolb + vd1*totalvold1b + vd0*totalvold0b + 
        vd0d*totalvold0db + vd*totalvoldb + vdd0*totalvoldd0b + vdd*
        totalvolddb + vddd*totalvoldddb;
    *vd1b = *vd1b + result1*totalvold1b + result1d0*totalvold0db + result1d*
        totalvoldd0b + result1dd*totalvoldddb;
    result1d1b = result1d1b + v*totalvold1b + vd0*totalvold0db + vd*
        totalvoldd0b + vdd*totalvoldddb;
    *vd0b = *vd0b + result1*totalvold0b + result1d1*totalvold0db + result1d*
        totalvolddb + result1dd0*totalvoldddb;
    result1d0b = result1d0b + v*totalvold0b + vd1*totalvold0db + vd*
        totalvolddb + vdd0*totalvoldddb;
    *vd0db = *vd0db + result1*totalvold0db + result1d*totalvoldddb;
    result1d0db = result1d0db + v*totalvold0db + vd*totalvoldddb;
    *vdb = *vdb + result1*totalvoldb + result1d1*totalvoldd0b + result1d0*
        totalvolddb + result1d0d*totalvoldddb;
    result1db = result1db + v*totalvoldb + vd1*totalvoldd0b + vd0*totalvolddb 
        + vd0d*totalvoldddb;
    *vdd0b = *vdd0b + result1*totalvoldd0b + result1d0*totalvoldddb;
    result1dd0b = result1dd0b + v*totalvoldd0b + vd0*totalvoldddb;
    *vddb = *vddb + result1*totalvolddb + result1d1*totalvoldddb;
    result1ddb = result1ddb + v*totalvolddb + vd1*totalvoldddb;
    *vdddb = *vdddb + result1*totalvoldddb;
    result1dddb = v*totalvoldddb;
    tempb0 = (T == 0.0 ? 0.0 : result1dddb/(2.0*temp));
    tempb = result1b - (Tddd-2.0*(tempd*temp1d+temp1*tempdd)-2.0*(temp3*tempd0
        ))*tempb0/temp;
    tempd0b = result1d1b - temp3*2.0*tempb0;
    temp3b = (T == 0.0 ? -(tempd0*2.0*tempb0) : result1ddb - tempd0*2.0*tempb0
        );
    *Tdddb = *Tdddb + tempb0;
    tempb1 = -(2.0*tempb0);
    tempddb = result1d0db + temp1*tempb1;
    temp1db = (T == 0.0 ? tempd*tempb1 : result1dd0b + tempd*tempb1);
    tempb0 = temp3b/(2.0*temp);
    tempdb = result1d0b + temp1d*tempb1 - temp1*2.0*tempb0;
    temp1b = (T == 0.0 ? tempdd*tempb1 - tempd*2.0*tempb0 : result1db + tempdd
        *tempb1 - tempd*2.0*tempb0);
    *Tddb = *Tddb + tempb0;
    tempb = tempb - (Tdd-2.0*(temp1*tempd))*tempb0/temp;
    temp3 = Td/(2.0*temp);
    popReal8(&temp1);
    tempb0 = temp1db/(2.0*temp);
    temp3b = temp1b - tempd0*2.0*tempb0;
    *Tdd0b = *Tdd0b + tempb0;
    tempd0b = tempd0b - temp3*2.0*tempb0;
    tempb = tempb - (Tdd0-2.0*(temp3*tempd0))*tempb0/temp;
    tempb0 = temp3b/(2.0*temp);
    *Tdb = *Tdb + tempb0;
    tempb = tempb - Td*tempb0/temp;
    tempb0 = (T == 0.0 ? 0.0 : tempddb/(2.0*temp1));
    temp1b = tempb - (Td0d-2.0*(temp3*temp1d))*tempb0/temp1;
    temp1db = tempd0b - temp3*2.0*tempb0;
    temp3b = (T == 0.0 ? -(temp1d*2.0*tempb0) : tempdb - temp1d*2.0*tempb0);
    *Td0db = *Td0db + tempb0;
    tempb0 = temp3b/(2.0*temp1);
    *Td0b = *Td0b + tempb0;
    temp1b = temp1b - Td0*tempb0/temp1;
    tempb0 = (T == 0.0 ? 0.0 : temp1db/(2.0*temp3));
    temp3b = temp1b - Td1*tempb0/temp3;
    *Td1b = *Td1b + tempb0;
    if (!(T==0.0))
        *Tb = *Tb + temp3b/(2.0*sqrt(T));
}
