/*        Generated by TAPENADE     (INRIA, Ecuador team)
    Tapenade 3.16 (develop) - 25 Oct 2024 09:00
*/
#include <adStack.h>
/*        Generated by TAPENADE     (INRIA, Ecuador team)
    Tapenade 3.16 (develop) - 25 Oct 2024 09:00

        Generated by TAPENADE     (INRIA, Ecuador team)
    Tapenade 3.16 (develop) - 25 Oct 2024 09:00

        Generated by TAPENADE     (INRIA, Ecuador team)
    Tapenade 3.16 (develop) - 25 Oct 2024 09:00

        Generated by TAPENADE     (INRIA, Ecuador team)
    Tapenade 3.16 (develop) - 25 Oct 2024 09:00
*/
#include <math.h>
#include <stdio.h>

/*
  Differentiation of cdf_n_d_d_d_d in reverse (adjoint) mode:
   gradient     of useful results: *cdf_ndd *cdf_nd0d *cdf_n_ddd
                *cdf_n_dd *cdf_nddd *cdf_n_d_dd *cdf_nd *cdf_n_d
                *cdf_nd0 *cdf_nd1 *cdf_n_d_d *cdf_n *cdf_n_dd0
                *cdf_ndd0 *cdf_n_d_d_d cdf_n_d_d_d_d
   with respect to varying inputs: *cdf_ndd *cdf_nd0d xdd0d xd0d
                *cdf_n_ddd *cdf_n_dd *cdf_nddd xdddd xddd xdd
                xd x *cdf_n_d_dd xd1d *cdf_nd *cdf_n_d *cdf_nd0
                xd0dd *cdf_nd1 *cdf_n_d_d *cdf_n *cdf_n_dd0 *cdf_ndd0
                xddd0 xdd0 xd0 xdd1 xd1 xd2 *cdf_n_d_d_d xd0d0
   Plus diff mem management of: cdf_ndd:in cdf_nd0d:in cdf_n_ddd:in
                cdf_n_dd:in cdf_nddd:in cdf_n_d_dd:in cdf_nd:in
                cdf_n_d:in cdf_nd0:in cdf_nd1:in cdf_n_d_d:in
                cdf_n:in cdf_n_dd0:in cdf_ndd0:in cdf_n_d_d_d:in


  Differentiation of cdf_n_d_d_d in forward (tangent) mode:
   variations   of useful results: *cdf_ndd *cdf_n_dd *cdf_nd
                *cdf_n_d *cdf_nd0 *cdf_n_d_d *cdf_n cdf_n_d_d_d
   with respect to varying inputs: *cdf_ndd xd0d *cdf_n_dd xddd
                xdd xd x *cdf_nd *cdf_n_d *cdf_nd0 *cdf_n_d_d
                *cdf_n xdd0 xd0 xd1
   Plus diff mem management of: cdf_ndd:in cdf_n_dd:in cdf_nd:in
                cdf_n_d:in cdf_nd0:in cdf_n_d_d:in cdf_n:in


  Differentiation of cdf_n_d_d in forward (tangent) mode:
   variations   of useful results: *cdf_nd *cdf_n_d cdf_n_d_d
                *cdf_n
   with respect to varying inputs: xdd xd x *cdf_nd *cdf_n_d *cdf_n
                xd0
   Plus diff mem management of: cdf_nd:in cdf_n_d:in cdf_n:in


  Differentiation of cdf_n_d in forward (tangent) mode:
   variations   of useful results: cdf_n_d *cdf_n
   with respect to varying inputs: xd x *cdf_n
   Plus diff mem management of: cdf_n:in


  Differentiation of cdf_n in forward (tangent) mode:
   variations   of useful results: cdf_n
   with respect to varying inputs: x
*/
void cdf_n_d_d_d_d_b(double x, double *xb, double xd2, double *xd2b, double 
        xd1, double *xd1b, double xd1d, double *xd1db, double xd0, double *
        xd0b, double xd0d0, double *xd0d0b, double xd0d, double *xd0db, double
        xd0dd, double *xd0ddb, double xd, double *xdb, double xdd1, double *
        xdd1b, double xdd0, double *xdd0b, double xdd0d, double *xdd0db, 
        double xdd, double *xddb, double xddd0, double *xddd0b, double xddd, 
        double *xdddb, double xdddd, double *xddddb, double *cdf_n, double *
        cdf_nb, double *cdf_nd1, double *cdf_nd1b, double *cdf_nd0, double *
        cdf_nd0b, double *cdf_nd0d, double *cdf_nd0db, double *cdf_nd, double 
        *cdf_ndb, double *cdf_ndd0, double *cdf_ndd0b, double *cdf_ndd, double
        *cdf_nddb, double *cdf_nddd, double *cdf_ndddb, double *cdf_n_d, 
        double *cdf_n_db, double *cdf_n_dd0, double *cdf_n_dd0b, double *
        cdf_n_dd, double *cdf_n_ddb, double *cdf_n_ddd, double *cdf_n_dddb, 
        double *cdf_n_d_d, double *cdf_n_d_db, double *cdf_n_d_dd, double *
        cdf_n_d_ddb, double *cdf_n_d_d_d, double *cdf_n_d_d_db, double 
        cdf_n_d_d_d_db) {
    double arg1;
    double arg1b;
    double arg1d1;
    double arg1d1b;
    double arg1d0;
    double arg1d0b;
    double arg1d0d;
    double arg1d0db;
    double arg1d;
    double arg1db;
    double arg1dd0;
    double arg1dd0b;
    double arg1dd;
    double arg1ddb;
    double arg1ddd;
    double arg1dddb;
    double temp;
    double tempb;
    double tempd0;
    double tempd0b;
    double tempd;
    double tempdb;
    double tempdd;
    double tempddb;
    double arg10;
    double arg10b;
    double arg10d0;
    double arg10d0b;
    double arg10d;
    double arg10db;
    double arg10dd;
    double arg10ddb;
    double temp0;
    double temp0b;
    double temp0d;
    double temp0db;
    double arg11;
    double arg11b;
    double arg11d;
    double arg11db;
    double temp1;
    double temp1b;
    double temp2;
    double temp2b;
    double temp3;
    double temp3b;
    double tempb0;
    double temp4;
    double tempb1;
    double temp5;
    double tempb2;
    double tempb3;
    double tempb4;
    arg10dd = -(0.70710678118654746*0.70710678118654746*2*(xd1*xd2+x*xd1d));
    arg10d = -(0.70710678118654746*0.70710678118654746*2*x*xd1);
    arg10d0 = -(0.70710678118654746*0.70710678118654746*2*x*xd2);
    arg10 = -(-(0.70710678118654746*x)*-(0.70710678118654746*x));
    temp0d = exp(arg10)*arg10d0;
    temp0 = exp(arg10);
    temp1 = exp(arg10);
    arg11d = -(0.70710678118654746*0.70710678118654746*2*x*xd2);
    arg11 = -(-(0.70710678118654746*x)*-(0.70710678118654746*x));
    pushReal8(temp1);
    temp1 = exp(arg11);
    arg1ddd = -(0.70710678118654746*0.70710678118654746*2*(xd1*xd0d0+xd0*xd1d+
        xd0d*xd2+x*xd0dd));
    arg1dd = -(0.70710678118654746*0.70710678118654746*2*(xd0*xd1+x*xd0d));
    arg1dd0 = -(0.70710678118654746*0.70710678118654746*2*(xd0*xd2+x*xd0d0));
    arg1d = -(0.70710678118654746*0.70710678118654746*2*x*xd0);
    arg1d0d = -(0.70710678118654746*0.70710678118654746*2*(xd1*xd2+x*xd1d));
    arg1d0 = -(0.70710678118654746*0.70710678118654746*2*x*xd1);
    arg1d1 = -(0.70710678118654746*0.70710678118654746*2*x*xd2);
    arg1 = -(-(0.70710678118654746*x)*-(0.70710678118654746*x));
    pushReal8(temp1);
    temp1 = exp(arg1);
    tempdd = arg1d0*exp(arg1)*arg1d1 + temp1*arg1d0d;
    tempd = temp1*arg1d0;
    tempd0 = exp(arg1)*arg1d1;
    temp = exp(arg1);
    pushReal8(temp0d);
    temp0d = exp(arg1)*arg1d1;
    pushReal8(temp0);
    temp0 = exp(arg1);
    pushReal8(temp1);
    temp1 = exp(arg1);
    temp2 = xd*arg1d*arg1d0;
    temp3 = arg1d*xdd0 + xd*arg1dd;
    temp4 = arg1d*xdd1 + xd*arg1dd0;
    tempb2 = 1.1283791671*0.70710678118654746*0.5*cdf_n_d_d_d_db;
    temp1b = (arg1d0*temp4+xd*arg1d*arg1d0d)*tempb2;
    tempb0 = temp1*tempb2;
    arg1b = exp(arg1)*temp2*arg1d1*tempb2;
    tempb3 = exp(arg1)*tempb2;
    temp3b = temp0d*tempb2;
    temp0db = temp3*tempb2;
    temp0b = (xdd0*arg1dd0+arg1d*xdd0d+arg1dd*xdd1+xd*arg1ddd)*tempb2;
    tempb4 = temp0*tempb2;
    tempdb = xddd0*tempb2;
    *xddd0b = tempd*tempb2;
    *xddb = tempdd*tempb2;
    tempddb = xdd*tempb2;
    *xdddb = tempd0*tempb2;
    tempd0b = xddd*tempb2;
    tempb = xdddd*tempb2;
    *xddddb = temp*tempb2;
    arg1dddb = xd*tempb4;
    tempb1 = arg1d0*tempb0;
    *xdd1b = arg1dd*tempb4 + arg1d*tempb1;
    tempb2 = 1.1283791671*0.70710678118654746*0.5*(*cdf_n_d_d_db);
    temp2b = arg1d1*tempb3 + temp1*tempb2;
    *cdf_n_d_d_db = 0.0;
    temp1b = temp1b + temp2*tempb2;
    temp0b = temp0b + temp3*tempb2;
    temp3b = temp3b + temp0*tempb2;
    arg1ddb = xdd1*tempb4 + xd*temp3b;
    *xddb = *xddb + tempd*tempb2;
    tempdb = tempdb + xdd*tempb2;
    tempb = tempb + xddd*tempb2;
    *xdddb = *xdddb + temp*tempb2;
    popReal8(&temp1);
    arg1b = arg1b + exp(arg1)*temp1b;
    tempb2 = 0.5*1.1283791671*0.70710678118654746*(*cdf_n_d_db);
    arg1db = xdd0d*tempb4 + xd*arg1d0d*tempb0 + xdd1*tempb1 + xdd0*temp3b + xd
        *arg1d0*temp2b + temp0*xd*tempb2;
    *xdb = arg1ddd*tempb4 + arg1d*arg1d0d*tempb0 + arg1dd0*tempb1 + arg1dd*
        temp3b + arg1d*arg1d0*temp2b + temp0*arg1d*tempb2;
    *cdf_n_d_db = 0.0;
    temp0b = temp0b + xd*arg1d*tempb2;
    tempb = tempb + xdd*tempb2;
    *xddb = *xddb + temp*tempb2;
    tempb2 = 1.1283791671*0.70710678118654746*0.5*(*cdf_n_d_ddb);
    arg1dd0b = xdd0*tempb4 + xd*tempb1 + temp0*xd*tempb2;
    *cdf_n_d_ddb = 0.0;
    arg1db = arg1db + (xd*temp0d+temp0*xdd1)*tempb2;
    tempb1 = arg1d*tempb2;
    temp0b = temp0b + xd*arg1dd0*tempb2 + xdd1*tempb1;
    *xdb = *xdb + temp0*arg1dd0*tempb2;
    *xddb = *xddb + tempd0*tempb2;
    tempd0b = tempd0b + xdd*tempb2;
    tempb = tempb + xddd0*tempb2;
    *xddd0b = *xddd0b + temp*tempb2;
    temp0db = temp0db + xd*tempb1;
    tempb2 = 0.5*1.1283791671*0.70710678118654746*(*cdf_n_dd0b);
    *xdb = *xdb + temp0d*tempb1 + temp*0.70710678118654746*0.5*1.1283791671*(*
        cdf_n_db) + tempd0*tempb2;
    *xdd1b = *xdd1b + temp0*tempb1 + temp*tempb2;
    popReal8(&temp0);
    popReal8(&temp0d);
    tempb = tempb + xd*0.70710678118654746*0.5*1.1283791671*(*cdf_n_db) + xdd1
        *tempb2;
    *cdf_n_db = 0.0;
    *cdf_n_dd0b = 0.0;
    tempd0b = tempd0b + xd*tempb2;
    tempb2 = 0.5*1.1283791671*0.70710678118654746*(*cdf_n_ddb);
    *xdd0b = arg1dd0*tempb4 + arg1d*temp3b + temp*tempb2;
    *cdf_n_ddb = 0.0;
    *xdb = *xdb + tempd*tempb2;
    tempdb = tempdb + xd*tempb2;
    tempb = tempb + xdd0*tempb2;
    tempb2 = 1.1283791671*0.70710678118654746*0.5*(*cdf_n_dddb);
    *xdd0db = arg1d*tempb4 + temp*tempb2;
    *cdf_n_dddb = 0.0;
    tempdb = tempdb + xdd1*tempb2;
    *xdd1b = *xdd1b + tempd*tempb2;
    *xdb = *xdb + tempdd*tempb2;
    tempddb = tempddb + xd*tempb2;
    arg1d0db = xd*arg1d*tempb0 + temp1*tempddb;
    *xdd0b = *xdd0b + tempd0*tempb2;
    tempd0b = tempd0b + xdd0*tempb2;
    tempb = tempb + xdd0d*tempb2;
    temp1b = arg1d0*tempdb + arg1d0d*tempddb;
    arg1b = arg1b + exp(arg1)*temp0b + exp(arg1)*arg1d1*temp0db + exp(arg1)*
        tempb + exp(arg1)*arg1d1*tempd0b + exp(arg1)*arg1d0*arg1d1*tempddb + 
        exp(arg1)*temp1b;
    tempb2 = exp(arg1)*tempddb;
    arg1d1b = temp2*tempb3 + exp(arg1)*temp0db + exp(arg1)*tempd0b + arg1d0*
        tempb2;
    arg1d0b = temp4*tempb0 + xd*arg1d*temp2b + temp1*tempdb + arg1d1*tempb2;
    popReal8(&temp1);
    tempb2 = -(0.70710678118654746*0.70710678118654746*2*arg1d0db);
    *xb = xd1d*tempb2 - 2*x*(0.70710678118654746*0.70710678118654746)*arg1b - 
        xd2*(0.70710678118654746*0.70710678118654746)*2*arg1d1b - xd1*(
        0.70710678118654746*0.70710678118654746)*2*arg1d0b;
    *xd2b = xd1*tempb2 - x*(0.70710678118654746*0.70710678118654746)*2*arg1d1b
    ;
    *xd1b = xd2*tempb2 - x*(0.70710678118654746*0.70710678118654746)*2*arg1d0b
    ;
    *xd1db = x*tempb2;
    tempb2 = -(0.70710678118654746*0.70710678118654746*2*arg1dd0b);
    *xb = *xb + xd0d0*tempb2 - xd0*(0.70710678118654746*0.70710678118654746)*2
        *arg1db;
    *xd0b = xd2*tempb2 - x*(0.70710678118654746*0.70710678118654746)*2*arg1db;
    *xd2b = *xd2b + xd0*tempb2;
    *xd0d0b = x*tempb2;
    tempb2 = -(0.70710678118654746*0.70710678118654746*2*arg1ddb);
    *xd0b = *xd0b + xd1*tempb2;
    *xd1b = *xd1b + xd0*tempb2;
    *xb = *xb + xd0d*tempb2;
    *xd0db = x*tempb2;
    tempb2 = -(0.70710678118654746*0.70710678118654746*2*arg1dddb);
    *xd1b = *xd1b + xd0d0*tempb2;
    *xd0d0b = *xd0d0b + xd1*tempb2;
    *xd0b = *xd0b + xd1d*tempb2;
    *xd1db = *xd1db + xd0*tempb2;
    *xd0db = *xd0db + xd2*tempb2;
    *xd2b = *xd2b + xd0d*tempb2;
    *xb = *xb + xd0dd*tempb2;
    temp5 = -(0.70710678118654746*0.70710678118654746*(x*x));
    tempb0 = 0.5*1.1283791671*0.70710678118654746*(*cdf_ndddb);
    *xd0ddb = x*tempb2 + temp0*tempb0;
    tempb2 = 0.70710678118654746*0.5*1.1283791671*(*cdf_nd0db);
    temp1b = xd1*0.70710678118654746*0.5*1.1283791671*(*cdf_nd0b) + xd1d*
        tempb2;
    *cdf_nd0db = 0.0;
    arg11b = exp(arg11)*xd1*arg11d*tempb2 + exp(arg11)*temp1b;
    tempb1 = exp(arg11)*tempb2;
    *xd1b = *xd1b + temp1*0.70710678118654746*0.5*1.1283791671*(*cdf_nd0b) + 
        arg11d*tempb1;
    *cdf_nd0b = 0.0;
    *xd1db = *xd1db + temp1*tempb2;
    arg11db = xd1*tempb1;
    popReal8(&temp1);
    tempb2 = 0.5*1.1283791671*0.70710678118654746*(*cdf_ndd0b);
    temp0b = xd0*0.70710678118654746*0.5*1.1283791671*(*cdf_ndb) + xd0d0*
        tempb2;
    *xd0b = *xd0b + temp0*0.70710678118654746*0.5*1.1283791671*(*cdf_ndb) + 
        temp0d*tempb2;
    *cdf_ndb = 0.0;
    *cdf_ndd0b = 0.0;
    temp0db = xd0*tempb2 + xd0d*tempb0;
    *xd0d0b = *xd0d0b + temp0*tempb2;
    tempb2 = 0.5*1.1283791671*0.70710678118654746*(*cdf_nddb);
    *cdf_nddb = 0.0;
    temp1b = xd0*arg10d*tempb2 + (arg10d*xd0d0+xd0*arg10dd)*tempb0;
    *xd0b = *xd0b + temp1*arg10d*tempb2;
    arg10db = temp1*xd0*tempb2;
    temp0b = temp0b + xd0d*tempb2 + xd0dd*tempb0;
    *xd0db = *xd0db + temp0*tempb2 + temp0d*tempb0;
    *cdf_ndddb = 0.0;
    tempb1 = exp(arg10)*tempb0;
    arg10b = exp(arg10)*xd0*arg10d*arg10d0*tempb0 + exp(arg10)*temp1b + exp(
        arg10)*temp0b + exp(arg10)*arg10d0*temp0db;
    tempb2 = temp1*tempb0;
    arg10db = arg10db + xd0d0*tempb2 + xd0*arg10d0*tempb1;
    *xd0d0b = *xd0d0b + arg10d*tempb2;
    *xd0b = *xd0b + arg10dd*tempb2 + arg10d*arg10d0*tempb1;
    arg10ddb = xd0*tempb2;
    arg10d0b = xd0*arg10d*tempb1 + exp(arg10)*temp0db;
    tempb0 = -(0.70710678118654746*0.70710678118654746*2*arg10ddb);
    *xb = *xb + 0.70710678118654746*1.1283791671*exp(-(-(0.70710678118654746*x
        )*-(0.70710678118654746*x)))*0.5*(*cdf_nb) + xd1d*tempb0 - 2*x*pow(
        0.70710678118654746, 3)*exp(temp5)*xd2*1.1283791671*0.5*(*cdf_nd1b) - 
        2*x*(0.70710678118654746*0.70710678118654746)*arg11b - xd2*(
        0.70710678118654746*0.70710678118654746)*2*arg11db - 2*x*(
        0.70710678118654746*0.70710678118654746)*arg10b - xd2*(
        0.70710678118654746*0.70710678118654746)*2*arg10d0b - xd1*(
        0.70710678118654746*0.70710678118654746)*2*arg10db;
    *cdf_nb = 0.0;
    *xd2b = *xd2b + exp(temp5)*1.1283791671*0.70710678118654746*0.5*(*cdf_nd1b
        ) + xd1*tempb0 - x*(0.70710678118654746*0.70710678118654746)*2*arg11db
        - x*(0.70710678118654746*0.70710678118654746)*2*arg10d0b;
    *cdf_nd1b = 0.0;
    *xd1b = *xd1b + xd2*tempb0 - x*(0.70710678118654746*0.70710678118654746)*2
        *arg10db;
    *xd1db = *xd1db + x*tempb0;
}

/*
  Differentiation of cdf_n_d_d_d in forward (tangent) mode:
   variations   of useful results: *cdf_ndd *cdf_n_dd *cdf_nd
                *cdf_n_d *cdf_nd0 *cdf_n_d_d *cdf_n cdf_n_d_d_d
   with respect to varying inputs: *cdf_ndd xd0d *cdf_n_dd xddd
                xdd xd x *cdf_nd *cdf_n_d *cdf_nd0 *cdf_n_d_d
                *cdf_n xdd0 xd0 xd1
   Plus diff mem management of: cdf_ndd:in cdf_n_dd:in cdf_nd:in
                cdf_n_d:in cdf_nd0:in cdf_n_d_d:in cdf_n:in


  Differentiation of cdf_n_d_d in forward (tangent) mode:
   variations   of useful results: *cdf_nd *cdf_n_d cdf_n_d_d
                *cdf_n
   with respect to varying inputs: xdd xd x *cdf_nd *cdf_n_d *cdf_n
                xd0
   Plus diff mem management of: cdf_nd:in cdf_n_d:in cdf_n:in


  Differentiation of cdf_n_d in forward (tangent) mode:
   variations   of useful results: cdf_n_d *cdf_n
   with respect to varying inputs: xd x *cdf_n
   Plus diff mem management of: cdf_n:in


  Differentiation of cdf_n in forward (tangent) mode:
   variations   of useful results: cdf_n
   with respect to varying inputs: x
*/
double cdf_n_d_d_d_d_nodiff(double x, double xd2, double xd1, double xd1d, 
        double xd0, double xd0d0, double xd0d, double xd0dd, double xd, double
        xdd1, double xdd0, double xdd0d, double xdd, double xddd0, double xddd
        , double xdddd, double *cdf_n, double *cdf_nd1, double *cdf_nd0, 
        double *cdf_nd0d, double *cdf_nd, double *cdf_ndd0, double *cdf_ndd, 
        double *cdf_nddd, double *cdf_n_d, double *cdf_n_dd0, double *cdf_n_dd
        , double *cdf_n_ddd, double *cdf_n_d_d, double *cdf_n_d_dd, double *
        cdf_n_d_d_d) {
    double arg1;
    double arg1d1;
    double arg1d0;
    double arg1d0d;
    double arg1d;
    double arg1dd0;
    double arg1dd;
    double arg1ddd;
    double temp;
    double tempd0;
    double tempd;
    double tempdd;
    double arg10;
    double arg10d0;
    double arg10d;
    double arg10dd;
    double temp0;
    double temp0d;
    double arg11;
    double arg11d;
    double temp1;
    double temp2;
    double temp3;
    arg10dd = -(0.70710678118654746*0.70710678118654746*2*(xd1*xd2+x*xd1d));
    arg10d = -(0.70710678118654746*0.70710678118654746*2*x*xd1);
    arg10d0 = -(0.70710678118654746*0.70710678118654746*2*x*xd2);
    arg10 = -(-(0.70710678118654746*x)*-(0.70710678118654746*x));
    temp0d = exp(arg10)*arg10d0;
    temp0 = exp(arg10);
    temp1 = exp(arg10);
    *cdf_nddd = 0.70710678118654746*0.5*1.1283791671*(xd0*arg10d*exp(arg10)*
        arg10d0+temp1*(arg10d*xd0d0+xd0*arg10dd)+xd0d*temp0d+temp0*xd0dd);
    *cdf_ndd = 0.70710678118654746*0.5*1.1283791671*(temp1*(xd0*arg10d)+temp0*
        xd0d);
    *cdf_ndd0 = 0.70710678118654746*0.5*1.1283791671*(xd0*temp0d+temp0*xd0d0);
    *cdf_nd = 1.1283791671*0.70710678118654746*0.5*(temp0*xd0);
    arg11d = -(0.70710678118654746*0.70710678118654746*2*x*xd2);
    arg11 = -(-(0.70710678118654746*x)*-(0.70710678118654746*x));
    temp1 = exp(arg11);
    *cdf_nd0d = 1.1283791671*0.70710678118654746*0.5*(xd1*exp(arg11)*arg11d+
        temp1*xd1d);
    *cdf_nd0 = 1.1283791671*0.70710678118654746*0.5*(temp1*xd1);
    *cdf_nd1 = 0.5*1.1283791671*exp(-(-(0.70710678118654746*x)*-(
        0.70710678118654746*x)))*0.70710678118654746*xd2;
    *cdf_n = 0.5*erfc(x*-0.70710678118654746);
    arg1ddd = -(0.70710678118654746*0.70710678118654746*2*(xd1*xd0d0+xd0*xd1d+
        xd0d*xd2+x*xd0dd));
    arg1dd = -(0.70710678118654746*0.70710678118654746*2*(xd0*xd1+x*xd0d));
    arg1dd0 = -(0.70710678118654746*0.70710678118654746*2*(xd0*xd2+x*xd0d0));
    arg1d = -(0.70710678118654746*0.70710678118654746*2*x*xd0);
    arg1d0d = -(0.70710678118654746*0.70710678118654746*2*(xd1*xd2+x*xd1d));
    arg1d0 = -(0.70710678118654746*0.70710678118654746*2*x*xd1);
    arg1d1 = -(0.70710678118654746*0.70710678118654746*2*x*xd2);
    arg1 = -(-(0.70710678118654746*x)*-(0.70710678118654746*x));
    temp1 = exp(arg1);
    tempdd = arg1d0*exp(arg1)*arg1d1 + temp1*arg1d0d;
    tempd = temp1*arg1d0;
    tempd0 = exp(arg1)*arg1d1;
    temp = exp(arg1);
    *cdf_n_ddd = 0.5*1.1283791671*0.70710678118654746*(tempd*xdd1+xd*tempdd+
        xdd0*tempd0+temp*xdd0d);
    *cdf_n_dd = 0.70710678118654746*0.5*1.1283791671*(xd*tempd+temp*xdd0);
    *cdf_n_dd0 = 0.70710678118654746*0.5*1.1283791671*(xd*tempd0+temp*xdd1);
    *cdf_n_d = 1.1283791671*0.70710678118654746*0.5*(temp*xd);
    temp0d = exp(arg1)*arg1d1;
    temp0 = exp(arg1);
    *cdf_n_d_dd = 0.5*1.1283791671*0.70710678118654746*(arg1d*(xd*temp0d+temp0
        *xdd1)+temp0*xd*arg1dd0+xdd*tempd0+temp*xddd0);
    *cdf_n_d_d = 0.70710678118654746*0.5*1.1283791671*(temp0*(xd*arg1d)+temp*
        xdd);
    temp1 = exp(arg1);
    temp2 = xd*arg1d*arg1d0;
    temp3 = arg1d*xdd0 + xd*arg1dd;
    *cdf_n_d_d_d = 0.5*1.1283791671*0.70710678118654746*(temp2*temp1+temp0*
        temp3+xdd*tempd+temp*xddd);
    return 0.5*1.1283791671*0.70710678118654746*(temp1*(arg1d0*(arg1d*xdd1+xd*
    arg1dd0)+xd*arg1d*arg1d0d)+temp2*exp(arg1)*arg1d1+temp3*temp0d+temp0*(xdd0
    *arg1dd0+arg1d*xdd0d+arg1dd*xdd1+xd*arg1ddd)+tempd*xddd0+xdd*tempdd+xddd*
    tempd0+temp*xdddd);
}

/*
  Differentiation of call_price_d_d_d_d in reverse (adjoint) mode:
   gradient     of useful results: Sdd0 Sdd1 Kd0dd Td vd0dd *call_price_d_dd
                Sd0 Tddd0 Sd1 Kd0d Sd2 v Sd0d0 Kddd0 Kd0 *call_priced0d
                Tdd Kd1 Kddd Kd Kd2 vddd0 vd0d *call_price_dd
                Sdd0d Td0d *call_price_ddd *call_priceddd vddd
                Td0d0 *call_price_d Sd0d Sdddd *call_priced0 Tddd
                Kd1d *call_priced1 vd0 vd1 vd2 Kd0d0 *call_price
                Tdd0d Sddd vd0d0 vd1d vd Td1d Kdd0d Sdd Tdddd
                vdd0d *call_price_d_d_d *call_priced Sd0dd Td0
                Sd1d Td1 Kdd0 Sd Td2 Kdd1 Kdddd Kdd K call_price_d_d_d_d
                *call_price_d_d vdddd *call_price_dd0 S *call_pricedd0
                T vdd0 vdd1 Sddd0 Tdd0 Td0dd Tdd1 *call_pricedd
                vdd
   with respect to varying inputs: Sdd0 Sdd1 Kd0dd Td vd0dd *call_price_d_dd
                Sd0 Tddd0 Sd1 Kd0d Sd2 v Sd0d0 Kddd0 Kd0 *call_priced0d
                Tdd Kd1 Kddd Kd Kd2 vddd0 vd0d *call_price_dd
                Sdd0d Td0d *call_price_ddd *call_priceddd vddd
                Td0d0 *call_price_d Sd0d Sdddd *call_priced0 Tddd
                Kd1d *call_priced1 vd0 vd1 vd2 Kd0d0 *call_price
                Tdd0d Sddd vd0d0 vd1d vd Td1d Kdd0d Sdd Tdddd
                vdd0d *call_price_d_d_d *call_priced Sd0dd Td0
                Sd1d Td1 Kdd0 Sd Td2 Kdd1 Kdddd Kdd K *call_price_d_d
                vdddd *call_price_dd0 S *call_pricedd0 T vdd0
                vdd1 Sddd0 Tdd0 Td0dd Tdd1 *call_pricedd vdd
   RW status of diff variables: Sdd0:incr Sdd1:incr Kd0dd:incr
                Td:incr vd0dd:incr call_price_d_dd:(loc) *call_price_d_dd:in-out
                Sd0:incr Tddd0:incr Sd1:incr Kd0d:incr Sd2:incr
                v:incr Sd0d0:incr Kddd0:incr Kd0:incr call_priced0d:(loc)
                *call_priced0d:in-out Tdd:incr Kd1:incr Kddd:incr
                Kd:incr Kd2:incr vddd0:incr vd0d:incr call_price_dd:(loc)
                *call_price_dd:in-out Sdd0d:incr Td0d:incr call_price_ddd:(loc)
                *call_price_ddd:in-out call_priceddd:(loc) *call_priceddd:in-out
                vddd:incr Td0d0:incr call_price_d:(loc) *call_price_d:in-out
                Sd0d:incr Sdddd:incr call_priced0:(loc) *call_priced0:in-out
                Tddd:incr Kd1d:incr call_priced1:(loc) *call_priced1:in-out
                vd0:incr vd1:incr vd2:incr Kd0d0:incr call_price:(loc)
                *call_price:in-out Tdd0d:incr Sddd:incr vd0d0:incr
                vd1d:incr vd:incr Td1d:incr Kdd0d:incr Sdd:incr
                Tdddd:incr vdd0d:incr call_price_d_d_d:(loc) *call_price_d_d_d:in-out
                call_priced:(loc) *call_priced:in-out Sd0dd:incr
                Td0:incr Sd1d:incr Td1:incr Kdd0:incr Sd:incr
                Td2:incr Kdd1:incr Kdddd:incr Kdd:incr K:incr
                call_price_d_d_d_d:in-killed call_price_d_d:(loc)
                *call_price_d_d:in-out vdddd:incr call_price_dd0:(loc)
                *call_price_dd0:in-out S:incr call_pricedd0:(loc)
                *call_pricedd0:in-out T:incr vdd0:incr vdd1:incr
                Sddd0:incr Tdd0:incr Td0dd:incr Tdd1:incr call_pricedd:(loc)
                *call_pricedd:in-out vdd:incr
   Plus diff mem management of: call_price_d_dd:in call_priced0d:in
                call_price_dd:in call_price_ddd:in call_priceddd:in
                call_price_d:in call_priced0:in call_priced1:in
                call_price:in call_price_d_d_d:in call_priced:in
                call_price_d_d:in call_price_dd0:in call_pricedd0:in
                call_pricedd:in


  Differentiation of call_price_d_d_d in forward (tangent) mode:
   variations   of useful results: *call_price_dd *call_price_d
                *call_priced0 *call_price call_price_d_d_d *call_priced
                *call_price_d_d *call_pricedd
   with respect to varying inputs: Sdd0 Td Sd0 Sd1 Kd0d v Kd0
                Tdd Kd1 Kddd Kd vd0d *call_price_dd Td0d vddd
                *call_price_d Sd0d *call_priced0 Tddd vd0 vd1
                *call_price Sddd vd Sdd *call_priced Td0 Td1 Kdd0
                Sd Kdd K *call_price_d_d S T vdd0 Tdd0 *call_pricedd
                vdd
   RW status of diff variables: Sdd0:in Td:in Sd0:in Sd1:in Kd0d:in
                v:in Kd0:in Tdd:in Kd1:in Kddd:in Kd:in vd0d:in
                call_price_dd:(loc) *call_price_dd:in-out Td0d:in
                vddd:in call_price_d:(loc) *call_price_d:in-out
                Sd0d:in call_priced0:(loc) *call_priced0:in-out
                Tddd:in vd0:in vd1:in call_price:(loc) *call_price:in-out
                Sddd:in vd:in Sdd:in call_price_d_d_d:out call_priced:(loc)
                *call_priced:in-out Td0:in Td1:in Kdd0:in Sd:in
                Kdd:in K:in call_price_d_d:(loc) *call_price_d_d:in-out
                S:in T:in vdd0:in Tdd0:in call_pricedd:(loc) *call_pricedd:in-out
                vdd:in
   Plus diff mem management of: call_price_dd:in call_price_d:in
                call_priced0:in call_price:in call_priced:in call_price_d_d:in
                call_pricedd:in


  Differentiation of call_price_d_d in forward (tangent) mode:
   variations   of useful results: *call_price_d *call_price *call_priced
                call_price_d_d
   with respect to varying inputs: Td Sd0 v Kd0 Tdd Kd *call_price_d
                vd0 *call_price vd Sdd *call_priced Td0 Sd Kdd
                K S T vdd
   RW status of diff variables: Td:in Sd0:in v:in Kd0:in Tdd:in
                Kd:in call_price_d:(loc) *call_price_d:in-out
                vd0:in call_price:(loc) *call_price:in-out vd:in
                Sdd:in call_priced:(loc) *call_priced:in-out Td0:in
                Sd:in Kdd:in K:in call_price_d_d:out S:in T:in
                vdd:in
   Plus diff mem management of: call_price_d:in call_price:in
                call_priced:in


  Differentiation of call_price_d in forward (tangent) mode:
   variations   of useful results: call_price_d *call_price
   with respect to varying inputs: Td v Kd *call_price vd Sd K
                S T
   RW status of diff variables: Td:in v:in Kd:in call_price_d:out
                call_price:(loc) *call_price:in-out vd:in Sd:in
                K:in S:in T:in
   Plus diff mem management of: call_price:in


  Differentiation of call_price in forward (tangent) mode:
   variations   of useful results: call_price
   with respect to varying inputs: v K S T
   RW status of diff variables: v:in call_price:out K:in S:in
                T:in
*/
void call_price_d_d_d_d_b(double S, double *Sb, double Sd2, double *Sd2b, 
        double Sd1, double *Sd1b, double Sd1d, double *Sd1db, double Sd0, 
        double *Sd0b, double Sd0d0, double *Sd0d0b, double Sd0d, double *Sd0db
        , double Sd0dd, double *Sd0ddb, double Sd, double *Sdb, double Sdd1, 
        double *Sdd1b, double Sdd0, double *Sdd0b, double Sdd0d, double *
        Sdd0db, double Sdd, double *Sddb, double Sddd0, double *Sddd0b, double
        Sddd, double *Sdddb, double Sdddd, double *Sddddb, double K, double *
        Kb, double Kd2, double *Kd2b, double Kd1, double *Kd1b, double Kd1d, 
        double *Kd1db, double Kd0, double *Kd0b, double Kd0d0, double *Kd0d0b,
        double Kd0d, double *Kd0db, double Kd0dd, double *Kd0ddb, double Kd, 
        double *Kdb, double Kdd1, double *Kdd1b, double Kdd0, double *Kdd0b, 
        double Kdd0d, double *Kdd0db, double Kdd, double *Kddb, double Kddd0, 
        double *Kddd0b, double Kddd, double *Kdddb, double Kdddd, double *
        Kddddb, double v, double *vb, double vd2, double *vd2b, double vd1, 
        double *vd1b, double vd1d, double *vd1db, double vd0, double *vd0b, 
        double vd0d0, double *vd0d0b, double vd0d, double *vd0db, double vd0dd
        , double *vd0ddb, double vd, double *vdb, double vdd1, double *vdd1b, 
        double vdd0, double *vdd0b, double vdd0d, double *vdd0db, double vdd, 
        double *vddb, double vddd0, double *vddd0b, double vddd, double *vdddb
        , double vdddd, double *vddddb, double T, double *Tb, double Td2, 
        double *Td2b, double Td1, double *Td1b, double Td1d, double *Td1db, 
        double Td0, double *Td0b, double Td0d0, double *Td0d0b, double Td0d, 
        double *Td0db, double Td0dd, double *Td0ddb, double Td, double *Tdb, 
        double Tdd1, double *Tdd1b, double Tdd0, double *Tdd0b, double Tdd0d, 
        double *Tdd0db, double Tdd, double *Tddb, double Tddd0, double *Tddd0b
        , double Tddd, double *Tdddb, double Tdddd, double *Tddddb, double *
        call_price, double *call_priceb, double *call_priced1, double *
        call_priced1b, double *call_priced0, double *call_priced0b, double *
        call_priced0d, double *call_priced0db, double *call_priced, double *
        call_pricedb, double *call_pricedd0, double *call_pricedd0b, double *
        call_pricedd, double *call_priceddb, double *call_priceddd, double *
        call_pricedddb, double *call_price_d, double *call_price_db, double *
        call_price_dd0, double *call_price_dd0b, double *call_price_dd, double
        *call_price_ddb, double *call_price_ddd, double *call_price_dddb, 
        double *call_price_d_d, double *call_price_d_db, double *
        call_price_d_dd, double *call_price_d_ddb, double *call_price_d_d_d, 
        double *call_price_d_d_db, double call_price_d_d_d_db) {
    double totalvol;
    double totalvolb;
    double totalvold2;
    double totalvold2b;
    double totalvold1;
    double totalvold1b;
    double totalvold1d;
    double totalvold1db;
    double totalvold0;
    double totalvold0b;
    double totalvold0d0;
    double totalvold0d0b;
    double totalvold0d;
    double totalvold0db;
    double totalvold0dd;
    double totalvold0ddb;
    double totalvold;
    double totalvoldb;
    double totalvoldd1;
    double totalvoldd1b;
    double totalvoldd0;
    double totalvoldd0b;
    double totalvoldd0d;
    double totalvoldd0db;
    double totalvoldd;
    double totalvolddb;
    double totalvolddd0;
    double totalvolddd0b;
    double totalvolddd;
    double totalvoldddb;
    double totalvoldddd;
    double totalvolddddb;
    double result1;
    double result1b;
    double result1d2;
    double result1d2b;
    double result1d1;
    double result1d1b;
    double result1d1d;
    double result1d1db;
    double result1d0;
    double result1d0b;
    double result1d0d0;
    double result1d0d0b;
    double result1d0d;
    double result1d0db;
    double result1d0dd;
    double result1d0ddb;
    double result1d;
    double result1db;
    double result1dd1;
    double result1dd1b;
    double result1dd0;
    double result1dd0b;
    double result1dd0d;
    double result1dd0db;
    double result1dd;
    double result1ddb;
    double result1ddd0;
    double result1ddd0b;
    double result1ddd;
    double result1dddb;
    double result1dddd;
    double result1ddddb;
    double result2;
    double result2b;
    double result2d2;
    double result2d2b;
    double result2d1;
    double result2d1b;
    double result2d1d;
    double result2d1db;
    double result2d0;
    double result2d0b;
    double result2d0d0;
    double result2d0d0b;
    double result2d0d;
    double result2d0db;
    double result2d0dd;
    double result2d0ddb;
    double result2d;
    double result2db;
    double result2dd1;
    double result2dd1b;
    double result2dd0;
    double result2dd0b;
    double result2dd0d;
    double result2dd0db;
    double result2dd;
    double result2ddb;
    double result2ddd0;
    double result2ddd0b;
    double result2ddd;
    double result2dddb;
    double result2dddd;
    double result2ddddb;
    double temp;
    double tempb;
    double tempd1;
    double tempd1b;
    double tempd0;
    double tempd0b;
    double tempd0d;
    double tempd0db;
    double tempd;
    double tempdb;
    double tempdd0;
    double tempdd0b;
    double tempdd;
    double tempddb;
    double tempddd;
    double tempdddb;
    double temp0;
    double temp0b;
    double temp0d1;
    double temp0d1b;
    double temp0d0;
    double temp0d0b;
    double temp0d0d;
    double temp0d0db;
    double temp0d;
    double temp0db;
    double temp0dd0;
    double temp0dd0b;
    double temp0dd;
    double temp0ddb;
    double temp0ddd;
    double temp0dddb;
    double temp1;
    double temp1b;
    double temp1d0;
    double temp1d0b;
    double temp1d;
    double temp1db;
    double temp1dd;
    double temp1ddb;
    double temp2;
    double temp2b;
    double temp2d0;
    double temp2d0b;
    double temp2d;
    double temp2db;
    double temp2dd;
    double temp2ddb;
    double temp3;
    double temp3b;
    double temp3d;
    double temp3db;
    double temp4;
    double temp4b;
    double temp4d;
    double temp4db;
    double temp5;
    double temp5b;
    double temp5d;
    double temp5db;
    double temp6;
    double temp6b;
    double temp7;
    double temp7b;
    double temp8;
    double temp8b;
    double temp9;
    double temp9b;
    double temp10;
    double tempb0;
    double temp11;
    double tempb1;
    double temp12;
    double tempb2;
    double tempb3;
    double temp13;
    double tempb4;
    double tempb5;
    temp6 = sqrt(T);
    temp3d = (T == 0.0 ? 0.0 : Td2/(2.0*temp6));
    temp3 = temp6;
    temp6 = Td1/(2.0*temp3);
    temp1dd = (T == 0.0 ? 0.0 : (Td1d-temp6*2.0*temp3d)/(2.0*temp3));
    temp1d = (T == 0.0 ? 0.0 : temp6);
    temp1d0 = temp3d;
    temp1 = temp3;
    temp6 = Td0/(2.0*temp1);
    temp3d = (Td0d0-temp6*2.0*temp1d0)/(2.0*temp1);
    pushReal8(temp3);
    temp3 = temp6;
    temp6 = (Td0d-2.0*temp3*temp1d)/(2.0*temp1);
    tempddd = (T == 0.0 ? 0.0 : (Td0dd-2.0*(temp1d*temp3d+temp3*temp1dd)-temp6
        *2.0*temp1d0)/(2.0*temp1));
    tempdd = (T == 0.0 ? 0.0 : temp6);
    tempdd0 = (T == 0.0 ? 0.0 : temp3d);
    tempd = (T == 0.0 ? 0.0 : temp3);
    tempd0d = temp1dd;
    tempd0 = temp1d;
    tempd1 = temp1d0;
    temp = temp1;
    temp6 = Td/(2.0*temp);
    temp3d = (Tdd1-temp6*2.0*tempd1)/(2.0*temp);
    pushReal8(temp3);
    temp3 = temp6;
    temp6 = (Tdd0-2.0*temp3*tempd0)/(2.0*temp);
    temp1dd = (Tdd0d-2.0*(tempd0*temp3d+temp3*tempd0d)-temp6*2.0*tempd1)/(2.0*
        temp);
    pushReal8(temp1d);
    temp1d = temp6;
    pushReal8(temp1d0);
    temp1d0 = temp3d;
    pushReal8(temp1);
    temp1 = temp3;
    temp6 = (Tdd-2.0*temp1*tempd)/(2.0*temp);
    pushReal8(temp3d);
    temp3d = (Tddd0-2.0*(tempd*temp1d0+temp1*tempdd0)-temp6*2.0*tempd1)/(2.0*
        temp);
    pushReal8(temp3);
    temp3 = temp6;
    temp6 = (Tddd-2.0*(tempd*temp1d+temp1*tempdd)-2.0*temp3*tempd0)/(2.0*temp)
    ;
    result1dddd = (T == 0.0 ? 0.0 : (Tdddd-2.0*(temp1d*tempdd0+tempd*temp1dd+
        tempdd*temp1d0+temp1*tempddd)-2.0*(tempd0*temp3d+temp3*tempd0d)-temp6*
        2.0*tempd1)/(2.0*temp));
    result1ddd = (T == 0.0 ? 0.0 : temp6);
    result1ddd0 = (T == 0.0 ? 0.0 : temp3d);
    result1dd = (T == 0.0 ? 0.0 : temp3);
    result1dd0d = (T == 0.0 ? 0.0 : temp1dd);
    result1dd0 = (T == 0.0 ? 0.0 : temp1d);
    result1dd1 = (T == 0.0 ? 0.0 : temp1d0);
    result1d = (T == 0.0 ? 0.0 : temp1);
    result1d0dd = tempddd;
    result1d0d = tempdd;
    result1d0d0 = tempdd0;
    result1d0 = tempd;
    result1d1d = tempd0d;
    result1d1 = tempd0;
    result1d2 = tempd1;
    result1 = temp;
    totalvoldddd = vdd0*result1d0d0 + result1d0*vdd0d + result1d0d*vdd1 + vd*
        result1d0dd + result1d1*vddd0 + vdd*result1d1d + vddd*result1d2 + 
        result1*vdddd + result1dd0*vd0d0 + vd0*result1dd0d + vd0d*result1dd1 +
        result1d*vd0dd + vd1*result1ddd0 + result1dd*vd1d + result1ddd*vd2 + v
        *result1dddd;
    totalvolddd = result1d0*vdd0 + vd*result1d0d + vdd*result1d1 + result1*
        vddd + vd0*result1dd0 + result1d*vd0d + result1dd*vd1 + v*result1ddd;
    totalvolddd0 = result1d0*vdd1 + vd*result1d0d0 + vdd*result1d2 + result1*
        vddd0 + vd0*result1dd1 + result1d*vd0d0 + result1dd*vd2 + v*
        result1ddd0;
    totalvoldd = vd*result1d0 + result1*vdd + result1d*vd0 + v*result1dd;
    totalvoldd0d = result1d1*vdd1 + vd*result1d1d + vdd0*result1d2 + result1*
        vdd0d + vd1*result1dd1 + result1d*vd1d + result1dd0*vd2 + v*
        result1dd0d;
    totalvoldd0 = vd*result1d1 + result1*vdd0 + result1d*vd1 + v*result1dd0;
    totalvoldd1 = vd*result1d2 + result1*vdd1 + result1d*vd2 + v*result1dd1;
    totalvold = result1*vd + v*result1d;
    totalvold0dd = result1d1*vd0d0 + vd0*result1d1d + vd0d*result1d2 + result1
        *vd0dd + vd1*result1d0d0 + result1d0*vd1d + result1d0d*vd2 + v*
        result1d0dd;
    totalvold0d = vd0*result1d1 + result1*vd0d + result1d0*vd1 + v*result1d0d;
    totalvold0d0 = vd0*result1d2 + result1*vd0d0 + result1d0*vd2 + v*
        result1d0d0;
    totalvold0 = result1*vd0 + v*result1d0;
    totalvold1d = vd1*result1d2 + result1*vd1d + result1d1*vd2 + v*result1d1d;
    totalvold1 = result1*vd1 + v*result1d1;
    totalvold2 = result1*vd2 + v*result1d2;
    totalvol = v*result1;
    temp6 = S*Kd0/K;
    temp3d = (Kd0*Sd2+S*Kd0d0-temp6*Kd2)/K;
    pushReal8(temp3);
    temp3 = temp6;
    temp6 = (Sd0-temp3)/K;
    temp4d = (Sd0d0-temp3d-temp6*Kd2)/K;
    temp4 = temp6;
    temp6 = (Kd0*Sd1+S*Kd0d-temp3*Kd1)/K;
    temp7 = (Sd0d-temp6-temp4*Kd1)/K;
    tempddd = (Sd0dd-(Sd1*Kd0d0+Kd0*Sd1d+Kd0d*Sd2+S*Kd0dd-Kd1*temp3d-temp3*
        Kd1d-temp6*Kd2)/K-Kd1*temp4d-temp4*Kd1d-temp7*Kd2)/K;
    pushReal8(tempdd);
    tempdd = temp7;
    pushReal8(tempdd0);
    tempdd0 = temp4d;
    pushReal8(tempd);
    tempd = temp4;
    temp7 = S*Kd1/K;
    temp6 = (Sd1-temp7)/K;
    pushReal8(tempd0d);
    tempd0d = (Sd1d-(Kd1*Sd2+S*Kd1d-temp7*Kd2)/K-temp6*Kd2)/K;
    pushReal8(tempd0);
    tempd0 = temp6;
    pushReal8(tempd1);
    tempd1 = (Sd2-S*Kd2/K)/K;
    pushReal8(temp);
    temp = S/K;
    temp7 = log(temp)/totalvol;
    pushReal8(temp4d);
    temp4d = (tempd1/temp-temp7*totalvold2)/totalvol;
    pushReal8(temp4);
    temp4 = temp7;
    pushReal8(temp7);
    temp7 = (tempd0/temp-temp4*totalvold1)/totalvol;
    temp1dd = ((tempd0d-tempd0*tempd1/temp)/temp-totalvold1*temp4d-temp4*
        totalvold1d-temp7*totalvold2)/totalvol;
    pushReal8(temp1d);
    temp1d = temp7;
    pushReal8(temp1d0);
    temp1d0 = temp4d;
    pushReal8(temp1);
    temp1 = temp4;
    temp7 = (tempd/temp-temp1*totalvold0)/totalvol;
    pushReal8(temp4d);
    temp4d = ((tempdd0-tempd*tempd1/temp)/temp-totalvold0*temp1d0-temp1*
        totalvold0d0-temp7*totalvold2)/totalvol;
    pushReal8(temp4);
    temp4 = temp7;
    temp7 = tempd*tempd0/temp;
    pushReal8(temp6);
    temp6 = (tempdd-temp7)/temp;
    temp8 = (temp6-totalvold0*temp1d-temp1*totalvold0d-temp4*totalvold1)/
        totalvol;
    temp0ddd = ((tempddd-(tempd0*tempdd0+tempd*tempd0d-temp7*tempd1)/temp-
        temp6*tempd1)/temp-temp1d*totalvold0d0-totalvold0*temp1dd-totalvold0d*
        temp1d0-temp1*totalvold0dd-totalvold1*temp4d-temp4*totalvold1d-temp8*
        totalvold2)/totalvol;
    temp0dd = temp8;
    temp0dd0 = temp4d;
    temp0d = temp4;
    temp0d0d = temp1dd;
    temp0d0 = temp1d;
    temp0d1 = temp1d0;
    temp0 = temp1;
    double d1 = temp0 + 0.5*totalvol;
    double d1b = 0.0;
    double d1d2 = temp0d1 + 0.5*totalvold2;
    double d1d2b = 0.0;
    double d1d1 = temp0d0 + 0.5*totalvold1;
    double d1d1b = 0.0;
    double d1d1d = temp0d0d + 0.5*totalvold1d;
    double d1d1db = 0.0;
    double d1d0 = temp0d + 0.5*totalvold0;
    double d1d0b = 0.0;
    double d1d0d0 = temp0dd0 + 0.5*totalvold0d0;
    double d1d0d0b = 0.0;
    double d1d0d = temp0dd + 0.5*totalvold0d;
    double d1d0db = 0.0;
    double d1d0dd = temp0ddd + 0.5*totalvold0dd;
    double d1d0ddb = 0.0;
    temp8 = (Sd-temp*Kd)/(temp*K);
    pushReal8(temp4d);
    temp4d = (Sdd1-Kd*tempd1-temp*Kdd1-temp8*(K*tempd1+temp*Kd2))/(temp*K);
    pushReal8(temp4);
    temp4 = temp8;
    temp8 = K*tempd0 + temp*Kd1;
    temp7 = (Sdd0-Kd*tempd0-temp*Kdd0-temp4*temp8)/(temp*K);
    pushReal8(temp1dd);
    temp1dd = (Sdd0d-tempd0*Kdd1-Kd*tempd0d-Kdd0*tempd1-temp*Kdd0d-temp8*
        temp4d-temp4*(tempd0*Kd2+K*tempd0d+Kd1*tempd1+temp*Kd1d)-temp7*(K*
        tempd1+temp*Kd2))/(temp*K);
    pushReal8(temp1d);
    temp1d = temp7;
    pushReal8(temp1d0);
    temp1d0 = temp4d;
    pushReal8(temp1);
    temp1 = temp4;
    temp8 = (temp1-temp0*totalvold)/totalvol;
    pushReal8(temp4d);
    temp4d = (temp1d0-totalvold*temp0d1-temp0*totalvoldd1-temp8*totalvold2)/
        totalvol;
    pushReal8(temp4);
    temp4 = temp8;
    temp8 = (temp1d-totalvold*temp0d0-temp0*totalvoldd0-temp4*totalvold1)/
        totalvol;
    temp2dd = (temp1dd-temp0d0*totalvoldd1-totalvold*temp0d0d-totalvoldd0*
        temp0d1-temp0*totalvoldd0d-totalvold1*temp4d-temp4*totalvold1d-temp8*
        totalvold2)/totalvol;
    temp2d = temp8;
    temp2d0 = temp4d;
    temp2 = temp4;
    double d1d = temp2 + 0.5*totalvold;
    double d1db = 0.0;
    double d1dd1 = temp2d0 + 0.5*totalvoldd1;
    double d1dd1b = 0.0;
    double d1dd0 = temp2d + 0.5*totalvoldd0;
    double d1dd0b = 0.0;
    double d1dd0d = temp2dd + 0.5*totalvoldd0d;
    double d1dd0db = 0.0;
    pushReal8(temp4d);
    temp4d = tempd*Kd2 + K*tempdd0 + Kd0*tempd1 + temp*Kd0d0;
    pushReal8(temp4);
    temp4 = K*tempd + temp*Kd0;
    pushReal8(temp8);
    temp8 = (Sdd-Kd*tempd-temp*Kdd-temp1*temp4)/(temp*K);
    pushReal8(temp3d);
    temp3d = (Sddd0-tempd*Kdd1-Kd*tempdd0-Kdd*tempd1-temp*Kddd0-temp4*temp1d0-
        temp1*temp4d-temp8*(K*tempd1+temp*Kd2))/(temp*K);
    pushReal8(temp3);
    temp3 = temp8;
    temp8 = (temp3-totalvold*temp0d-temp0*totalvoldd-temp2*totalvold0)/
        totalvol;
    temp5d = (temp3d-temp0d*totalvoldd1-totalvold*temp0dd0-totalvoldd*temp0d1-
        temp0*totalvolddd0-totalvold0*temp2d0-temp2*totalvold0d0-temp8*
        totalvold2)/totalvol;
    temp5 = temp8;
    double d1dd = temp5 + 0.5*totalvoldd;
    double d1ddb = 0.0;
    double d1ddd0 = temp5d + 0.5*totalvolddd0;
    double d1ddd0b = 0.0;
    temp8 = tempd*Kd1 + K*tempdd + Kd0*tempd0 + temp*Kd0d;
    pushReal8(temp7);
    temp7 = K*tempd0 + temp*Kd1;
    temp6 = (Sddd-tempd*Kdd0-Kd*tempdd-Kdd*tempd0-temp*Kddd-temp4*temp1d-temp1
        *temp8-temp3*temp7)/(temp*K);
    temp9 = (temp6-temp0d*totalvoldd0-totalvold*temp0dd-totalvoldd*temp0d0-
        temp0*totalvolddd-totalvold0*temp2d-temp2*totalvold0d-temp5*totalvold1
        )/totalvol;
    double d1ddd = temp9 + 0.5*totalvolddd;
    double d1dddb = 0.0;
    double d1dddd = ((Sdddd-Kdd0*tempdd0-tempd*Kdd0d-tempdd*Kdd1-Kd*tempddd-
    tempd0*Kddd0-Kdd*tempd0d-Kddd*tempd1-temp*Kdddd-temp1d*temp4d-temp4*
    temp1dd-temp8*temp1d0-temp1*(Kd1*tempdd0+tempd*Kd1d+tempdd*Kd2+K*tempddd+
    tempd0*Kd0d0+Kd0*tempd0d+Kd0d*tempd1+temp*Kd0dd)-temp7*temp3d-temp3*(
    tempd0*Kd2+K*tempd0d+Kd1*tempd1+temp*Kd1d)-temp6*(K*tempd1+temp*Kd2))/(
    temp*K)-totalvoldd0*temp0dd0-temp0d*totalvoldd0d-temp0dd*totalvoldd1-
    totalvold*temp0ddd-temp0d0*totalvolddd0-totalvoldd*temp0d0d-totalvolddd*
    temp0d1-temp0*totalvoldddd-temp2d*totalvold0d0-totalvold0*temp2dd-
    totalvold0d*temp2d0-temp2*totalvold0dd-totalvold1*temp5d-temp5*totalvold1d
    -temp9*totalvold2)/totalvol + 0.5*totalvoldddd;
    double d1ddddb = 0.0;
    double d2 = d1 - totalvol;
    double d2b = 0.0;
    double d2d2 = d1d2 - totalvold2;
    double d2d2b = 0.0;
    double d2d1 = d1d1 - totalvold1;
    double d2d1b = 0.0;
    double d2d1d = d1d1d - totalvold1d;
    double d2d1db = 0.0;
    double d2d0 = d1d0 - totalvold0;
    double d2d0b = 0.0;
    double d2d0d0 = d1d0d0 - totalvold0d0;
    double d2d0d0b = 0.0;
    double d2d0d = d1d0d - totalvold0d;
    double d2d0db = 0.0;
    double d2d0dd = d1d0dd - totalvold0dd;
    double d2d0ddb = 0.0;
    double d2d = d1d - totalvold;
    double d2db = 0.0;
    double d2dd1 = d1dd1 - totalvoldd1;
    double d2dd1b = 0.0;
    double d2dd0 = d1dd0 - totalvoldd0;
    double d2dd0b = 0.0;
    double d2dd0d = d1dd0d - totalvoldd0d;
    double d2dd0db = 0.0;
    double d2dd = d1dd - totalvoldd;
    double d2ddb = 0.0;
    double d2ddd0 = d1ddd0 - totalvolddd0;
    double d2ddd0b = 0.0;
    double d2ddd = d1ddd - totalvolddd;
    double d2dddb = 0.0;
    double d2dddd = d1dddd - totalvoldddd;
    double d2ddddb = 0.0;
    pushReal8(result1dddd);
    pushReal8(result1ddd);
    pushReal8(result1ddd0);
    pushReal8(result1dd);
    pushReal8(result1dd0d);
    pushReal8(result1dd0);
    pushReal8(result1dd1);
    pushReal8(result1d);
    pushReal8(result1d0dd);
    pushReal8(result1d0d);
    pushReal8(result1d0d0);
    pushReal8(result1d0);
    pushReal8(result1d1d);
    pushReal8(result1d1);
    pushReal8(result1d2);
    pushReal8(result1);
    result1dddd = cdf_n_d_d_d_d_nodiff(d1, d1d2, d1d1, d1d1d, d1d0, d1d0d0, 
                                       d1d0d, d1d0dd, d1d, d1dd1, d1dd0, 
                                       d1dd0d, d1dd, d1ddd0, d1ddd, d1dddd, &
                                       result1, &result1d2, &result1d1, &
                                       result1d1d, &result1d0, &result1d0d0, &
                                       result1d0d, &result1d0dd, &result1d, &
                                       result1dd1, &result1dd0, &result1dd0d, 
                                       &result1dd, &result1ddd0, &result1ddd);
    result2d0 = 0.0;
    result2dd0 = 0.0;
    result2d0d = 0.0;
    result2d1 = 0.0;
    result2ddd0 = 0.0;
    result2dd0d = 0.0;
    result2dd1 = 0.0;
    result2d0dd = 0.0;
    result2d0d0 = 0.0;
    result2d1d = 0.0;
    result2d2 = 0.0;
    result2dddd = cdf_n_d_d_d_d_nodiff(d2, d2d2, d2d1, d2d1d, d2d0, d2d0d0, 
                                       d2d0d, d2d0dd, d2d, d2dd1, d2dd0, 
                                       d2dd0d, d2dd, d2ddd0, d2ddd, d2dddd, &
                                       result2, &result2d2, &result2d1, &
                                       result2d1d, &result2d0, &result2d0d0, &
                                       result2d0d, &result2d0dd, &result2d, &
                                       result2dd1, &result2dd0, &result2dd0d, 
                                       &result2dd, &result2ddd0, &result2ddd);
    *Sdd0b = *Sdd0b + result1d0d0*call_price_d_d_d_db + result1d0*(*
        call_price_d_d_db) + result1*(*call_price_ddb) + result1d2*(*
        call_price_dddb);
    result1d0d0b = Sdd0*call_price_d_d_d_db + Sd*(*call_price_d_ddb) + S*(*
        call_pricedd0b) + Sd1*(*call_pricedddb);
    result1d0b = Sdd0d*call_price_d_d_d_db + Sdd0*(*call_price_d_d_db) + Sd*(*
        call_price_d_db) + Sdd1*(*call_price_d_ddb) + S*(*call_pricedb) + Sd2*
        (*call_pricedd0b) + Sd1*(*call_priceddb) + Sd1d*(*call_pricedddb);
    *Sdd0db = *Sdd0db + result1d0*call_price_d_d_d_db + result1*(*
        call_price_dddb);
    result1d0db = Sdd1*call_price_d_d_d_db + Sd*(*call_price_d_d_db) + S*(*
        call_priceddb) + Sd2*(*call_pricedddb);
    *Sdd1b = *Sdd1b + result1d0d*call_price_d_d_d_db + result1d0*(*
        call_price_d_ddb) + result1*(*call_price_dd0b) + result1d1*(*
        call_price_dddb);
    *Sdb = *Sdb + result1d0dd*call_price_d_d_d_db + result1d0d*(*
        call_price_d_d_db) + result1d0*(*call_price_d_db) + result1d0d0*(*
        call_price_d_ddb) + result1*(*call_price_db) + result1d2*(*
        call_price_dd0b) + result1d1*(*call_price_ddb) + result1d1d*(*
        call_price_dddb);
    result1d0ddb = Sd*call_price_d_d_d_db + S*(*call_pricedddb);
    result1d1b = Sddd0*call_price_d_d_d_db + Sdd*(*call_price_d_d_db) + Sd*(*
        call_price_ddb) + Sdd1*(*call_price_dddb) + S*(*call_priced0b) + Sd2*(
        *call_priced0db) + Sd0*(*call_priceddb) + Sd0d0*(*call_pricedddb);
    *Sddd0b = *Sddd0b + result1d1*call_price_d_d_d_db + result1*(*
        call_price_d_ddb);
    *Sddb = *Sddb + result1d1d*call_price_d_d_d_db + result1d1*(*
        call_price_d_d_db) + result1*(*call_price_d_db) + result1d2*(*
        call_price_d_ddb);
    result1d1db = Sdd*call_price_d_d_d_db + Sd*(*call_price_dddb) + S*(*
        call_priced0db) + Sd0*(*call_pricedddb);
    *Sdddb = *Sdddb + result1d2*call_price_d_d_d_db + result1*(*
        call_price_d_d_db);
    result1d2b = Sddd*call_price_d_d_d_db + Sdd*(*call_price_d_ddb) + Sd*(*
        call_price_dd0b) + Sdd0*(*call_price_dddb) + S*(*call_priced1b) + Sd1*
        (*call_priced0db) + Sd0*(*call_pricedd0b) + Sd0d*(*call_pricedddb);
    result1b = Sdddd*call_price_d_d_d_db + Sddd*(*call_price_d_d_db) + Sdd*(*
        call_price_d_db) + Sddd0*(*call_price_d_ddb) + Sd*(*call_price_db) + 
        Sdd1*(*call_price_dd0b) + Sdd0*(*call_price_ddb) + Sdd0d*(*
        call_price_dddb) + S*(*call_priceb) + Sd2*(*call_priced1b) + Sd1*(*
        call_priced0b) + Sd1d*(*call_priced0db) + Sd0*(*call_pricedb) + Sd0d0*
        (*call_pricedd0b) + Sd0d*(*call_priceddb) + Sd0dd*(*call_pricedddb);
    *Sddddb = *Sddddb + result1*call_price_d_d_d_db;
    result1dd0b = Sd0d0*call_price_d_d_d_db + Sd0*(*call_price_d_d_db) + S*(*
        call_price_ddb) + Sd2*(*call_price_dddb);
    *Sd0d0b = *Sd0d0b + result1dd0*call_price_d_d_d_db + result1d*(*
        call_price_d_ddb) + result1*(*call_pricedd0b) + result1d1*(*
        call_pricedddb);
    *Sd0b = *Sd0b + result1dd0d*call_price_d_d_d_db + result1dd0*(*
        call_price_d_d_db) + result1d*(*call_price_d_db) + result1dd1*(*
        call_price_d_ddb) + result1*(*call_pricedb) + result1d2*(*
        call_pricedd0b) + result1d1*(*call_priceddb) + result1d1d*(*
        call_pricedddb);
    result1dd0db = Sd0*call_price_d_d_d_db + S*(*call_price_dddb);
    *Sd0db = *Sd0db + result1dd1*call_price_d_d_d_db + result1d*(*
        call_price_d_d_db) + result1*(*call_priceddb) + result1d2*(*
        call_pricedddb);
    result1dd1b = Sd0d*call_price_d_d_d_db + Sd0*(*call_price_d_ddb) + S*(*
        call_price_dd0b) + Sd1*(*call_price_dddb);
    result1db = Sd0dd*call_price_d_d_d_db + Sd0d*(*call_price_d_d_db) + Sd0*(*
        call_price_d_db) + Sd0d0*(*call_price_d_ddb) + S*(*call_price_db) + 
        Sd2*(*call_price_dd0b) + Sd1*(*call_price_ddb) + Sd1d*(*
        call_price_dddb);
    *Sd0ddb = *Sd0ddb + result1d*call_price_d_d_d_db + result1*(*
        call_pricedddb);
    *Sd1b = *Sd1b + result1ddd0*call_price_d_d_d_db + result1dd*(*
        call_price_d_d_db) + result1d*(*call_price_ddb) + result1dd1*(*
        call_price_dddb) + result1*(*call_priced0b) + result1d2*(*
        call_priced0db) + result1d0*(*call_priceddb) + result1d0d0*(*
        call_pricedddb);
    result1ddd0b = Sd1*call_price_d_d_d_db + S*(*call_price_d_ddb);
    result1ddb = Sd1d*call_price_d_d_d_db + Sd1*(*call_price_d_d_db) + S*(*
        call_price_d_db) + Sd2*(*call_price_d_ddb);
    *Sd1db = *Sd1db + result1dd*call_price_d_d_d_db + result1d*(*
        call_price_dddb) + result1*(*call_priced0db) + result1d0*(*
        call_pricedddb);
    result1dddb = Sd2*call_price_d_d_d_db + S*(*call_price_d_d_db);
    *Sd2b = *Sd2b + result1ddd*call_price_d_d_d_db + result1dd*(*
        call_price_d_ddb) + result1d*(*call_price_dd0b) + result1dd0*(*
        call_price_dddb) + result1*(*call_priced1b) + result1d1*(*
        call_priced0db) + result1d0*(*call_pricedd0b) + result1d0d*(*
        call_pricedddb);
    *Sb = *Sb + result1dddd*call_price_d_d_d_db + result1ddd*(*
        call_price_d_d_db) + result1dd*(*call_price_d_db) + result1ddd0*(*
        call_price_d_ddb) + result1d*(*call_price_db) + result1dd1*(*
        call_price_dd0b) + result1dd0*(*call_price_ddb) + result1dd0d*(*
        call_price_dddb) + result1*(*call_priceb) + result1d2*(*call_priced1b)
        + result1d1*(*call_priced0b) + result1d1d*(*call_priced0db) + 
        result1d0*(*call_pricedb) + result1d0d0*(*call_pricedd0b) + result1d0d
        *(*call_priceddb) + result1d0dd*(*call_pricedddb);
    result1ddddb = S*call_price_d_d_d_db;
    *Kdd0b = *Kdd0b - result2d0d0*call_price_d_d_d_db - result2d0*(*
        call_price_d_d_db) - result2*(*call_price_ddb) - result2d2*(*
        call_price_dddb);
    result2d0d0b = -(Kdd0*call_price_d_d_d_db) - Kd*(*call_price_d_ddb) - K*(*
        call_pricedd0b) - Kd1*(*call_pricedddb);
    result2d0b = -(Kdd0d*call_price_d_d_d_db) - Kdd0*(*call_price_d_d_db) - Kd
        *(*call_price_d_db) - Kdd1*(*call_price_d_ddb) - K*(*call_pricedb) - 
        Kd2*(*call_pricedd0b) - Kd1*(*call_priceddb) - Kd1d*(*call_pricedddb);
    *Kdd0db = *Kdd0db - result2d0*call_price_d_d_d_db - result2*(*
        call_price_dddb);
    result2d0db = -(Kdd1*call_price_d_d_d_db) - Kd*(*call_price_d_d_db) - K*(*
        call_priceddb) - Kd2*(*call_pricedddb);
    *Kdd1b = *Kdd1b - result2d0d*call_price_d_d_d_db - result2d0*(*
        call_price_d_ddb) - result2*(*call_price_dd0b) - result2d1*(*
        call_price_dddb);
    *Kdb = *Kdb - result2d0dd*call_price_d_d_d_db - result2d0d*(*
        call_price_d_d_db) - result2d0*(*call_price_d_db) - result2d0d0*(*
        call_price_d_ddb) - result2*(*call_price_db) - result2d2*(*
        call_price_dd0b) - result2d1*(*call_price_ddb) - result2d1d*(*
        call_price_dddb);
    result2d0ddb = -(Kd*call_price_d_d_d_db) - K*(*call_pricedddb);
    result2d1b = -(Kddd0*call_price_d_d_d_db) - Kdd*(*call_price_d_d_db) - Kd*
        (*call_price_ddb) - Kdd1*(*call_price_dddb) - K*(*call_priced0b) - Kd2
        *(*call_priced0db) - Kd0*(*call_priceddb) - Kd0d0*(*call_pricedddb);
    *Kddd0b = *Kddd0b - result2d1*call_price_d_d_d_db - result2*(*
        call_price_d_ddb);
    *Kddb = *Kddb - result2d1d*call_price_d_d_d_db - result2d1*(*
        call_price_d_d_db) - result2*(*call_price_d_db) - result2d2*(*
        call_price_d_ddb);
    result2d1db = -(Kdd*call_price_d_d_d_db) - Kd*(*call_price_dddb) - K*(*
        call_priced0db) - Kd0*(*call_pricedddb);
    *Kdddb = *Kdddb - result2d2*call_price_d_d_d_db - result2*(*
        call_price_d_d_db);
    result2d2b = -(Kddd*call_price_d_d_d_db) - Kdd*(*call_price_d_ddb) - Kd*(*
        call_price_dd0b) - Kdd0*(*call_price_dddb) - K*(*call_priced1b) - Kd1*
        (*call_priced0db) - Kd0*(*call_pricedd0b) - Kd0d*(*call_pricedddb);
    result2b = -(Kdddd*call_price_d_d_d_db) - Kddd*(*call_price_d_d_db) - Kdd*
        (*call_price_d_db) - Kddd0*(*call_price_d_ddb) - Kd*(*call_price_db) -
        Kdd1*(*call_price_dd0b) - Kdd0*(*call_price_ddb) - Kdd0d*(*
        call_price_dddb) - K*(*call_priceb) - Kd2*(*call_priced1b) - Kd1*(*
        call_priced0b) - Kd1d*(*call_priced0db) - Kd0*(*call_pricedb) - Kd0d0*
        (*call_pricedd0b) - Kd0d*(*call_priceddb) - Kd0dd*(*call_pricedddb);
    *Kddddb = *Kddddb - result2*call_price_d_d_d_db;
    result2dd0b = -(Kd0d0*call_price_d_d_d_db) - Kd0*(*call_price_d_d_db) - K*
        (*call_price_ddb) - Kd2*(*call_price_dddb);
    *Kd0d0b = *Kd0d0b - result2dd0*call_price_d_d_d_db - result2d*(*
        call_price_d_ddb) - result2*(*call_pricedd0b) - result2d1*(*
        call_pricedddb);
    *Kd0b = *Kd0b - result2dd0d*call_price_d_d_d_db - result2dd0*(*
        call_price_d_d_db) - result2d*(*call_price_d_db) - result2dd1*(*
        call_price_d_ddb) - result2*(*call_pricedb) - result2d2*(*
        call_pricedd0b) - result2d1*(*call_priceddb) - result2d1d*(*
        call_pricedddb);
    result2dd0db = -(Kd0*call_price_d_d_d_db) - K*(*call_price_dddb);
    *Kd0db = *Kd0db - result2dd1*call_price_d_d_d_db - result2d*(*
        call_price_d_d_db) - result2*(*call_priceddb) - result2d2*(*
        call_pricedddb);
    result2dd1b = -(Kd0d*call_price_d_d_d_db) - Kd0*(*call_price_d_ddb) - K*(*
        call_price_dd0b) - Kd1*(*call_price_dddb);
    result2db = -(Kd0dd*call_price_d_d_d_db) - Kd0d*(*call_price_d_d_db) - Kd0
        *(*call_price_d_db) - Kd0d0*(*call_price_d_ddb) - K*(*call_price_db) -
        Kd2*(*call_price_dd0b) - Kd1*(*call_price_ddb) - Kd1d*(*
        call_price_dddb);
    *Kd0ddb = *Kd0ddb - result2d*call_price_d_d_d_db - result2*(*
        call_pricedddb);
    *Kd1b = *Kd1b - result2ddd0*call_price_d_d_d_db - result2dd*(*
        call_price_d_d_db) - result2d*(*call_price_ddb) - result2dd1*(*
        call_price_dddb) - result2*(*call_priced0b) - result2d2*(*
        call_priced0db) - result2d0*(*call_priceddb) - result2d0d0*(*
        call_pricedddb);
    result2ddd0b = -(Kd1*call_price_d_d_d_db) - K*(*call_price_d_ddb);
    result2ddb = -(Kd1d*call_price_d_d_d_db) - Kd1*(*call_price_d_d_db) - K*(*
        call_price_d_db) - Kd2*(*call_price_d_ddb);
    *Kd1db = *Kd1db - result2dd*call_price_d_d_d_db - result2d*(*
        call_price_dddb) - result2*(*call_priced0db) - result2d0*(*
        call_pricedddb);
    result2dddb = -(Kd2*call_price_d_d_d_db) - K*(*call_price_d_d_db);
    *Kd2b = *Kd2b - result2ddd*call_price_d_d_d_db - result2dd*(*
        call_price_d_ddb) - result2d*(*call_price_dd0b) - result2dd0*(*
        call_price_dddb) - result2*(*call_priced1b) - result2d1*(*
        call_priced0db) - result2d0*(*call_pricedd0b) - result2d0d*(*
        call_pricedddb);
    *Kb = *Kb - result2dddd*call_price_d_d_d_db - result2ddd*(*
        call_price_d_d_db) - result2dd*(*call_price_d_db) - result2ddd0*(*
        call_price_d_ddb) - result2d*(*call_price_db) - result2dd1*(*
        call_price_dd0b) - result2dd0*(*call_price_ddb) - result2dd0d*(*
        call_price_dddb) - result2*(*call_priceb) - result2d2*(*call_priced1b)
        - result2d1*(*call_priced0b) - result2d1d*(*call_priced0db) - 
        result2d0*(*call_pricedb) - result2d0d0*(*call_pricedd0b) - result2d0d
        *(*call_priceddb) - result2d0dd*(*call_pricedddb);
    result2ddddb = -(K*call_price_d_d_d_db);
    *call_price_d_d_db = 0.0;
    *call_price_d_db = 0.0;
    *call_price_d_ddb = 0.0;
    *call_price_db = 0.0;
    *call_price_dd0b = 0.0;
    *call_price_ddb = 0.0;
    *call_price_dddb = 0.0;
    *call_priceb = 0.0;
    *call_priced1b = 0.0;
    *call_priced0b = 0.0;
    *call_priced0db = 0.0;
    *call_pricedb = 0.0;
    *call_pricedd0b = 0.0;
    *call_priceddb = 0.0;
    *call_pricedddb = 0.0;
    d2b = 0.0;
    d2d2b = 0.0;
    d2d1b = 0.0;
    d2d1db = 0.0;
    d2d0b = 0.0;
    d2d0d0b = 0.0;
    d2d0db = 0.0;
    d2d0ddb = 0.0;
    d2db = 0.0;
    d2dd1b = 0.0;
    d2dd0b = 0.0;
    d2dd0db = 0.0;
    d2ddb = 0.0;
    d2ddd0b = 0.0;
    d2dddb = 0.0;
    d2ddddb = 0.0;
    cdf_n_d_d_d_d_b(d2, &d2b, d2d2, &d2d2b, d2d1, &d2d1b, d2d1d, &d2d1db, d2d0
                    , &d2d0b, d2d0d0, &d2d0d0b, d2d0d, &d2d0db, d2d0dd, &
                    d2d0ddb, d2d, &d2db, d2dd1, &d2dd1b, d2dd0, &d2dd0b, 
                    d2dd0d, &d2dd0db, d2dd, &d2ddb, d2ddd0, &d2ddd0b, d2ddd, &
                    d2dddb, d2dddd, &d2ddddb, &result2, &result2b, &result2d2,
                    &result2d2b, &result2d1, &result2d1b, &result2d1d, &
                    result2d1db, &result2d0, &result2d0b, &result2d0d0, &
                    result2d0d0b, &result2d0d, &result2d0db, &result2d0dd, &
                    result2d0ddb, &result2d, &result2db, &result2dd1, &
                    result2dd1b, &result2dd0, &result2dd0b, &result2dd0d, &
                    result2dd0db, &result2dd, &result2ddb, &result2ddd0, &
                    result2ddd0b, &result2ddd, &result2dddb, result2ddddb);
    popReal8(&result1);
    popReal8(&result1d2);
    popReal8(&result1d1);
    popReal8(&result1d1d);
    popReal8(&result1d0);
    popReal8(&result1d0d0);
    popReal8(&result1d0d);
    popReal8(&result1d0dd);
    popReal8(&result1d);
    popReal8(&result1dd1);
    popReal8(&result1dd0);
    popReal8(&result1dd0d);
    popReal8(&result1dd);
    popReal8(&result1ddd0);
    popReal8(&result1ddd);
    popReal8(&result1dddd);
    d1b = 0.0;
    d1d2b = 0.0;
    d1d1b = 0.0;
    d1d1db = 0.0;
    d1d0b = 0.0;
    d1d0d0b = 0.0;
    d1d0db = 0.0;
    d1d0ddb = 0.0;
    d1db = 0.0;
    d1dd1b = 0.0;
    d1dd0b = 0.0;
    d1dd0db = 0.0;
    d1ddb = 0.0;
    d1ddd0b = 0.0;
    d1dddb = 0.0;
    d1ddddb = 0.0;
    cdf_n_d_d_d_d_b(d1, &d1b, d1d2, &d1d2b, d1d1, &d1d1b, d1d1d, &d1d1db, d1d0
                    , &d1d0b, d1d0d0, &d1d0d0b, d1d0d, &d1d0db, d1d0dd, &
                    d1d0ddb, d1d, &d1db, d1dd1, &d1dd1b, d1dd0, &d1dd0b, 
                    d1dd0d, &d1dd0db, d1dd, &d1ddb, d1ddd0, &d1ddd0b, d1ddd, &
                    d1dddb, d1dddd, &d1ddddb, &result1, &result1b, &result1d2,
                    &result1d2b, &result1d1, &result1d1b, &result1d1d, &
                    result1d1db, &result1d0, &result1d0b, &result1d0d0, &
                    result1d0d0b, &result1d0d, &result1d0db, &result1d0dd, &
                    result1d0ddb, &result1d, &result1db, &result1dd1, &
                    result1dd1b, &result1dd0, &result1dd0b, &result1dd0d, &
                    result1dd0db, &result1dd, &result1ddb, &result1ddd0, &
                    result1ddd0b, &result1ddd, &result1dddb, result1ddddb);
    d1ddddb = d1ddddb + d2ddddb;
    d1dddb = d1dddb + d2dddb;
    d1ddd0b = d1ddd0b + d2ddd0b;
    d1ddb = d1ddb + d2ddb;
    d1dd0db = d1dd0db + d2dd0db;
    d1dd0b = d1dd0b + d2dd0b;
    d1dd1b = d1dd1b + d2dd1b;
    d1db = d1db + d2db;
    d1d0ddb = d1d0ddb + d2d0ddb;
    d1d0db = d1d0db + d2d0db;
    d1d0d0b = d1d0d0b + d2d0d0b;
    d1d0b = d1d0b + d2d0b;
    d1d1db = d1d1db + d2d1db;
    d1d1b = d1d1b + d2d1b;
    d1d2b = d1d2b + d2d2b;
    d1b = d1b + d2b;
    temp11 = Kd1*tempdd0 + tempd*Kd1d + tempdd*Kd2 + K*tempddd + tempd0*Kd0d0 
        + Kd0*tempd0d + Kd0d*tempd1 + temp*Kd0dd;
    temp10 = tempd0*Kd2 + K*tempd0d + Kd1*tempd1 + temp*Kd1d;
    temp13 = K*tempd1 + temp*Kd2;
    temp12 = (Sdddd-Kdd0*tempdd0-tempd*Kdd0d-tempdd*Kdd1-Kd*tempddd-tempd0*
        Kddd0-Kdd*tempd0d-Kddd*tempd1-temp*Kdddd-temp1d*temp4d-temp4*temp1dd-
        temp8*temp1d0-temp1*temp11-temp7*temp3d-temp3*temp10-temp6*temp13)/(
        temp*K);
    tempb3 = d1ddddb/totalvol;
    totalvolddddb = 0.5*d1ddddb - d2ddddb - temp0*tempb3;
    totalvoldddb = -d2dddb - temp0d1*tempb3;
    totalvolddd0b = -d2ddd0b - temp0d0*tempb3;
    totalvolddb = -d2ddb - temp0d0d*tempb3;
    totalvoldd0db = -d2dd0db - temp0d*tempb3;
    totalvoldd0b = -d2dd0b - temp0dd0*tempb3;
    totalvoldd1b = -d2dd1b - temp0dd*tempb3;
    totalvoldb = -d2db - temp0ddd*tempb3;
    totalvold0ddb = -d2d0ddb - temp2*tempb3;
    totalvold0db = -d2d0db - temp2d0*tempb3;
    totalvold0d0b = -d2d0d0b - temp2d*tempb3;
    totalvold0b = -d2d0b - temp2dd*tempb3;
    totalvold1db = -d2d1db - temp5*tempb3;
    totalvold1b = -d2d1b - temp5d*tempb3;
    totalvold2b = -d2d2b - temp9*tempb3;
    totalvolb = -d2b - (temp12-totalvoldd0*temp0dd0-temp0d*totalvoldd0d-
        temp0dd*totalvoldd1-totalvold*temp0ddd-temp0d0*totalvolddd0-totalvoldd
        *temp0d0d-totalvolddd*temp0d1-temp0*totalvoldddd-temp2d*totalvold0d0-
        totalvold0*temp2dd-totalvold0d*temp2d0-temp2*totalvold0dd-totalvold1*
        temp5d-temp5*totalvold1d-temp9*totalvold2)*tempb3/totalvol;
    tempb2 = tempb3/(temp*K);
    temp0dd0b = -(totalvoldd0*tempb3);
    temp0db = -(totalvoldd0d*tempb3);
    temp0ddb = -(totalvoldd1*tempb3);
    temp0dddb = d1d0ddb - totalvold*tempb3;
    temp0d0b = -(totalvolddd0*tempb3);
    temp0d0db = -(totalvoldd*tempb3);
    temp0d1b = -(totalvolddd*tempb3);
    temp0b = -(totalvoldddd*tempb3);
    temp2db = -(totalvold0d0*tempb3);
    temp2ddb = d1dd0db - totalvold0*tempb3;
    temp2d0b = -(totalvold0d*tempb3);
    temp2b = -(totalvold0dd*tempb3);
    temp5db = d1ddd0b - totalvold1*tempb3;
    temp5b = -(totalvold1d*tempb3);
    temp9b = d1dddb - totalvold2*tempb3;
    *Sddddb = *Sddddb + tempb2;
    tempdd0b = -(Kdd0*tempb2);
    *Kdd0db = *Kdd0db - tempd*tempb2;
    *Kdd1b = *Kdd1b - tempdd*tempb2;
    *Kddd0b = *Kddd0b - tempd0*tempb2;
    tempd1b = -(Kddd*tempb2);
    tempb = -(Kdddd*tempb2);
    *Kddddb = *Kddddb - temp*tempb2;
    temp4db = -(temp1d*tempb2);
    temp1ddb = -(temp4*tempb2);
    temp1d0b = -(temp8*tempb2);
    tempb1 = -(temp1*tempb2);
    tempdddb = K*tempb1 - Kd*tempb2;
    temp3db = -(temp7*tempb2);
    tempb0 = -(temp3*tempb2);
    tempd0db = K*tempb0 - Kdd*tempb2 + Kd0*tempb1;
    tempb4 = -(temp6*tempb2);
    tempb5 = -(temp12*tempb2);
    *Kd1db = *Kd1db + temp*tempb0 + tempd*tempb1;
    *Kd0ddb = *Kd0ddb + temp*tempb1;
    tempb3 = temp9b/totalvol;
    temp6b = tempb3 - temp13*tempb2;
    totalvoldddb = totalvoldddb + 0.5*d1dddb - temp0*tempb3;
    temp0db = temp0db - totalvoldd0*tempb3;
    totalvoldd0b = totalvoldd0b - temp0d*tempb3;
    totalvoldb = totalvoldb - temp0dd*tempb3;
    temp0ddb = temp0ddb + d1d0db - totalvold*tempb3;
    totalvolddb = totalvolddb - temp0d0*tempb3;
    temp0d0b = temp0d0b - totalvoldd*tempb3;
    temp0b = temp0b - totalvolddd*tempb3;
    totalvold0b = totalvold0b - temp2d*tempb3;
    temp2db = temp2db + d1dd0b - totalvold0*tempb3;
    temp2b = temp2b - totalvold0d*tempb3;
    totalvold0db = totalvold0db - temp2*tempb3;
    temp5b = temp5b + d1ddb - totalvold1*tempb3;
    totalvold1b = totalvold1b - temp5*tempb3;
    totalvolb = totalvolb - (temp6-temp0d*totalvoldd0-totalvold*temp0dd-
        totalvoldd*temp0d0-temp0*totalvolddd-totalvold0*temp2d-temp2*
        totalvold0d-temp5*totalvold1)*tempb3/totalvol;
    tempb3 = temp6b/(temp*K);
    *Kdd0b = *Kdd0b - tempdd0*tempb2 - tempd*tempb3;
    *Kdb = *Kdb - tempddd*tempb2 - tempdd*tempb3;
    *Kddb = *Kddb - tempd0d*tempb2 - tempd0*tempb3;
    *Kdddb = *Kdddb - tempd1*tempb2 - temp*tempb3;
    temp1db = -(temp4d*tempb2) - temp4*tempb3;
    temp4b = -(temp1dd*tempb2) - temp1d*tempb3;
    temp8b = -(temp1d0*tempb2) - temp1*tempb3;
    tempdb = Kd1d*tempb1 - Kdd0d*tempb2 + Kd1*temp8b - Kdd0*tempb3;
    tempddb = Kd2*tempb1 - Kdd1*tempb2 + K*temp8b - Kd*tempb3;
    temp1b = -(temp11*tempb2) - temp8*tempb3;
    temp7b = -(temp3d*tempb2) - temp3*tempb3;
    tempd0b = Kd2*tempb0 - Kddd0*tempb2 + Kd0d0*tempb1 + K*temp7b - Kdd*tempb3
        + Kd0*temp8b;
    temp3b = -(temp10*tempb2) - temp7*tempb3;
    *Kd1b = *Kd1b + tempd1*tempb0 + tempdd0*tempb1 + temp*temp7b + tempd*
        temp8b;
    *Kd0b = *Kd0b + tempd0d*tempb1 + tempd0*temp8b;
    *Kd0db = *Kd0db + tempd1*tempb1 + temp*temp8b;
    *Sdddb = *Sdddb + tempb3;
    tempb2 = -((Sddd-tempd*Kdd0-Kd*tempdd-Kdd*tempd0-temp*Kddd-temp4*temp1d-
        temp1*temp8-temp3*temp7)*tempb3/(temp*K));
    tempb = tempb + K*tempb5 + Kd2*tempb4 + Kd1d*tempb0 + Kd0dd*tempb1 + K*
        tempb2 - Kddd*tempb3 + Kd1*temp7b + Kd0d*temp8b;
    *Kb = *Kb + temp*tempb5 + tempd1*tempb4 + tempd0d*tempb0 + tempddd*tempb1 
        + temp*tempb2 + tempd0*temp7b + tempdd*temp8b;
    popReal8(&temp7);
    temp8 = (temp3-totalvold*temp0d-temp0*totalvoldd-temp2*totalvold0)/
        totalvol;
    tempb3 = temp5db/totalvol;
    totalvolddd0b = totalvolddd0b + 0.5*d1ddd0b - temp0*tempb3;
    totalvolddb = totalvolddb + 0.5*d1ddb - temp0d1*tempb3;
    temp8b = temp5b - totalvold2*tempb3;
    temp3db = temp3db + tempb3;
    temp0db = temp0db - totalvoldd1*tempb3;
    totalvoldd1b = totalvoldd1b - temp0d*tempb3;
    totalvoldb = totalvoldb - temp0dd0*tempb3;
    temp0dd0b = temp0dd0b + d1d0d0b - totalvold*tempb3;
    temp0d1b = temp0d1b - totalvoldd*tempb3;
    temp0b = temp0b - totalvolddd0*tempb3;
    totalvold0b = totalvold0b - temp2d0*tempb3;
    temp2d0b = temp2d0b + d1dd1b - totalvold0*tempb3;
    temp2b = temp2b - totalvold0d0*tempb3;
    totalvold0d0b = totalvold0d0b - temp2*tempb3;
    totalvold2b = totalvold2b - temp8*tempb3;
    totalvolb = totalvolb - (temp3d-temp0d*totalvoldd1-totalvold*temp0dd0-
        totalvoldd*temp0d1-temp0*totalvolddd0-totalvold0*temp2d0-temp2*
        totalvold0d0-temp8*totalvold2)*tempb3/totalvol;
    tempb3 = temp8b/totalvol;
    temp3b = temp3b + tempb3;
    totalvoldb = totalvoldb - temp0d*tempb3;
    temp0db = temp0db + d1d0b - totalvold*tempb3;
    temp0b = temp0b - totalvoldd*tempb3;
    totalvolddb = totalvolddb - temp0*tempb3;
    temp2b = temp2b + d1db - totalvold0*tempb3;
    totalvold0b = totalvold0b - temp2*tempb3;
    totalvolb = totalvolb - (temp3-totalvold*temp0d-temp0*totalvoldd-temp2*
        totalvold0)*tempb3/totalvol;
    temp8 = (Sdd-Kd*tempd-temp*Kdd-temp1*temp4)/(temp*K);
    popReal8(&temp3);
    popReal8(&temp3d);
    temp12 = K*tempd1 + temp*Kd2;
    tempb3 = temp3db/(temp*K);
    temp8b = temp3b - temp12*tempb3;
    *Sddd0b = *Sddd0b + tempb3;
    tempdb = tempdb - Kdd1*tempb3;
    *Kdd1b = *Kdd1b - tempd*tempb3;
    *Kdb = *Kdb - tempdd0*tempb3;
    *Kddb = *Kddb - tempd1*tempb3;
    *Kddd0b = *Kddd0b - temp*tempb3;
    temp4b = temp4b - temp1d0*tempb3;
    temp1d0b = temp1d0b - temp4*tempb3;
    temp1b = temp1b - temp4d*tempb3;
    temp4db = temp4db - temp1*tempb3;
    tempdd0b = tempdd0b + Kd1*tempb1 + K*temp4db - Kd*tempb3;
    *Kd0d0b = *Kd0d0b + tempd0*tempb1 + temp*temp4db;
    tempb2 = -(temp8*tempb3);
    tempd1b = tempd1b + K*tempb4 + Kd1*tempb0 + Kd0d*tempb1 + K*tempb2 - Kdd*
        tempb3 + Kd0*temp4db;
    *Kd2b = *Kd2b + temp*tempb4 + tempd0*tempb0 + tempdd*tempb1 + temp*tempb2 
        + tempd*temp4db;
    tempb1 = -((Sddd0-tempd*Kdd1-Kd*tempdd0-Kdd*tempd1-temp*Kddd0-temp4*
        temp1d0-temp1*temp4d-temp8*temp12)*tempb3/(temp*K));
    tempb = tempb + K*tempb1 - Kddd0*tempb3 + Kd2*tempb2;
    *Kb = *Kb + temp*tempb1 + tempd1*tempb2;
    popReal8(&temp8);
    tempb3 = temp8b/(temp*K);
    *Sddb = *Sddb + tempb3;
    *Kdb = *Kdb - tempd*tempb3;
    *Kddb = *Kddb - temp*tempb3;
    temp1b = temp1b - temp4*tempb3;
    temp4b = temp4b - temp1*tempb3;
    tempdb = tempdb + K*temp4b - Kd*tempb3 + Kd2*temp4db;
    tempb2 = -((Sdd-Kd*tempd-temp*Kdd-temp1*temp4)*tempb3/(temp*K));
    tempb = tempb + K*tempb2 - Kdd*tempb3 + Kd0*temp4b + Kd0d0*temp4db;
    *Kb = *Kb + temp*tempb2 + tempd*temp4b + tempdd0*temp4db;
    popReal8(&temp4);
    *Kd0b = *Kd0b + temp*temp4b + tempd1*temp4db;
    popReal8(&temp4d);
    tempb3 = temp2ddb/totalvol;
    totalvoldd0db = totalvoldd0db + 0.5*d1dd0db - temp0*tempb3;
    totalvoldd0b = totalvoldd0b + 0.5*d1dd0b - temp0d1*tempb3;
    totalvoldd1b = totalvoldd1b + 0.5*d1dd1b - temp0d0*tempb3;
    totalvoldb = totalvoldb + 0.5*d1db - temp0d0d*tempb3;
    temp4b = temp2b - totalvold1d*tempb3;
    temp4db = temp2d0b - totalvold1*tempb3;
    temp8b = temp2db - totalvold2*tempb3;
    temp1ddb = temp1ddb + tempb3;
    temp0d0b = temp0d0b - totalvoldd1*tempb3;
    temp0d0db = temp0d0db + d1d1db - totalvold*tempb3;
    temp0d1b = temp0d1b - totalvoldd0*tempb3;
    temp0b = temp0b - totalvoldd0d*tempb3;
    totalvold1b = totalvold1b - temp4d*tempb3;
    totalvold1db = totalvold1db - temp4*tempb3;
    totalvold2b = totalvold2b - temp8*tempb3;
    totalvolb = totalvolb - (temp1dd-temp0d0*totalvoldd1-totalvold*temp0d0d-
        totalvoldd0*temp0d1-temp0*totalvoldd0d-totalvold1*temp4d-temp4*
        totalvold1d-temp8*totalvold2)*tempb3/totalvol;
    tempb3 = temp8b/totalvol;
    temp1db = temp1db + tempb3;
    totalvoldb = totalvoldb - temp0d0*tempb3;
    temp0d0b = temp0d0b + d1d1b - totalvold*tempb3;
    temp0b = temp0b - totalvoldd0*tempb3;
    totalvoldd0b = totalvoldd0b - temp0*tempb3;
    temp4b = temp4b - totalvold1*tempb3;
    totalvold1b = totalvold1b - temp4*tempb3;
    totalvolb = totalvolb - (temp1d-totalvold*temp0d0-temp0*totalvoldd0-temp4*
        totalvold1)*tempb3/totalvol;
    temp8 = (temp1-temp0*totalvold)/totalvol;
    popReal8(&temp4);
    popReal8(&temp4d);
    tempb3 = temp4db/totalvol;
    temp8b = temp4b - totalvold2*tempb3;
    temp1d0b = temp1d0b + tempb3;
    totalvoldb = totalvoldb - temp0d1*tempb3;
    temp0d1b = temp0d1b + d1d2b - totalvold*tempb3;
    temp0b = temp0b - totalvoldd1*tempb3;
    totalvoldd1b = totalvoldd1b - temp0*tempb3;
    totalvold2b = totalvold2b - temp8*tempb3;
    totalvolb = totalvolb - (temp1d0-totalvold*temp0d1-temp0*totalvoldd1-temp8
        *totalvold2)*tempb3/totalvol;
    tempb3 = temp8b/totalvol;
    temp1b = temp1b + tempb3;
    temp0b = temp0b + d1b - totalvold*tempb3;
    totalvoldb = totalvoldb - temp0*tempb3;
    totalvolb = totalvolb - (temp1-temp0*totalvold)*tempb3/totalvol;
    temp8 = K*tempd0 + temp*Kd1;
    popReal8(&temp1);
    popReal8(&temp1d0);
    popReal8(&temp1d);
    popReal8(&temp1dd);
    temp11 = tempd0*Kd2 + K*tempd0d + Kd1*tempd1 + temp*Kd1d;
    temp10 = K*tempd1 + temp*Kd2;
    tempb2 = temp1ddb/(temp*K);
    temp4b = temp1b - temp11*tempb2;
    temp4db = temp1d0b - temp8*tempb2;
    temp7b = temp1db - temp10*tempb2;
    *Sdd0db = *Sdd0db + tempb2;
    tempd0b = tempd0b - Kdd1*tempb2;
    *Kdd1b = *Kdd1b - tempd0*tempb2;
    *Kdb = *Kdb - tempd0d*tempb2;
    *Kdd0b = *Kdd0b - tempd1*tempb2;
    *Kdd0db = *Kdd0db - temp*tempb2;
    temp8b = -(temp4d*tempb2);
    tempb1 = -(temp4*tempb2);
    tempd0db = tempd0db + K*tempb1 - Kd*tempb2;
    tempb0 = -(temp7*tempb2);
    tempd1b = tempd1b + K*tempb0 - Kdd0*tempb2 + Kd1*tempb1;
    tempb3 = -((Sdd0d-tempd0*Kdd1-Kd*tempd0d-Kdd0*tempd1-temp*Kdd0d-temp8*
        temp4d-temp4*temp11-temp7*temp10)*tempb2/(temp*K));
    tempb = tempb + K*tempb3 - Kdd0d*tempb2 + Kd2*tempb0 + Kd1d*tempb1;
    *Kb = *Kb + temp*tempb3 + tempd1*tempb0 + tempd0d*tempb1;
    *Kd2b = *Kd2b + temp*tempb0 + tempd0*tempb1;
    *Kd1db = *Kd1db + temp*tempb1;
    tempb2 = temp7b/(temp*K);
    *Sdd0b = *Sdd0b + tempb2;
    *Kdb = *Kdb - tempd0*tempb2;
    *Kdd0b = *Kdd0b - temp*tempb2;
    temp4b = temp4b - temp8*tempb2;
    temp8b = temp8b - temp4*tempb2;
    tempd0b = tempd0b + Kd2*tempb1 + K*temp8b - Kd*tempb2;
    *Kd1b = *Kd1b + tempd1*tempb1 + temp*temp8b;
    tempb1 = -((Sdd0-Kd*tempd0-temp*Kdd0-temp4*temp8)*tempb2/(temp*K));
    tempb = tempb + K*tempb1 - Kdd0*tempb2;
    *Kb = *Kb + temp*tempb1;
    temp8 = (Sd-temp*Kd)/(temp*K);
    popReal8(&temp4);
    popReal8(&temp4d);
    temp11 = K*tempd1 + temp*Kd2;
    tempb2 = temp4db/(temp*K);
    *Sdd1b = *Sdd1b + tempb2;
    *Kdb = *Kdb - tempd1*tempb2;
    *Kdd1b = *Kdd1b - temp*tempb2;
    tempb1 = -(temp8*tempb2);
    tempd1b = tempd1b + K*tempb1 - Kd*tempb2;
    tempb0 = -((Sdd1-Kd*tempd1-temp*Kdd1-temp8*temp11)*tempb2/(temp*K));
    *Kb = *Kb + tempd0*temp8b + temp*tempb0 + tempd1*tempb1;
    tempb = tempb + Kd1*temp8b + K*tempb0 - Kdd1*tempb2 + Kd2*tempb1;
    temp8b = temp4b - temp11*tempb2;
    *Kd2b = *Kd2b + temp*tempb1;
    tempb2 = temp8b/(temp*K);
    *Sdb = *Sdb + tempb2;
    *Kdb = *Kdb - temp*tempb2;
    tempb1 = -((Sd-temp*Kd)*tempb2/(temp*K));
    tempb = tempb + K*tempb1 - Kd*tempb2;
    *Kb = *Kb + temp*tempb1;
    temp7 = tempd*tempd0/temp;
    temp6 = (tempdd-temp7)/temp;
    temp8 = (temp6-totalvold0*temp1d-temp1*totalvold0d-temp4*totalvold1)/
        totalvol;
    temp10 = (tempd0*tempdd0+tempd*tempd0d-temp7*tempd1)/temp;
    temp11 = (tempddd-temp10-temp6*tempd1)/temp;
    tempb2 = temp0dddb/totalvol;
    totalvold0ddb = totalvold0ddb + 0.5*d1d0ddb - temp1*tempb2;
    totalvold0db = totalvold0db + 0.5*d1d0db - temp1d0*tempb2;
    totalvold0d0b = totalvold0d0b + 0.5*d1d0d0b - temp1d*tempb2;
    totalvold0b = totalvold0b + 0.5*d1d0b - temp1dd*tempb2;
    totalvold1db = totalvold1db + 0.5*d1d1db - temp4*tempb2;
    totalvold1b = totalvold1b + 0.5*d1d1b - temp4d*tempb2;
    totalvold2b = totalvold2b + 0.5*d1d2b - temp8*tempb2;
    totalvolb = totalvolb + 0.5*d1b - (temp11-temp1d*totalvold0d0-totalvold0*
        temp1dd-totalvold0d*temp1d0-temp1*totalvold0dd-totalvold1*temp4d-temp4
        *totalvold1d-temp8*totalvold2)*tempb2/totalvol;
    temp1b = temp0b - totalvold0dd*tempb2;
    temp1d0b = temp0d1b - totalvold0d*tempb2;
    temp1db = temp0d0b - totalvold0d0*tempb2;
    temp1ddb = temp0d0db - totalvold0*tempb2;
    temp4b = temp0db - totalvold1d*tempb2;
    temp4db = temp0dd0b - totalvold1*tempb2;
    temp8b = temp0ddb - totalvold2*tempb2;
    tempb1 = tempb2/temp;
    tempdddb = tempdddb + tempb1;
    tempb0 = -(tempb1/temp);
    tempd1b = tempd1b - temp6*tempb1 - temp7*tempb0;
    tempd0db = tempd0db + tempd*tempb0;
    tempb2 = temp8b/totalvol;
    temp6b = tempb2 - tempd1*tempb1;
    totalvold0b = totalvold0b - temp1d*tempb2;
    temp1db = temp1db - totalvold0*tempb2;
    temp1b = temp1b - totalvold0d*tempb2;
    totalvold0db = totalvold0db - temp1*tempb2;
    temp4b = temp4b - totalvold1*tempb2;
    totalvold1b = totalvold1b - temp4*tempb2;
    totalvolb = totalvolb - (temp6-totalvold0*temp1d-temp1*totalvold0d-temp4*
        totalvold1)*tempb2/totalvol;
    popReal8(&temp6);
    tempb2 = temp6b/temp;
    tempb = tempb - temp11*tempb1 - temp10*tempb0 - (tempdd-temp7)*tempb2/temp
    ;
    temp7b = -(tempd1*tempb0) - tempb2;
    tempddb = tempddb + tempb2;
    tempb2 = temp7b/temp;
    tempd0b = tempd0b + tempdd0*tempb0 + tempd*tempb2;
    tempdb = tempdb + tempd0d*tempb0 + tempd0*tempb2;
    tempb = tempb - tempd*tempd0*tempb2/temp;
    temp7 = (tempd/temp-temp1*totalvold0)/totalvol;
    popReal8(&temp4);
    popReal8(&temp4d);
    temp10 = tempd*tempd1/temp;
    temp11 = (tempdd0-temp10)/temp;
    tempb2 = temp4db/totalvol;
    temp7b = temp4b - totalvold2*tempb2;
    tempb1 = tempb2/temp;
    tempdd0b = tempdd0b + tempd0*tempb0 + tempb1;
    totalvold0b = totalvold0b - temp1d0*tempb2;
    temp1d0b = temp1d0b - totalvold0*tempb2;
    temp1b = temp1b - totalvold0d0*tempb2;
    totalvold0d0b = totalvold0d0b - temp1*tempb2;
    totalvold2b = totalvold2b - temp7*tempb2;
    totalvolb = totalvolb - (temp11-totalvold0*temp1d0-temp1*totalvold0d0-
        temp7*totalvold2)*tempb2/totalvol;
    tempb0 = -(tempb1/temp);
    tempd1b = tempd1b + tempd*tempb0;
    tempb2 = temp7b/totalvol;
    tempb = tempb - temp11*tempb1 - temp10*tempb0 - tempd*tempb2/(temp*temp);
    tempdb = tempdb + tempd1*tempb0 + tempb2/temp;
    temp1b = temp1b - totalvold0*tempb2;
    totalvold0b = totalvold0b - temp1*tempb2;
    totalvolb = totalvolb - (tempd/temp-temp1*totalvold0)*tempb2/totalvol;
    temp7 = (tempd0/temp-temp4*totalvold1)/totalvol;
    popReal8(&temp1);
    popReal8(&temp1d0);
    popReal8(&temp1d);
    temp10 = tempd0*tempd1/temp;
    temp11 = (tempd0d-temp10)/temp;
    tempb2 = temp1ddb/totalvol;
    temp4b = temp1b - totalvold1d*tempb2;
    temp4db = temp1d0b - totalvold1*tempb2;
    temp7b = temp1db - totalvold2*tempb2;
    tempb1 = tempb2/temp;
    totalvold1b = totalvold1b - temp4d*tempb2;
    totalvold1db = totalvold1db - temp4*tempb2;
    totalvold2b = totalvold2b - temp7*tempb2;
    totalvolb = totalvolb - (temp11-totalvold1*temp4d-temp4*totalvold1d-temp7*
        totalvold2)*tempb2/totalvol;
    tempd0db = tempd0db + tempb1;
    tempb0 = -(tempb1/temp);
    popReal8(&temp7);
    tempb2 = temp7b/totalvol;
    tempb = tempb - temp11*tempb1 - temp10*tempb0 - tempd0*tempb2/(temp*temp);
    tempd0b = tempd0b + tempd1*tempb0 + tempb2/temp;
    temp4b = temp4b - totalvold1*tempb2;
    totalvold1b = totalvold1b - temp4*tempb2;
    totalvolb = totalvolb - (tempd0/temp-temp4*totalvold1)*tempb2/totalvol;
    popReal8(&temp4);
    popReal8(&temp4d);
    tempb2 = temp4db/totalvol;
    tempd1b = tempd1b + tempd0*tempb0 + tempb2/temp;
    temp7b = temp4b - totalvold2*tempb2;
    tempb = tempb + temp7b/(temp*totalvol) - tempd1*tempb2/(temp*temp);
    totalvold2b = totalvold2b - temp7*tempb2;
    totalvolb = totalvolb - (tempd1/temp-temp7*totalvold2)*tempb2/totalvol - 
        log(temp)*temp7b/(totalvol*totalvol);
    temp7 = S*Kd1/K;
    popReal8(&temp);
    popReal8(&tempd1);
    temp11 = S*Kd2/K;
    tempb2 = tempd1b/K;
    *Sd2b = *Sd2b + tempb2;
    tempb1 = -(tempb2/K);
    *Sb = *Sb + tempb/K + Kd2*tempb1;
    *Kb = *Kb - S*tempb/(K*K) - (Sd2-temp11)*tempb2/K - temp11*tempb1;
    *Kd2b = *Kd2b + S*tempb1;
    popReal8(&tempd0);
    popReal8(&tempd0d);
    temp11 = (Kd1*Sd2+S*Kd1d-temp7*Kd2)/K;
    tempb2 = tempd0db/K;
    temp6b = tempd0b - Kd2*tempb2;
    *Sd1db = *Sd1db + tempb2;
    tempb1 = -(tempb2/K);
    *Kd2b = *Kd2b - temp6*tempb2 - temp7*tempb1;
    *Kb = *Kb - (Sd1d-temp11-temp6*Kd2)*tempb2/K;
    *Sd2b = *Sd2b + Kd1*tempb1;
    *Kd1db = *Kd1db + S*tempb1;
    tempb2 = temp6b/K;
    temp7b = -(Kd2*tempb1) - tempb2;
    *Kb = *Kb - temp11*tempb1 - (Sd1-temp7)*tempb2/K;
    *Sd1b = *Sd1b + tempb2;
    tempb2 = temp7b/K;
    *Kd1b = *Kd1b + Sd2*tempb1 + S*tempb2;
    *Sb = *Sb + Kd1d*tempb1 + Kd1*tempb2;
    *Kb = *Kb - S*Kd1*tempb2/K;
    temp6 = (Kd0*Sd1+S*Kd0d-temp3*Kd1)/K;
    temp7 = (Sd0d-temp6-temp4*Kd1)/K;
    popReal8(&tempd);
    popReal8(&tempdd0);
    popReal8(&tempdd);
    temp11 = (Sd1*Kd0d0+Kd0*Sd1d+Kd0d*Sd2+S*Kd0dd-Kd1*temp3d-temp3*Kd1d-temp6*
        Kd2)/K;
    tempb2 = tempdddb/K;
    temp4b = tempdb - Kd1d*tempb2;
    temp4db = tempdd0b - Kd1*tempb2;
    temp7b = tempddb - Kd2*tempb2;
    *Sd0ddb = *Sd0ddb + tempb2;
    tempb1 = -(tempb2/K);
    *Kd1b = *Kd1b - temp4d*tempb2;
    *Kd1db = *Kd1db - temp4*tempb2 - temp3*tempb1;
    *Kd2b = *Kd2b - temp7*tempb2 - temp6*tempb1;
    *Kb = *Kb - (Sd0dd-temp11-Kd1*temp4d-temp4*Kd1d-temp7*Kd2)*tempb2/K;
    *Sd1db = *Sd1db + Kd0*tempb1;
    *Kd0ddb = *Kd0ddb + S*tempb1;
    tempb2 = temp7b/K;
    *Kd1b = *Kd1b - temp3d*tempb1 - temp4*tempb2;
    temp6b = -(Kd2*tempb1) - tempb2;
    *Kb = *Kb - temp11*tempb1 - (Sd0d-temp6-temp4*Kd1)*tempb2/K;
    *Sd0db = *Sd0db + tempb2;
    temp4b = temp4b - Kd1*tempb2;
    tempb2 = temp6b/K;
    *Sd1b = *Sd1b + Kd0d0*tempb1 + Kd0*tempb2;
    *Kd0b = *Kd0b + Sd1d*tempb1 + Sd1*tempb2;
    *Kd0db = *Kd0db + Sd2*tempb1 + S*tempb2;
    *Sb = *Sb + Kd0dd*tempb1 + Kd0d*tempb2;
    temp3b = -(Kd1d*tempb1) - Kd1*tempb2;
    *Kd1b = *Kd1b - temp3*tempb2;
    *Kb = *Kb - (Kd0*Sd1+S*Kd0d-temp3*Kd1)*tempb2/K;
    temp6 = (Sd0-temp3)/K;
    tempb2 = temp4db/K;
    temp3db = -(Kd1*tempb1) - tempb2;
    temp6b = temp4b - Kd2*tempb2;
    *Sd0d0b = *Sd0d0b + tempb2;
    *Kd2b = *Kd2b - temp6*tempb2;
    *Kb = *Kb - (Sd0d0-temp3d-temp6*Kd2)*tempb2/K;
    tempb2 = temp6b/K;
    *Sd0b = *Sd0b + tempb2;
    temp3b = temp3b - tempb2;
    *Kb = *Kb - (Sd0-temp3)*tempb2/K;
    temp6 = S*Kd0/K;
    popReal8(&temp3);
    tempb2 = temp3db/K;
    *Kd0d0b = *Kd0d0b + Sd1*tempb1 + S*tempb2;
    *Sd2b = *Sd2b + Kd0d*tempb1 + Kd0*tempb2;
    temp6b = temp3b - Kd2*tempb2;
    *Kd0b = *Kd0b + Sd2*tempb2;
    *Sb = *Sb + Kd0d0*tempb2;
    *Kd2b = *Kd2b - temp6*tempb2;
    *Kb = *Kb - (Kd0*Sd2+S*Kd0d0-temp6*Kd2)*tempb2/K;
    tempb2 = temp6b/K;
    *Sb = *Sb + Kd0*tempb2;
    *Kd0b = *Kd0b + S*tempb2;
    *Kb = *Kb - S*Kd0*tempb2/K;
    *vb = *vb + result1*totalvolb + result1d2*totalvold2b + result1d1*
        totalvold1b + result1d1d*totalvold1db + result1d0*totalvold0b + 
        result1d0d0*totalvold0d0b + result1d0d*totalvold0db + result1d0dd*
        totalvold0ddb + result1d*totalvoldb + result1dd1*totalvoldd1b + 
        result1dd0*totalvoldd0b + result1dd0d*totalvoldd0db + result1dd*
        totalvolddb + result1ddd0*totalvolddd0b + result1ddd*totalvoldddb + 
        result1dddd*totalvolddddb;
    result1b = result1b + v*totalvolb + vd2*totalvold2b + vd1*totalvold1b + 
        vd1d*totalvold1db + vd0*totalvold0b + vd0d0*totalvold0d0b + vd0d*
        totalvold0db + vd0dd*totalvold0ddb + vd*totalvoldb + vdd1*totalvoldd1b
        + vdd0*totalvoldd0b + vdd0d*totalvoldd0db + vdd*totalvolddb + vddd0*
        totalvolddd0b + vddd*totalvoldddb + vdddd*totalvolddddb;
    *vd2b = *vd2b + result1*totalvold2b + result1d1*totalvold1db + result1d0*
        totalvold0d0b + result1d0d*totalvold0ddb + result1d*totalvoldd1b + 
        result1dd0*totalvoldd0db + result1dd*totalvolddd0b + result1ddd*
        totalvolddddb;
    result1d2b = result1d2b + v*totalvold2b + vd1*totalvold1db + vd0*
        totalvold0d0b + vd0d*totalvold0ddb + vd*totalvoldd1b + vdd0*
        totalvoldd0db + vdd*totalvolddd0b + vddd*totalvolddddb;
    *vd1b = *vd1b + result1*totalvold1b + result1d2*totalvold1db + result1d0*
        totalvold0db + result1d0d0*totalvold0ddb + result1d*totalvoldd0b + 
        result1dd1*totalvoldd0db + result1dd*totalvoldddb + result1ddd0*
        totalvolddddb;
    result1d1b = result1d1b + v*totalvold1b + vd2*totalvold1db + vd0*
        totalvold0db + vd0d0*totalvold0ddb + vd*totalvoldd0b + vdd1*
        totalvoldd0db + vdd*totalvoldddb + vddd0*totalvolddddb;
    *vd1db = *vd1db + result1*totalvold1db + result1d0*totalvold0ddb + 
        result1d*totalvoldd0db + result1dd*totalvolddddb;
    result1d1db = result1d1db + v*totalvold1db + vd0*totalvold0ddb + vd*
        totalvoldd0db + vdd*totalvolddddb;
    *vd0b = *vd0b + result1*totalvold0b + result1d2*totalvold0d0b + result1d1*
        totalvold0db + result1d1d*totalvold0ddb + result1d*totalvolddb + 
        result1dd1*totalvolddd0b + result1dd0*totalvoldddb + result1dd0d*
        totalvolddddb;
    result1d0b = result1d0b + v*totalvold0b + vd2*totalvold0d0b + vd1*
        totalvold0db + vd1d*totalvold0ddb + vd*totalvolddb + vdd1*
        totalvolddd0b + vdd0*totalvoldddb + vdd0d*totalvolddddb;
    *vd0d0b = *vd0d0b + result1*totalvold0d0b + result1d1*totalvold0ddb + 
        result1d*totalvolddd0b + result1dd0*totalvolddddb;
    result1d0d0b = result1d0d0b + v*totalvold0d0b + vd1*totalvold0ddb + vd*
        totalvolddd0b + vdd0*totalvolddddb;
    *vd0db = *vd0db + result1*totalvold0db + result1d2*totalvold0ddb + 
        result1d*totalvoldddb + result1dd1*totalvolddddb;
    result1d0db = result1d0db + v*totalvold0db + vd2*totalvold0ddb + vd*
        totalvoldddb + vdd1*totalvolddddb;
    *vd0ddb = *vd0ddb + result1*totalvold0ddb + result1d*totalvolddddb;
    result1d0ddb = result1d0ddb + v*totalvold0ddb + vd*totalvolddddb;
    *vdb = *vdb + result1*totalvoldb + result1d2*totalvoldd1b + result1d1*
        totalvoldd0b + result1d1d*totalvoldd0db + result1d0*totalvolddb + 
        result1d0d0*totalvolddd0b + result1d0d*totalvoldddb + result1d0dd*
        totalvolddddb;
    result1db = result1db + v*totalvoldb + vd2*totalvoldd1b + vd1*totalvoldd0b
        + vd1d*totalvoldd0db + vd0*totalvolddb + vd0d0*totalvolddd0b + vd0d*
        totalvoldddb + vd0dd*totalvolddddb;
    *vdd1b = *vdd1b + result1*totalvoldd1b + result1d1*totalvoldd0db + 
        result1d0*totalvolddd0b + result1d0d*totalvolddddb;
    result1dd1b = result1dd1b + v*totalvoldd1b + vd1*totalvoldd0db + vd0*
        totalvolddd0b + vd0d*totalvolddddb;
    *vdd0b = *vdd0b + result1*totalvoldd0b + result1d2*totalvoldd0db + 
        result1d0*totalvoldddb + result1d0d0*totalvolddddb;
    result1dd0b = result1dd0b + v*totalvoldd0b + vd2*totalvoldd0db + vd0*
        totalvoldddb + vd0d0*totalvolddddb;
    *vdd0db = *vdd0db + result1*totalvoldd0db + result1d0*totalvolddddb;
    result1dd0db = result1dd0db + v*totalvoldd0db + vd0*totalvolddddb;
    *vddb = *vddb + result1*totalvolddb + result1d2*totalvolddd0b + result1d1*
        totalvoldddb + result1d1d*totalvolddddb;
    result1ddb = result1ddb + v*totalvolddb + vd2*totalvolddd0b + vd1*
        totalvoldddb + vd1d*totalvolddddb;
    *vddd0b = *vddd0b + result1*totalvolddd0b + result1d1*totalvolddddb;
    result1ddd0b = result1ddd0b + v*totalvolddd0b + vd1*totalvolddddb;
    *vdddb = *vdddb + result1*totalvoldddb + result1d2*totalvolddddb;
    result1dddb = result1dddb + v*totalvoldddb + vd2*totalvolddddb;
    *vddddb = *vddddb + result1*totalvolddddb;
    result1ddddb = v*totalvolddddb;
    tempb1 = (T == 0.0 ? 0.0 : result1ddddb/(2.0*temp));
    tempb = result1b - (Tdddd-2.0*(temp1d*tempdd0+tempd*temp1dd+tempdd*temp1d0
        +temp1*tempddd)-2.0*(tempd0*temp3d+temp3*tempd0d)-2.0*(temp6*tempd1))*
        tempb1/temp;
    tempd1b = result1d2b - temp6*2.0*tempb1;
    temp6b = (T == 0.0 ? -(tempd1*2.0*tempb1) : result1dddb - tempd1*2.0*
        tempb1);
    *Tddddb = *Tddddb + tempb1;
    tempb0 = -(2.0*tempb1);
    tempdb = result1d0b + temp1dd*tempb0;
    tempdd0b = result1d0d0b + temp1d*tempb0;
    tempddb = result1d0db + temp1d0*tempb0;
    tempdddb = result1d0ddb + temp1*tempb0;
    temp1b = (T == 0.0 ? tempddd*tempb0 : result1db + tempddd*tempb0);
    temp1d0b = (T == 0.0 ? tempdd*tempb0 : result1dd1b + tempdd*tempb0);
    temp1db = (T == 0.0 ? tempdd0*tempb0 : result1dd0b + tempdd0*tempb0);
    temp1ddb = (T == 0.0 ? tempd*tempb0 : result1dd0db + tempd*tempb0);
    tempb2 = -(2.0*tempb1);
    tempd0db = result1d1db + temp3*tempb2;
    temp3db = (T == 0.0 ? tempd0*tempb2 : result1ddd0b + tempd0*tempb2);
    tempb1 = temp6b/(2.0*temp);
    tempd0b = result1d1b + temp3d*tempb2 - temp3*2.0*tempb1;
    temp3b = (T == 0.0 ? tempd0d*tempb2 - tempd0*2.0*tempb1 : result1ddb + 
        tempd0d*tempb2 - tempd0*2.0*tempb1);
    *Tdddb = *Tdddb + tempb1;
    tempb0 = -(2.0*tempb1);
    tempb = tempb - (Tddd-2.0*(tempd*temp1d+temp1*tempdd)-2.0*(temp3*tempd0))*
        tempb1/temp;
    tempdb = tempdb + temp1d*tempb0;
    temp1db = temp1db + tempd*tempb0;
    temp1b = temp1b + tempdd*tempb0;
    tempddb = tempddb + temp1*tempb0;
    temp6 = (Tdd-2.0*temp1*tempd)/(2.0*temp);
    popReal8(&temp3);
    popReal8(&temp3d);
    tempb1 = temp3db/(2.0*temp);
    temp6b = temp3b - tempd1*2.0*tempb1;
    *Tddd0b = *Tddd0b + tempb1;
    tempb0 = -(2.0*tempb1);
    tempd1b = tempd1b - temp6*2.0*tempb1;
    tempb = tempb - (Tddd0-2.0*(tempd*temp1d0+temp1*tempdd0)-2.0*(temp6*tempd1
        ))*tempb1/temp;
    temp1d0b = temp1d0b + tempd*tempb0;
    tempdd0b = tempdd0b + temp1*tempb0;
    tempb1 = temp6b/(2.0*temp);
    tempdb = tempdb + temp1d0*tempb0 - temp1*2.0*tempb1;
    temp1b = temp1b + tempdd0*tempb0 - tempd*2.0*tempb1;
    *Tddb = *Tddb + tempb1;
    tempb = tempb - (Tdd-2.0*(temp1*tempd))*tempb1/temp;
    temp6 = (Tdd0-2.0*temp3*tempd0)/(2.0*temp);
    popReal8(&temp1);
    popReal8(&temp1d0);
    popReal8(&temp1d);
    tempb1 = temp1ddb/(2.0*temp);
    temp6b = temp1db - tempd1*2.0*tempb1;
    *Tdd0db = *Tdd0db + tempb1;
    tempb0 = -(2.0*tempb1);
    temp3db = temp1d0b + tempd0*tempb0;
    tempd1b = tempd1b - temp6*2.0*tempb1;
    tempb = tempb - (Tdd0d-2.0*(tempd0*temp3d+temp3*tempd0d)-2.0*(temp6*tempd1
        ))*tempb1/temp;
    tempd0db = tempd0db + temp3*tempb0;
    tempb1 = temp6b/(2.0*temp);
    temp3b = temp1b + tempd0d*tempb0 - tempd0*2.0*tempb1;
    tempd0b = tempd0b + temp3d*tempb0 - temp3*2.0*tempb1;
    *Tdd0b = *Tdd0b + tempb1;
    tempb = tempb - (Tdd0-2.0*(temp3*tempd0))*tempb1/temp;
    temp6 = Td/(2.0*temp);
    popReal8(&temp3);
    tempb1 = temp3db/(2.0*temp);
    temp6b = temp3b - tempd1*2.0*tempb1;
    *Tdd1b = *Tdd1b + tempb1;
    tempd1b = tempd1b - temp6*2.0*tempb1;
    tempb = tempb - (Tdd1-2.0*(temp6*tempd1))*tempb1/temp;
    tempb1 = temp6b/(2.0*temp);
    *Tdb = *Tdb + tempb1;
    tempb = tempb - Td*tempb1/temp;
    tempb0 = (T == 0.0 ? 0.0 : tempdddb/(2.0*temp1));
    temp1b = tempb - (Td0dd-2.0*(temp1d*temp3d+temp3*temp1dd)-2.0*(temp6*
        temp1d0))*tempb0/temp1;
    temp1d0b = tempd1b - temp6*2.0*tempb0;
    temp6b = (T == 0.0 ? -(temp1d0*2.0*tempb0) : tempddb - temp1d0*2.0*tempb0)
    ;
    *Td0ddb = *Td0ddb + tempb0;
    tempb1 = -(2.0*tempb0);
    temp1ddb = tempd0db + temp3*tempb1;
    temp3db = (T == 0.0 ? temp1d*tempb1 : tempdd0b + temp1d*tempb1);
    tempb0 = temp6b/(2.0*temp1);
    temp1db = tempd0b + temp3d*tempb1 - temp3*2.0*tempb0;
    temp3b = (T == 0.0 ? temp1dd*tempb1 - temp1d*2.0*tempb0 : tempdb + temp1dd
        *tempb1 - temp1d*2.0*tempb0);
    *Td0db = *Td0db + tempb0;
    temp1b = temp1b - (Td0d-2.0*(temp3*temp1d))*tempb0/temp1;
    temp6 = Td0/(2.0*temp1);
    popReal8(&temp3);
    tempb0 = temp3db/(2.0*temp1);
    temp6b = temp3b - temp1d0*2.0*tempb0;
    *Td0d0b = *Td0d0b + tempb0;
    temp1d0b = temp1d0b - temp6*2.0*tempb0;
    temp1b = temp1b - (Td0d0-2.0*(temp6*temp1d0))*tempb0/temp1;
    tempb0 = temp6b/(2.0*temp1);
    *Td0b = *Td0b + tempb0;
    temp1b = temp1b - Td0*tempb0/temp1;
    tempb0 = (T == 0.0 ? 0.0 : temp1ddb/(2.0*temp3));
    temp3b = temp1b - (Td1d-2.0*(temp6*temp3d))*tempb0/temp3;
    temp3db = temp1d0b - temp6*2.0*tempb0;
    temp6b = (T == 0.0 ? -(temp3d*2.0*tempb0) : temp1db - temp3d*2.0*tempb0);
    *Td1db = *Td1db + tempb0;
    tempb0 = temp6b/(2.0*temp3);
    *Td1b = *Td1b + tempb0;
    temp3b = temp3b - Td1*tempb0/temp3;
    tempb0 = (T == 0.0 ? 0.0 : temp3db/(2.0*temp6));
    temp6b = temp3b - Td2*tempb0/temp6;
    *Td2b = *Td2b + tempb0;
    if (!(T==0.0))
        *Tb = *Tb + temp6b/(2.0*sqrt(T));
}
