/*        Generated by TAPENADE     (INRIA, Ecuador team)
    Tapenade 3.16 (develop) - 25 Oct 2024 09:00
*/
/*        Generated by TAPENADE     (INRIA, Ecuador team)
    Tapenade 3.16 (develop) - 25 Oct 2024 09:00
*/
#include <math.h>
#include <stdio.h>

/*
  Differentiation of cdf_n_d in forward (tangent) mode:
   variations   of useful results: cdf_n_d *cdf_n
   with respect to varying inputs: xd x *cdf_n
   Plus diff mem management of: cdf_n:in


  Differentiation of cdf_n in forward (tangent) mode:
   variations   of useful results: cdf_n
   with respect to varying inputs: x
*/
double cdf_n_d_d(double x, double xd0, double xd, double xdd, double *cdf_n, 
        double *cdf_nd, double *cdf_n_d) {
    double arg1;
    double arg1d;
    double temp;
    *cdf_nd = 0.5*1.1283791671*exp(-(-(0.70710678118654746*x)*-(
        0.70710678118654746*x)))*0.70710678118654746*xd0;
    *cdf_n = 0.5*erfc(x*-0.70710678118654746);
    arg1d = -(0.70710678118654746*0.70710678118654746*2*x*xd0);
    arg1 = -(-(0.70710678118654746*x)*-(0.70710678118654746*x));
    temp = exp(arg1);
    *cdf_n_d = 1.1283791671*0.70710678118654746*0.5*(temp*xd);
    return 1.1283791671*0.70710678118654746*0.5*(xd*exp(arg1)*arg1d+temp*xdd);
}

/*
  Differentiation of call_price_d in forward (tangent) mode:
   variations   of useful results: call_price_d *call_price
   with respect to varying inputs: Td v Kd *call_price vd Sd K
                S T
   RW status of diff variables: Td:in v:in Kd:in call_price_d:out
                call_price:(loc) *call_price:in-out vd:in Sd:in
                K:in S:in T:in
   Plus diff mem management of: call_price:in


  Differentiation of call_price in forward (tangent) mode:
   variations   of useful results: call_price
   with respect to varying inputs: v K S T
   RW status of diff variables: v:in call_price:out K:in S:in
                T:in
*/
double call_price_d_d(double S, double Sd0, double Sd, double Sdd, double K, 
        double Kd0, double Kd, double Kdd, double v, double vd0, double vd, 
        double vdd, double T, double Td0, double Td, double Tdd, double *
        call_price, double *call_priced, double *call_price_d) {
    double totalvol;
    double totalvold0;
    double totalvold;
    double totalvoldd;
    double result1;
    double result1d0;
    double result1d;
    double result1dd;
    double result2;
    double result2d0;
    double result2d;
    double result2dd;
    double temp;
    double tempd;
    double temp0;
    double temp0d;
    double temp1;
    double temp2;
    temp1 = sqrt(T);
    tempd = (T == 0.0 ? 0.0 : Td0/(2.0*temp1));
    temp = temp1;
    temp1 = Td/(2.0*temp);
    result1dd = (T == 0.0 ? 0.0 : (Tdd-temp1*2.0*tempd)/(2.0*temp));
    result1d = (T == 0.0 ? 0.0 : temp1);
    result1d0 = tempd;
    result1 = temp;
    totalvoldd = vd*result1d0 + result1*vdd + result1d*vd0 + v*result1dd;
    totalvold = result1*vd + v*result1d;
    totalvold0 = result1*vd0 + v*result1d0;
    totalvol = v*result1;
    tempd = (Sd0-S*Kd0/K)/K;
    temp = S/K;
    temp1 = log(temp)/totalvol;
    temp0d = (tempd/temp-temp1*totalvold0)/totalvol;
    temp0 = temp1;
    double d1 = temp0 + 0.5*totalvol;
    double d1d0 = temp0d + 0.5*totalvold0;
    temp1 = (Sd-temp*Kd)/(temp*K);
    temp2 = (temp1-temp0*totalvold)/totalvol;
    double d1d = temp2 + 0.5*totalvold;
    double d1dd = ((Sdd-Kd*tempd-temp*Kdd-temp1*(K*tempd+temp*Kd0))/(temp*K)-
    totalvold*temp0d-temp0*totalvoldd-temp2*totalvold0)/totalvol + 0.5*
    totalvoldd;
    double d2 = d1 - totalvol;
    double d2d0 = d1d0 - totalvold0;
    double d2d = d1d - totalvold;
    double d2dd = d1dd - totalvoldd;
    result1dd = cdf_n_d_d(d1, d1d0, d1d, d1dd, &result1, &result1d0, &result1d
                         );
    result2d0 = 0.0;
    result2dd = cdf_n_d_d(d2, d2d0, d2d, d2dd, &result2, &result2d0, &result2d
                         );
    *call_priced = result1*Sd0 + S*result1d0 - result2*Kd0 - K*result2d0;
    *call_price = S*result1 - K*result2;
    *call_price_d = result1*Sd + S*result1d - result2*Kd - K*result2d;
    return Sd*result1d0 + result1*Sdd + result1d*Sd0 + S*result1dd - Kd*
    result2d0 - result2*Kdd - result2d*Kd0 - K*result2dd;
}
