/*        Generated by TAPENADE     (INRIA, Ecuador team)
    Tapenade 3.16 (develop) - 25 Oct 2024 09:00
*/
#include <adStack.h>
/*        Generated by TAPENADE     (INRIA, Ecuador team)
    Tapenade 3.16 (develop) - 25 Oct 2024 09:00

        Generated by TAPENADE     (INRIA, Ecuador team)
    Tapenade 3.16 (develop) - 25 Oct 2024 09:00
*/
#include <math.h>
#include <stdio.h>

/*
  Differentiation of cdf_n_d_d in reverse (adjoint) mode:
   gradient     of useful results: *cdf_nd *cdf_n_d cdf_n_d_d
                *cdf_n
   with respect to varying inputs: xdd xd x *cdf_nd *cdf_n_d *cdf_n
                xd0
   Plus diff mem management of: cdf_nd:in cdf_n_d:in cdf_n:in


  Differentiation of cdf_n_d in forward (tangent) mode:
   variations   of useful results: cdf_n_d *cdf_n
   with respect to varying inputs: xd x *cdf_n
   Plus diff mem management of: cdf_n:in


  Differentiation of cdf_n in forward (tangent) mode:
   variations   of useful results: cdf_n
   with respect to varying inputs: x
*/
void cdf_n_d_d_b(double x, double *xb, double xd0, double *xd0b, double xd, 
        double *xdb, double xdd, double *xddb, double *cdf_n, double *cdf_nb, 
        double *cdf_nd, double *cdf_ndb, double *cdf_n_d, double *cdf_n_db, 
        double cdf_n_d_db) {
    double arg1;
    double arg1b;
    double arg1d;
    double arg1db;
    double temp;
    double tempb;
    double temp0;
    double tempb0;
    double tempb1;
    arg1d = -(0.70710678118654746*0.70710678118654746*2*x*xd0);
    arg1 = -(-(0.70710678118654746*x)*-(0.70710678118654746*x));
    temp = exp(arg1);
    temp0 = -(0.70710678118654746*0.70710678118654746*(x*x));
    tempb0 = 0.70710678118654746*0.5*1.1283791671*cdf_n_d_db;
    tempb1 = exp(arg1)*tempb0;
    tempb = xdd*tempb0 + xd*0.70710678118654746*0.5*1.1283791671*(*cdf_n_db);
    arg1b = exp(arg1)*xd*arg1d*tempb0 + exp(arg1)*tempb;
    *xddb = temp*tempb0;
    *xdb = arg1d*tempb1 + temp*0.70710678118654746*0.5*1.1283791671*(*cdf_n_db
        );
    arg1db = xd*tempb1;
    *cdf_n_db = 0.0;
    *xb = 0.70710678118654746*1.1283791671*exp(-(-(0.70710678118654746*x)*-(
        0.70710678118654746*x)))*0.5*(*cdf_nb) - 2*x*(0.70710678118654746*
        0.70710678118654746)*arg1b - xd0*(0.70710678118654746*
        0.70710678118654746)*2*arg1db - 2*x*pow(0.70710678118654746, 3)*exp(
        temp0)*xd0*1.1283791671*0.5*(*cdf_ndb);
    *xd0b = exp(temp0)*1.1283791671*0.70710678118654746*0.5*(*cdf_ndb) - x*(
        0.70710678118654746*0.70710678118654746)*2*arg1db;
    *cdf_nb = 0.0;
    *cdf_ndb = 0.0;
}

/*
  Differentiation of cdf_n_d in forward (tangent) mode:
   variations   of useful results: cdf_n_d *cdf_n
   with respect to varying inputs: xd x *cdf_n
   Plus diff mem management of: cdf_n:in


  Differentiation of cdf_n in forward (tangent) mode:
   variations   of useful results: cdf_n
   with respect to varying inputs: x
*/
double cdf_n_d_d_nodiff(double x, double xd0, double xd, double xdd, double *
        cdf_n, double *cdf_nd, double *cdf_n_d) {
    double arg1;
    double arg1d;
    double temp;
    *cdf_nd = 0.5*1.1283791671*exp(-(-(0.70710678118654746*x)*-(
        0.70710678118654746*x)))*0.70710678118654746*xd0;
    *cdf_n = 0.5*erfc(x*-0.70710678118654746);
    arg1d = -(0.70710678118654746*0.70710678118654746*2*x*xd0);
    arg1 = -(-(0.70710678118654746*x)*-(0.70710678118654746*x));
    temp = exp(arg1);
    *cdf_n_d = 1.1283791671*0.70710678118654746*0.5*(temp*xd);
    return 1.1283791671*0.70710678118654746*0.5*(xd*exp(arg1)*arg1d+temp*xdd);
}

/*
  Differentiation of call_price_d_d in reverse (adjoint) mode:
   gradient     of useful results: Td Sd0 v Kd0 Tdd Kd *call_price_d
                vd0 *call_price vd Sdd *call_priced Td0 Sd Kdd
                K call_price_d_d S T vdd
   with respect to varying inputs: Td Sd0 v Kd0 Tdd Kd *call_price_d
                vd0 *call_price vd Sdd *call_priced Td0 Sd Kdd
                K S T vdd
   RW status of diff variables: Td:incr Sd0:incr v:incr Kd0:incr
                Tdd:incr Kd:incr call_price_d:(loc) *call_price_d:in-out
                vd0:incr call_price:(loc) *call_price:in-out vd:incr
                Sdd:incr call_priced:(loc) *call_priced:in-out
                Td0:incr Sd:incr Kdd:incr K:incr call_price_d_d:in-killed
                S:incr T:incr vdd:incr
   Plus diff mem management of: call_price_d:in call_price:in
                call_priced:in


  Differentiation of call_price_d in forward (tangent) mode:
   variations   of useful results: call_price_d *call_price
   with respect to varying inputs: Td v Kd *call_price vd Sd K
                S T
   RW status of diff variables: Td:in v:in Kd:in call_price_d:out
                call_price:(loc) *call_price:in-out vd:in Sd:in
                K:in S:in T:in
   Plus diff mem management of: call_price:in


  Differentiation of call_price in forward (tangent) mode:
   variations   of useful results: call_price
   with respect to varying inputs: v K S T
   RW status of diff variables: v:in call_price:out K:in S:in
                T:in
*/
void call_price_d_d_b(double S, double *Sb, double Sd0, double *Sd0b, double 
        Sd, double *Sdb, double Sdd, double *Sddb, double K, double *Kb, 
        double Kd0, double *Kd0b, double Kd, double *Kdb, double Kdd, double *
        Kddb, double v, double *vb, double vd0, double *vd0b, double vd, 
        double *vdb, double vdd, double *vddb, double T, double *Tb, double 
        Td0, double *Td0b, double Td, double *Tdb, double Tdd, double *Tddb, 
        double *call_price, double *call_priceb, double *call_priced, double *
        call_pricedb, double *call_price_d, double *call_price_db, double 
        call_price_d_db) {
    double totalvol;
    double totalvolb;
    double totalvold0;
    double totalvold0b;
    double totalvold;
    double totalvoldb;
    double totalvoldd;
    double totalvolddb;
    double result1;
    double result1b;
    double result1d0;
    double result1d0b;
    double result1d;
    double result1db;
    double result1dd;
    double result1ddb;
    double result2;
    double result2b;
    double result2d0;
    double result2d0b;
    double result2d;
    double result2db;
    double result2dd;
    double result2ddb;
    double temp;
    double tempb;
    double tempd;
    double tempdb;
    double temp0;
    double temp0b;
    double temp0d;
    double temp0db;
    double temp1;
    double temp1b;
    double temp2;
    double temp2b;
    double temp3;
    double tempb0;
    double temp4;
    double tempb1;
    double temp5;
    double tempb2;
    double tempb3;
    temp1 = sqrt(T);
    tempd = (T == 0.0 ? 0.0 : Td0/(2.0*temp1));
    temp = temp1;
    temp1 = Td/(2.0*temp);
    result1dd = (T == 0.0 ? 0.0 : (Tdd-temp1*2.0*tempd)/(2.0*temp));
    result1d = (T == 0.0 ? 0.0 : temp1);
    result1d0 = tempd;
    result1 = temp;
    totalvoldd = vd*result1d0 + result1*vdd + result1d*vd0 + v*result1dd;
    totalvold = result1*vd + v*result1d;
    totalvold0 = result1*vd0 + v*result1d0;
    totalvol = v*result1;
    tempd = (Sd0-S*Kd0/K)/K;
    pushReal8(temp);
    temp = S/K;
    temp1 = log(temp)/totalvol;
    temp0d = (tempd/temp-temp1*totalvold0)/totalvol;
    temp0 = temp1;
    double d1 = temp0 + 0.5*totalvol;
    double d1b = 0.0;
    double d1d0 = temp0d + 0.5*totalvold0;
    double d1d0b = 0.0;
    pushReal8(temp1);
    temp1 = (Sd-temp*Kd)/(temp*K);
    temp2 = (temp1-temp0*totalvold)/totalvol;
    double d1d = temp2 + 0.5*totalvold;
    double d1db = 0.0;
    double d1dd = ((Sdd-Kd*tempd-temp*Kdd-temp1*(K*tempd+temp*Kd0))/(temp*K)-
    totalvold*temp0d-temp0*totalvoldd-temp2*totalvold0)/totalvol + 0.5*
    totalvoldd;
    double d1ddb = 0.0;
    double d2 = d1 - totalvol;
    double d2b = 0.0;
    double d2d0 = d1d0 - totalvold0;
    double d2d0b = 0.0;
    double d2d = d1d - totalvold;
    double d2db = 0.0;
    double d2dd = d1dd - totalvoldd;
    double d2ddb = 0.0;
    pushReal8(result1dd);
    pushReal8(result1d);
    pushReal8(result1d0);
    pushReal8(result1);
    result1dd = cdf_n_d_d_nodiff(d1, d1d0, d1d, d1dd, &result1, &result1d0, &
                                 result1d);
    result2d0 = 0.0;
    result2dd = cdf_n_d_d_nodiff(d2, d2d0, d2d, d2dd, &result2, &result2d0, &
                                 result2d);
    *Sdb = *Sdb + result1d0*call_price_d_db + result1*(*call_price_db);
    result1d0b = Sd*call_price_d_db + S*(*call_pricedb);
    result1b = Sdd*call_price_d_db + Sd*(*call_price_db) + S*(*call_priceb) + 
        Sd0*(*call_pricedb);
    *Sddb = *Sddb + result1*call_price_d_db;
    result1db = Sd0*call_price_d_db + S*(*call_price_db);
    *Sd0b = *Sd0b + result1d*call_price_d_db + result1*(*call_pricedb);
    *Sb = *Sb + result1dd*call_price_d_db + result1d*(*call_price_db) + 
        result1*(*call_priceb) + result1d0*(*call_pricedb);
    result1ddb = S*call_price_d_db;
    *Kdb = *Kdb - result2d0*call_price_d_db - result2*(*call_price_db);
    result2d0b = -(Kd*call_price_d_db) - K*(*call_pricedb);
    result2b = -(Kdd*call_price_d_db) - Kd*(*call_price_db) - K*(*call_priceb)
        - Kd0*(*call_pricedb);
    *Kddb = *Kddb - result2*call_price_d_db;
    result2db = -(Kd0*call_price_d_db) - K*(*call_price_db);
    *Kd0b = *Kd0b - result2d*call_price_d_db - result2*(*call_pricedb);
    *Kb = *Kb - result2dd*call_price_d_db - result2d*(*call_price_db) - 
        result2*(*call_priceb) - result2d0*(*call_pricedb);
    result2ddb = -(K*call_price_d_db);
    *call_price_db = 0.0;
    *call_priceb = 0.0;
    *call_pricedb = 0.0;
    d2b = 0.0;
    d2d0b = 0.0;
    d2db = 0.0;
    d2ddb = 0.0;
    cdf_n_d_d_b(d2, &d2b, d2d0, &d2d0b, d2d, &d2db, d2dd, &d2ddb, &result2, &
                result2b, &result2d0, &result2d0b, &result2d, &result2db, 
                result2ddb);
    popReal8(&result1);
    popReal8(&result1d0);
    popReal8(&result1d);
    popReal8(&result1dd);
    d1b = 0.0;
    d1d0b = 0.0;
    d1db = 0.0;
    d1ddb = 0.0;
    cdf_n_d_d_b(d1, &d1b, d1d0, &d1d0b, d1d, &d1db, d1dd, &d1ddb, &result1, &
                result1b, &result1d0, &result1d0b, &result1d, &result1db, 
                result1ddb);
    d1ddb = d1ddb + d2ddb;
    d1db = d1db + d2db;
    d1d0b = d1d0b + d2d0b;
    d1b = d1b + d2b;
    temp5 = K*tempd + temp*Kd0;
    temp3 = (Sdd-Kd*tempd-temp*Kdd-temp1*temp5)/(temp*K);
    tempb1 = d1ddb/totalvol;
    totalvolddb = 0.5*d1ddb - d2ddb - temp0*tempb1;
    totalvoldb = -d2db - temp0d*tempb1;
    totalvold0b = -d2d0b - temp2*tempb1;
    totalvolb = -d2b - (temp3-totalvold*temp0d-temp0*totalvoldd-temp2*
        totalvold0)*tempb1/totalvol;
    tempb0 = tempb1/(temp*K);
    temp0db = d1d0b - totalvold*tempb1;
    temp0b = -(totalvoldd*tempb1);
    temp2b = d1db - totalvold0*tempb1;
    *Sddb = *Sddb + tempb0;
    tempdb = -(Kd*tempb0);
    *Kddb = *Kddb - temp*tempb0;
    tempb2 = -(temp1*tempb0);
    tempb3 = -(temp3*tempb0);
    tempb1 = temp2b/totalvol;
    temp1b = tempb1 - temp5*tempb0;
    totalvoldb = totalvoldb + 0.5*d1db - temp0*tempb1;
    temp0b = temp0b + d1b - totalvold*tempb1;
    totalvolb = totalvolb - (temp1-temp0*totalvold)*tempb1/totalvol;
    popReal8(&temp1);
    tempb1 = temp1b/(temp*K);
    *Kdb = *Kdb - tempd*tempb0 - temp*tempb1;
    tempb = K*tempb3 - Kdd*tempb0 + Kd0*tempb2 - Kd*tempb1;
    *Sdb = *Sdb + tempb1;
    tempb0 = -((Sd-temp*Kd)*tempb1/(temp*K));
    *Kb = *Kb + temp*tempb3 + tempd*tempb2 + temp*tempb0;
    tempb1 = temp0db/totalvol;
    tempdb = tempdb + K*tempb2 + tempb1/temp;
    totalvold0b = totalvold0b + 0.5*d1d0b - temp1*tempb1;
    temp1b = temp0b - totalvold0*tempb1;
    tempb = tempb + K*tempb0 + temp1b/(temp*totalvol) - tempd*tempb1/(temp*
        temp);
    totalvolb = totalvolb + 0.5*d1b - (tempd/temp-temp1*totalvold0)*tempb1/
        totalvol - log(temp)*temp1b/(totalvol*totalvol);
    temp4 = S*Kd0/K;
    tempb0 = tempdb/K;
    *Sd0b = *Sd0b + tempb0;
    tempb1 = -(tempb0/K);
    *Kd0b = *Kd0b + temp*tempb2 + S*tempb1;
    popReal8(&temp);
    *Sb = *Sb + tempb/K + Kd0*tempb1;
    *Kb = *Kb - S*tempb/(K*K) - (Sd0-temp4)*tempb0/K - temp4*tempb1;
    *vb = *vb + result1*totalvolb + result1d0*totalvold0b + result1d*
        totalvoldb + result1dd*totalvolddb;
    result1b = result1b + v*totalvolb + vd0*totalvold0b + vd*totalvoldb + vdd*
        totalvolddb;
    *vd0b = *vd0b + result1*totalvold0b + result1d*totalvolddb;
    result1d0b = result1d0b + v*totalvold0b + vd*totalvolddb;
    *vdb = *vdb + result1*totalvoldb + result1d0*totalvolddb;
    result1db = result1db + v*totalvoldb + vd0*totalvolddb;
    *vddb = *vddb + result1*totalvolddb;
    result1ddb = v*totalvolddb;
    tempb0 = (T == 0.0 ? 0.0 : result1ddb/(2.0*temp));
    tempb = result1b - (Tdd-2.0*(temp1*tempd))*tempb0/temp;
    tempdb = result1d0b - temp1*2.0*tempb0;
    temp1b = (T == 0.0 ? -(tempd*2.0*tempb0) : result1db - tempd*2.0*tempb0);
    *Tddb = *Tddb + tempb0;
    tempb0 = temp1b/(2.0*temp);
    *Tdb = *Tdb + tempb0;
    tempb = tempb - Td*tempb0/temp;
    tempb0 = (T == 0.0 ? 0.0 : tempdb/(2.0*temp1));
    temp1b = tempb - Td0*tempb0/temp1;
    *Td0b = *Td0b + tempb0;
    if (!(T==0.0))
        *Tb = *Tb + temp1b/(2.0*sqrt(T));
}
