/*        Generated by TAPENADE     (INRIA, Ecuador team)
    Tapenade 3.16 (develop) - 25 Oct 2024 09:00
*/
/*        Generated by TAPENADE     (INRIA, Ecuador team)
    Tapenade 3.16 (develop) - 25 Oct 2024 09:00

        Generated by TAPENADE     (INRIA, Ecuador team)
    Tapenade 3.16 (develop) - 25 Oct 2024 09:00

        Generated by TAPENADE     (INRIA, Ecuador team)
    Tapenade 3.16 (develop) - 25 Oct 2024 09:00

        Generated by TAPENADE     (INRIA, Ecuador team)
    Tapenade 3.16 (develop) - 25 Oct 2024 09:00
*/
#include <math.h>
#include <stdio.h>

/*
  Differentiation of cdf_n_d_d_d_d in forward (tangent) mode:
   variations   of useful results: *cdf_ndd *cdf_nd0d *cdf_n_ddd
                *cdf_n_dd *cdf_nddd *cdf_n_d_dd *cdf_nd *cdf_n_d
                *cdf_nd0 *cdf_nd1 *cdf_n_d_d *cdf_n *cdf_n_dd0
                *cdf_ndd0 *cdf_n_d_d_d cdf_n_d_d_d_d
   with respect to varying inputs: *cdf_ndd *cdf_nd0d xdd0d xd0d
                *cdf_n_ddd *cdf_n_dd *cdf_nddd xdddd xddd xdd
                xd x *cdf_n_d_dd xd1d *cdf_nd *cdf_n_d *cdf_nd0
                xd0dd *cdf_nd1 *cdf_n_d_d *cdf_n *cdf_n_dd0 *cdf_ndd0
                xddd0 xdd0 xd0 xdd1 xd1 xd2 *cdf_n_d_d_d xd0d0
   Plus diff mem management of: cdf_ndd:in cdf_nd0d:in cdf_n_ddd:in
                cdf_n_dd:in cdf_nddd:in cdf_n_d_dd:in cdf_nd:in
                cdf_n_d:in cdf_nd0:in cdf_nd1:in cdf_n_d_d:in
                cdf_n:in cdf_n_dd0:in cdf_ndd0:in cdf_n_d_d_d:in


  Differentiation of cdf_n_d_d_d in forward (tangent) mode:
   variations   of useful results: *cdf_ndd *cdf_n_dd *cdf_nd
                *cdf_n_d *cdf_nd0 *cdf_n_d_d *cdf_n cdf_n_d_d_d
   with respect to varying inputs: *cdf_ndd xd0d *cdf_n_dd xddd
                xdd xd x *cdf_nd *cdf_n_d *cdf_nd0 *cdf_n_d_d
                *cdf_n xdd0 xd0 xd1
   Plus diff mem management of: cdf_ndd:in cdf_n_dd:in cdf_nd:in
                cdf_n_d:in cdf_nd0:in cdf_n_d_d:in cdf_n:in


  Differentiation of cdf_n_d_d in forward (tangent) mode:
   variations   of useful results: *cdf_nd *cdf_n_d cdf_n_d_d
                *cdf_n
   with respect to varying inputs: xdd xd x *cdf_nd *cdf_n_d *cdf_n
                xd0
   Plus diff mem management of: cdf_nd:in cdf_n_d:in cdf_n:in


  Differentiation of cdf_n_d in forward (tangent) mode:
   variations   of useful results: cdf_n_d *cdf_n
   with respect to varying inputs: xd x *cdf_n
   Plus diff mem management of: cdf_n:in


  Differentiation of cdf_n in forward (tangent) mode:
   variations   of useful results: cdf_n
   with respect to varying inputs: x
*/
double cdf_n_d_d_d_d_d(double x, double xd3, double xd2, double xd2d, double 
        xd1, double xd1d0, double xd1d, double xd1dd, double xd0, double xd0d1
        , double xd0d0, double xd0d0d, double xd0d, double xd0dd0, double 
        xd0dd, double xd0ddd, double xd, double xdd2, double xdd1, double 
        xdd1d, double xdd0, double xdd0d0, double xdd0d, double xdd0dd, double
        xdd, double xddd1, double xddd0, double xddd0d, double xddd, double 
        xdddd0, double xdddd, double xddddd, double *cdf_n, double *cdf_nd2, 
        double *cdf_nd1, double *cdf_nd1d, double *cdf_nd0, double *cdf_nd0d0,
        double *cdf_nd0d, double *cdf_nd0dd, double *cdf_nd, double *cdf_ndd1,
        double *cdf_ndd0, double *cdf_ndd0d, double *cdf_ndd, double *
        cdf_nddd0, double *cdf_nddd, double *cdf_ndddd, double *cdf_n_d, 
        double *cdf_n_dd1, double *cdf_n_dd0, double *cdf_n_dd0d, double *
        cdf_n_dd, double *cdf_n_ddd0, double *cdf_n_ddd, double *cdf_n_dddd, 
        double *cdf_n_d_d, double *cdf_n_d_dd0, double *cdf_n_d_dd, double *
        cdf_n_d_ddd, double *cdf_n_d_d_d, double *cdf_n_d_d_dd, double *
        cdf_n_d_d_d_d) {
    double arg1;
    double arg1d2;
    double arg1d1;
    double arg1d1d;
    double arg1d0;
    double arg1d0d0;
    double arg1d0d;
    double arg1d0dd;
    double arg1d;
    double arg1dd1;
    double arg1dd0;
    double arg1dd0d;
    double arg1dd;
    double arg1ddd0;
    double arg1ddd;
    double arg1dddd;
    double temp;
    double tempd1;
    double tempd0;
    double tempd0d;
    double tempd;
    double tempdd0;
    double tempdd;
    double tempddd;
    double arg10;
    double arg10d1;
    double arg10d0;
    double arg10d0d;
    double arg10d;
    double arg10dd0;
    double arg10dd;
    double arg10ddd;
    double temp0;
    double temp0d0;
    double temp0d;
    double temp0dd;
    double arg11;
    double arg11d0;
    double arg11d;
    double arg11dd;
    double temp1;
    double temp1d;
    double temp2;
    double temp2d;
    double temp3;
    double temp3d;
    double arg12;
    double arg12d;
    double temp4;
    double temp5;
    double temp6;
    double temp7;
    arg10ddd = -(0.70710678118654746*0.70710678118654746*2*(xd2*xd1d0+xd1*xd2d
        +xd1d*xd3+x*xd1dd));
    arg10dd = -(0.70710678118654746*0.70710678118654746*2*(xd1*xd2+x*xd1d));
    arg10dd0 = -(0.70710678118654746*0.70710678118654746*2*(xd1*xd3+x*xd1d0));
    arg10d = -(0.70710678118654746*0.70710678118654746*2*x*xd1);
    arg10d0d = -(0.70710678118654746*0.70710678118654746*2*(xd2*xd3+x*xd2d));
    arg10d0 = -(0.70710678118654746*0.70710678118654746*2*x*xd2);
    arg10d1 = -(0.70710678118654746*0.70710678118654746*2*x*xd3);
    arg10 = -(-(0.70710678118654746*x)*-(0.70710678118654746*x));
    temp4 = exp(arg10);
    temp0dd = arg10d0*exp(arg10)*arg10d1 + temp4*arg10d0d;
    temp0d = temp4*arg10d0;
    temp0d0 = exp(arg10)*arg10d1;
    temp0 = exp(arg10);
    temp1d = exp(arg10)*arg10d1;
    temp1 = exp(arg10);
    temp4 = exp(arg10);
    temp5 = xd0*arg10d*arg10d0;
    temp6 = arg10d*xd0d0 + xd0*arg10dd;
    *cdf_ndddd = 0.5*1.1283791671*0.70710678118654746*(temp4*(arg10d0*(arg10d*
        xd0d1+xd0*arg10dd0)+xd0*arg10d*arg10d0d)+temp5*exp(arg10)*arg10d1+
        temp6*temp1d+temp1*(xd0d0*arg10dd0+arg10d*xd0d0d+arg10dd*xd0d1+xd0*
        arg10ddd)+temp0d*xd0dd0+xd0d*temp0dd+xd0dd*temp0d0+temp0*xd0ddd);
    *cdf_nddd = 0.5*1.1283791671*0.70710678118654746*(temp5*temp4+temp1*temp6+
        xd0d*temp0d+temp0*xd0dd);
    *cdf_nddd0 = 0.5*1.1283791671*0.70710678118654746*(arg10d*(xd0*temp1d+
        temp1*xd0d1)+temp1*xd0*arg10dd0+xd0d*temp0d0+temp0*xd0dd0);
    *cdf_ndd = 0.70710678118654746*0.5*1.1283791671*(temp1*(xd0*arg10d)+temp0*
        xd0d);
    *cdf_ndd0d = 0.5*1.1283791671*0.70710678118654746*(temp0d*xd0d1+xd0*
        temp0dd+xd0d0*temp0d0+temp0*xd0d0d);
    *cdf_ndd0 = 0.70710678118654746*0.5*1.1283791671*(xd0*temp0d+temp0*xd0d0);
    *cdf_ndd1 = 0.70710678118654746*0.5*1.1283791671*(xd0*temp0d0+temp0*xd0d1)
    ;
    *cdf_nd = 1.1283791671*0.70710678118654746*0.5*(temp0*xd0);
    arg11dd = -(0.70710678118654746*0.70710678118654746*2*(xd2*xd3+x*xd2d));
    arg11d = -(0.70710678118654746*0.70710678118654746*2*x*xd2);
    arg11d0 = -(0.70710678118654746*0.70710678118654746*2*x*xd3);
    arg11 = -(-(0.70710678118654746*x)*-(0.70710678118654746*x));
    temp1d = exp(arg11)*arg11d0;
    temp1 = exp(arg11);
    temp6 = exp(arg11);
    *cdf_nd0dd = 0.70710678118654746*0.5*1.1283791671*(xd1*arg11d*exp(arg11)*
        arg11d0+temp6*(arg11d*xd1d0+xd1*arg11dd)+xd1d*temp1d+temp1*xd1dd);
    *cdf_nd0d = 0.70710678118654746*0.5*1.1283791671*(temp6*(xd1*arg11d)+temp1
        *xd1d);
    *cdf_nd0d0 = 0.70710678118654746*0.5*1.1283791671*(xd1*temp1d+temp1*xd1d0)
    ;
    *cdf_nd0 = 1.1283791671*0.70710678118654746*0.5*(temp1*xd1);
    arg12d = -(0.70710678118654746*0.70710678118654746*2*x*xd3);
    arg12 = -(-(0.70710678118654746*x)*-(0.70710678118654746*x));
    temp6 = exp(arg12);
    *cdf_nd1d = 1.1283791671*0.70710678118654746*0.5*(xd2*exp(arg12)*arg12d+
        temp6*xd2d);
    *cdf_nd1 = 1.1283791671*0.70710678118654746*0.5*(temp6*xd2);
    *cdf_nd2 = 0.5*1.1283791671*exp(-(-(0.70710678118654746*x)*-(
        0.70710678118654746*x)))*0.70710678118654746*xd3;
    *cdf_n = 0.5*erfc(x*-0.70710678118654746);
    arg1dddd = -(0.70710678118654746*0.70710678118654746*2*(xd0d0*xd1d0+xd1*
        xd0d0d+xd1d*xd0d1+xd0*xd1dd+xd2*xd0dd0+xd0d*xd2d+xd0dd*xd3+x*xd0ddd));
    arg1ddd = -(0.70710678118654746*0.70710678118654746*2*(xd1*xd0d0+xd0*xd1d+
        xd0d*xd2+x*xd0dd));
    arg1ddd0 = -(0.70710678118654746*0.70710678118654746*2*(xd1*xd0d1+xd0*
        xd1d0+xd0d*xd3+x*xd0dd0));
    arg1dd = -(0.70710678118654746*0.70710678118654746*2*(xd0*xd1+x*xd0d));
    arg1dd0d = -(0.70710678118654746*0.70710678118654746*2*(xd2*xd0d1+xd0*xd2d
        +xd0d0*xd3+x*xd0d0d));
    arg1dd0 = -(0.70710678118654746*0.70710678118654746*2*(xd0*xd2+x*xd0d0));
    arg1dd1 = -(0.70710678118654746*0.70710678118654746*2*(xd0*xd3+x*xd0d1));
    arg1d = -(0.70710678118654746*0.70710678118654746*2*x*xd0);
    arg1d0dd = -(0.70710678118654746*0.70710678118654746*2*(xd2*xd1d0+xd1*xd2d
        +xd1d*xd3+x*xd1dd));
    arg1d0d = -(0.70710678118654746*0.70710678118654746*2*(xd1*xd2+x*xd1d));
    arg1d0d0 = -(0.70710678118654746*0.70710678118654746*2*(xd1*xd3+x*xd1d0));
    arg1d0 = -(0.70710678118654746*0.70710678118654746*2*x*xd1);
    arg1d1d = -(0.70710678118654746*0.70710678118654746*2*(xd2*xd3+x*xd2d));
    arg1d1 = -(0.70710678118654746*0.70710678118654746*2*x*xd2);
    arg1d2 = -(0.70710678118654746*0.70710678118654746*2*x*xd3);
    arg1 = -(-(0.70710678118654746*x)*-(0.70710678118654746*x));
    temp1d = exp(arg1)*arg1d2;
    temp1 = exp(arg1);
    temp6 = exp(arg1);
    tempddd = arg1d0*arg1d1*exp(arg1)*arg1d2 + temp6*(arg1d1*arg1d0d0+arg1d0*
        arg1d1d) + arg1d0d*temp1d + temp1*arg1d0dd;
    tempdd = temp6*(arg1d0*arg1d1) + temp1*arg1d0d;
    tempdd0 = arg1d0*temp1d + temp1*arg1d0d0;
    tempd = temp1*arg1d0;
    temp6 = exp(arg1);
    tempd0d = arg1d1*exp(arg1)*arg1d2 + temp6*arg1d1d;
    tempd0 = temp6*arg1d1;
    tempd1 = exp(arg1)*arg1d2;
    temp = exp(arg1);
    *cdf_n_dddd = 1.1283791671*0.70710678118654746*0.5*(xdd1*tempdd0+tempd*
        xdd1d+tempdd*xdd2+xd*tempddd+tempd0*xdd0d0+xdd0*tempd0d+xdd0d*tempd1+
        temp*xdd0dd);
    *cdf_n_ddd = 0.5*1.1283791671*0.70710678118654746*(tempd*xdd1+xd*tempdd+
        xdd0*tempd0+temp*xdd0d);
    *cdf_n_ddd0 = 0.5*1.1283791671*0.70710678118654746*(tempd*xdd2+xd*tempdd0+
        xdd0*tempd1+temp*xdd0d0);
    *cdf_n_dd = 0.70710678118654746*0.5*1.1283791671*(xd*tempd+temp*xdd0);
    *cdf_n_dd0d = 0.5*1.1283791671*0.70710678118654746*(tempd0*xdd2+xd*tempd0d
        +xdd1*tempd1+temp*xdd1d);
    *cdf_n_dd0 = 0.70710678118654746*0.5*1.1283791671*(xd*tempd0+temp*xdd1);
    *cdf_n_dd1 = 0.70710678118654746*0.5*1.1283791671*(xd*tempd1+temp*xdd2);
    *cdf_n_d = 1.1283791671*0.70710678118654746*0.5*(temp*xd);
    temp6 = exp(arg1);
    temp0dd = arg1d1*exp(arg1)*arg1d2 + temp6*arg1d1d;
    temp0d = temp6*arg1d1;
    temp0d0 = exp(arg1)*arg1d2;
    temp0 = exp(arg1);
    temp6 = xd*temp0d + temp0*xdd1;
    *cdf_n_d_ddd = 1.1283791671*0.70710678118654746*0.5*(temp6*arg1dd1+arg1d*(
        temp0d*xdd2+xd*temp0dd+xdd1*temp0d0+temp0*xdd1d)+arg1dd0*(xd*temp0d0+
        temp0*xdd2)+temp0*xd*arg1dd0d+tempd0*xddd1+xdd*tempd0d+xddd0*tempd1+
        temp*xddd0d);
    *cdf_n_d_dd = 1.1283791671*0.70710678118654746*0.5*(arg1d*temp6+temp0*xd*
        arg1dd0+xdd*tempd0+temp*xddd0);
    *cdf_n_d_dd0 = 0.5*1.1283791671*0.70710678118654746*(arg1d*(xd*temp0d0+
        temp0*xdd2)+temp0*xd*arg1dd1+xdd*tempd1+temp*xddd1);
    *cdf_n_d_d = 0.70710678118654746*0.5*1.1283791671*(temp0*(xd*arg1d)+temp*
        xdd);
    temp1d = exp(arg1)*arg1d2;
    temp1 = exp(arg1);
    temp2d = arg1d0*(arg1d*xdd2+xd*arg1dd1) + xd*arg1d*arg1d0d0;
    temp2 = xd*arg1d*arg1d0;
    temp3d = xdd0*arg1dd1 + arg1d*xdd0d0 + arg1dd*xdd2 + xd*arg1ddd0;
    temp3 = arg1d*xdd0 + xd*arg1dd;
    *cdf_n_d_d_dd = 1.1283791671*0.70710678118654746*0.5*(temp1*temp2d+temp2*
        temp1d+temp3*temp0d0+temp0*temp3d+tempd*xddd1+xdd*tempdd0+xddd*tempd1+
        temp*xdddd0);
    *cdf_n_d_d_d = 0.5*1.1283791671*0.70710678118654746*(temp2*temp1+temp0*
        temp3+xdd*tempd+temp*xddd);
    temp6 = arg1d*xdd1 + xd*arg1dd0;
    temp5 = arg1d0*temp6 + xd*arg1d*arg1d0d;
    temp4 = exp(arg1);
    temp7 = xdd0*arg1dd0 + arg1d*xdd0d + arg1dd*xdd1 + xd*arg1ddd;
    *cdf_n_d_d_d_d = 1.1283791671*0.70710678118654746*0.5*(temp1*temp5+temp4*(
        temp2*arg1d1)+temp3*temp0d+temp0*temp7+tempd*xddd0+xdd*tempdd+xddd*
        tempd0+temp*xdddd);
    return 1.1283791671*0.70710678118654746*0.5*(temp5*temp1d+temp1*(temp6*
    arg1d0d0+arg1d0*(xdd1*arg1dd1+arg1d*xdd1d+arg1dd0*xdd2+xd*arg1dd0d)+
    arg1d0d*(arg1d*xdd2+xd*arg1dd1)+xd*arg1d*arg1d0dd)+temp2*arg1d1*exp(arg1)*
    arg1d2+temp4*(arg1d1*temp2d+temp2*arg1d1d)+temp0d*temp3d+temp3*temp0dd+
    temp7*temp0d0+temp0*(arg1dd0*xdd0d0+xdd0*arg1dd0d+xdd0d*arg1dd1+arg1d*
    xdd0dd+xdd1*arg1ddd0+arg1dd*xdd1d+arg1ddd*xdd2+xd*arg1dddd)+xddd0*tempdd0+
    tempd*xddd0d+tempdd*xddd1+xdd*tempddd+tempd0*xdddd0+xddd*tempd0d+xdddd*
    tempd1+temp*xddddd);
}

/*
  Differentiation of call_price_d_d_d_d in forward (tangent) mode:
   variations   of useful results: *call_price_d_dd *call_priced0d
                *call_price_dd *call_price_ddd *call_priceddd
                *call_price_d *call_priced0 *call_priced1 *call_price
                *call_price_d_d_d *call_priced call_price_d_d_d_d
                *call_price_d_d *call_price_dd0 *call_pricedd0
                *call_pricedd
   with respect to varying inputs: Sdd0 Sdd1 Kd0dd Td vd0dd *call_price_d_dd
                Sd0 Tddd0 Sd1 Kd0d Sd2 v Sd0d0 Kddd0 Kd0 *call_priced0d
                Tdd Kd1 Kddd Kd Kd2 vddd0 vd0d *call_price_dd
                Sdd0d Td0d *call_price_ddd *call_priceddd vddd
                Td0d0 *call_price_d Sd0d Sdddd *call_priced0 Tddd
                Kd1d *call_priced1 vd0 vd1 vd2 Kd0d0 *call_price
                Tdd0d Sddd vd0d0 vd1d vd Td1d Kdd0d Sdd Tdddd
                vdd0d *call_price_d_d_d *call_priced Sd0dd Td0
                Sd1d Td1 Kdd0 Sd Td2 Kdd1 Kdddd Kdd K *call_price_d_d
                vdddd *call_price_dd0 S *call_pricedd0 T vdd0
                vdd1 Sddd0 Tdd0 Td0dd Tdd1 *call_pricedd vdd
   RW status of diff variables: Sdd0:in Sdd1:in Kd0dd:in Td:in
                vd0dd:in call_price_d_dd:(loc) *call_price_d_dd:in-out
                Sd0:in Tddd0:in Sd1:in Kd0d:in Sd2:in v:in Sd0d0:in
                Kddd0:in Kd0:in call_priced0d:(loc) *call_priced0d:in-out
                Tdd:in Kd1:in Kddd:in Kd:in Kd2:in vddd0:in vd0d:in
                call_price_dd:(loc) *call_price_dd:in-out Sdd0d:in
                Td0d:in call_price_ddd:(loc) *call_price_ddd:in-out
                call_priceddd:(loc) *call_priceddd:in-out vddd:in
                Td0d0:in call_price_d:(loc) *call_price_d:in-out
                Sd0d:in Sdddd:in call_priced0:(loc) *call_priced0:in-out
                Tddd:in Kd1d:in call_priced1:(loc) *call_priced1:in-out
                vd0:in vd1:in vd2:in Kd0d0:in call_price:(loc)
                *call_price:in-out Tdd0d:in Sddd:in vd0d0:in vd1d:in
                vd:in Td1d:in Kdd0d:in Sdd:in Tdddd:in vdd0d:in
                call_price_d_d_d:(loc) *call_price_d_d_d:in-out
                call_priced:(loc) *call_priced:in-out Sd0dd:in
                Td0:in Sd1d:in Td1:in Kdd0:in Sd:in Td2:in Kdd1:in
                Kdddd:in Kdd:in K:in call_price_d_d_d_d:out call_price_d_d:(loc)
                *call_price_d_d:in-out vdddd:in call_price_dd0:(loc)
                *call_price_dd0:in-out S:in call_pricedd0:(loc)
                *call_pricedd0:in-out T:in vdd0:in vdd1:in Sddd0:in
                Tdd0:in Td0dd:in Tdd1:in call_pricedd:(loc) *call_pricedd:in-out
                vdd:in
   Plus diff mem management of: call_price_d_dd:in call_priced0d:in
                call_price_dd:in call_price_ddd:in call_priceddd:in
                call_price_d:in call_priced0:in call_priced1:in
                call_price:in call_price_d_d_d:in call_priced:in
                call_price_d_d:in call_price_dd0:in call_pricedd0:in
                call_pricedd:in


  Differentiation of call_price_d_d_d in forward (tangent) mode:
   variations   of useful results: *call_price_dd *call_price_d
                *call_priced0 *call_price call_price_d_d_d *call_priced
                *call_price_d_d *call_pricedd
   with respect to varying inputs: Sdd0 Td Sd0 Sd1 Kd0d v Kd0
                Tdd Kd1 Kddd Kd vd0d *call_price_dd Td0d vddd
                *call_price_d Sd0d *call_priced0 Tddd vd0 vd1
                *call_price Sddd vd Sdd *call_priced Td0 Td1 Kdd0
                Sd Kdd K *call_price_d_d S T vdd0 Tdd0 *call_pricedd
                vdd
   RW status of diff variables: Sdd0:in Td:in Sd0:in Sd1:in Kd0d:in
                v:in Kd0:in Tdd:in Kd1:in Kddd:in Kd:in vd0d:in
                call_price_dd:(loc) *call_price_dd:in-out Td0d:in
                vddd:in call_price_d:(loc) *call_price_d:in-out
                Sd0d:in call_priced0:(loc) *call_priced0:in-out
                Tddd:in vd0:in vd1:in call_price:(loc) *call_price:in-out
                Sddd:in vd:in Sdd:in call_price_d_d_d:out call_priced:(loc)
                *call_priced:in-out Td0:in Td1:in Kdd0:in Sd:in
                Kdd:in K:in call_price_d_d:(loc) *call_price_d_d:in-out
                S:in T:in vdd0:in Tdd0:in call_pricedd:(loc) *call_pricedd:in-out
                vdd:in
   Plus diff mem management of: call_price_dd:in call_price_d:in
                call_priced0:in call_price:in call_priced:in call_price_d_d:in
                call_pricedd:in


  Differentiation of call_price_d_d in forward (tangent) mode:
   variations   of useful results: *call_price_d *call_price *call_priced
                call_price_d_d
   with respect to varying inputs: Td Sd0 v Kd0 Tdd Kd *call_price_d
                vd0 *call_price vd Sdd *call_priced Td0 Sd Kdd
                K S T vdd
   RW status of diff variables: Td:in Sd0:in v:in Kd0:in Tdd:in
                Kd:in call_price_d:(loc) *call_price_d:in-out
                vd0:in call_price:(loc) *call_price:in-out vd:in
                Sdd:in call_priced:(loc) *call_priced:in-out Td0:in
                Sd:in Kdd:in K:in call_price_d_d:out S:in T:in
                vdd:in
   Plus diff mem management of: call_price_d:in call_price:in
                call_priced:in


  Differentiation of call_price_d in forward (tangent) mode:
   variations   of useful results: call_price_d *call_price
   with respect to varying inputs: Td v Kd *call_price vd Sd K
                S T
   RW status of diff variables: Td:in v:in Kd:in call_price_d:out
                call_price:(loc) *call_price:in-out vd:in Sd:in
                K:in S:in T:in
   Plus diff mem management of: call_price:in


  Differentiation of call_price in forward (tangent) mode:
   variations   of useful results: call_price
   with respect to varying inputs: v K S T
   RW status of diff variables: v:in call_price:out K:in S:in
                T:in
*/
double call_price_d_d_d_d_d(double S, double Sd3, double Sd2, double Sd2d, 
        double Sd1, double Sd1d0, double Sd1d, double Sd1dd, double Sd0, 
        double Sd0d1, double Sd0d0, double Sd0d0d, double Sd0d, double Sd0dd0,
        double Sd0dd, double Sd0ddd, double Sd, double Sdd2, double Sdd1, 
        double Sdd1d, double Sdd0, double Sdd0d0, double Sdd0d, double Sdd0dd,
        double Sdd, double Sddd1, double Sddd0, double Sddd0d, double Sddd, 
        double Sdddd0, double Sdddd, double Sddddd, double K, double Kd3, 
        double Kd2, double Kd2d, double Kd1, double Kd1d0, double Kd1d, double
        Kd1dd, double Kd0, double Kd0d1, double Kd0d0, double Kd0d0d, double 
        Kd0d, double Kd0dd0, double Kd0dd, double Kd0ddd, double Kd, double 
        Kdd2, double Kdd1, double Kdd1d, double Kdd0, double Kdd0d0, double 
        Kdd0d, double Kdd0dd, double Kdd, double Kddd1, double Kddd0, double 
        Kddd0d, double Kddd, double Kdddd0, double Kdddd, double Kddddd, 
        double v, double vd3, double vd2, double vd2d, double vd1, double 
        vd1d0, double vd1d, double vd1dd, double vd0, double vd0d1, double 
        vd0d0, double vd0d0d, double vd0d, double vd0dd0, double vd0dd, double
        vd0ddd, double vd, double vdd2, double vdd1, double vdd1d, double vdd0
        , double vdd0d0, double vdd0d, double vdd0dd, double vdd, double vddd1
        , double vddd0, double vddd0d, double vddd, double vdddd0, double 
        vdddd, double vddddd, double T, double Td3, double Td2, double Td2d, 
        double Td1, double Td1d0, double Td1d, double Td1dd, double Td0, 
        double Td0d1, double Td0d0, double Td0d0d, double Td0d, double Td0dd0,
        double Td0dd, double Td0ddd, double Td, double Tdd2, double Tdd1, 
        double Tdd1d, double Tdd0, double Tdd0d0, double Tdd0d, double Tdd0dd,
        double Tdd, double Tddd1, double Tddd0, double Tddd0d, double Tddd, 
        double Tdddd0, double Tdddd, double Tddddd, double *call_price, double
        *call_priced2, double *call_priced1, double *call_priced1d, double *
        call_priced0, double *call_priced0d0, double *call_priced0d, double *
        call_priced0dd, double *call_priced, double *call_pricedd1, double *
        call_pricedd0, double *call_pricedd0d, double *call_pricedd, double *
        call_priceddd0, double *call_priceddd, double *call_pricedddd, double 
        *call_price_d, double *call_price_dd1, double *call_price_dd0, double 
        *call_price_dd0d, double *call_price_dd, double *call_price_ddd0, 
        double *call_price_ddd, double *call_price_dddd, double *
        call_price_d_d, double *call_price_d_dd0, double *call_price_d_dd, 
        double *call_price_d_ddd, double *call_price_d_d_d, double *
        call_price_d_d_dd, double *call_price_d_d_d_d) {
    double totalvol;
    double totalvold3;
    double totalvold2;
    double totalvold2d;
    double totalvold1;
    double totalvold1d0;
    double totalvold1d;
    double totalvold1dd;
    double totalvold0;
    double totalvold0d1;
    double totalvold0d0;
    double totalvold0d0d;
    double totalvold0d;
    double totalvold0dd0;
    double totalvold0dd;
    double totalvold0ddd;
    double totalvold;
    double totalvoldd2;
    double totalvoldd1;
    double totalvoldd1d;
    double totalvoldd0;
    double totalvoldd0d0;
    double totalvoldd0d;
    double totalvoldd0dd;
    double totalvoldd;
    double totalvolddd1;
    double totalvolddd0;
    double totalvolddd0d;
    double totalvolddd;
    double totalvoldddd0;
    double totalvoldddd;
    double totalvolddddd;
    double result1;
    double result1d3;
    double result1d2;
    double result1d2d;
    double result1d1;
    double result1d1d0;
    double result1d1d;
    double result1d1dd;
    double result1d0;
    double result1d0d1;
    double result1d0d0;
    double result1d0d0d;
    double result1d0d;
    double result1d0dd0;
    double result1d0dd;
    double result1d0ddd;
    double result1d;
    double result1dd2;
    double result1dd1;
    double result1dd1d;
    double result1dd0;
    double result1dd0d0;
    double result1dd0d;
    double result1dd0dd;
    double result1dd;
    double result1ddd1;
    double result1ddd0;
    double result1ddd0d;
    double result1ddd;
    double result1dddd0;
    double result1dddd;
    double result1ddddd;
    double result2;
    double result2d3;
    double result2d2;
    double result2d2d;
    double result2d1;
    double result2d1d0;
    double result2d1d;
    double result2d1dd;
    double result2d0;
    double result2d0d1;
    double result2d0d0;
    double result2d0d0d;
    double result2d0d;
    double result2d0dd0;
    double result2d0dd;
    double result2d0ddd;
    double result2d;
    double result2dd2;
    double result2dd1;
    double result2dd1d;
    double result2dd0;
    double result2dd0d0;
    double result2dd0d;
    double result2dd0dd;
    double result2dd;
    double result2ddd1;
    double result2ddd0;
    double result2ddd0d;
    double result2ddd;
    double result2dddd0;
    double result2dddd;
    double result2ddddd;
    double temp;
    double tempd2;
    double tempd1;
    double tempd1d;
    double tempd0;
    double tempd0d0;
    double tempd0d;
    double tempd0dd;
    double tempd;
    double tempdd1;
    double tempdd0;
    double tempdd0d;
    double tempdd;
    double tempddd0;
    double tempddd;
    double tempdddd;
    double temp0;
    double temp0d2;
    double temp0d1;
    double temp0d1d;
    double temp0d0;
    double temp0d0d0;
    double temp0d0d;
    double temp0d0dd;
    double temp0d;
    double temp0dd1;
    double temp0dd0;
    double temp0dd0d;
    double temp0dd;
    double temp0ddd0;
    double temp0ddd;
    double temp0dddd;
    double temp1;
    double temp1d1;
    double temp1d0;
    double temp1d0d;
    double temp1d;
    double temp1dd0;
    double temp1dd;
    double temp1ddd;
    double temp2;
    double temp2d1;
    double temp2d0;
    double temp2d0d;
    double temp2d;
    double temp2dd0;
    double temp2dd;
    double temp2ddd;
    double temp3;
    double temp3d0;
    double temp3d;
    double temp3dd;
    double temp4;
    double temp4d0;
    double temp4d;
    double temp4dd;
    double temp5;
    double temp5d0;
    double temp5d;
    double temp5dd;
    double temp6;
    double temp6d;
    double temp7;
    double temp7d;
    double temp8;
    double temp8d;
    double temp9;
    double temp9d;
    double temp10;
    double temp11;
    double temp12;
    double temp13;
    double temp14;
    temp10 = sqrt(T);
    temp6d = (T == 0.0 ? 0.0 : Td3/(2.0*temp10));
    temp6 = temp10;
    temp10 = Td2/(2.0*temp6);
    temp3dd = (T == 0.0 ? 0.0 : (Td2d-temp10*2.0*temp6d)/(2.0*temp6));
    temp3d = (T == 0.0 ? 0.0 : temp10);
    temp3d0 = temp6d;
    temp3 = temp6;
    temp10 = Td1/(2.0*temp3);
    temp6d = (Td1d0-temp10*2.0*temp3d0)/(2.0*temp3);
    temp6 = temp10;
    temp10 = (Td1d-2.0*temp6*temp3d)/(2.0*temp3);
    temp1ddd = (T == 0.0 ? 0.0 : (Td1dd-2.0*(temp3d*temp6d+temp6*temp3dd)-
        temp10*2.0*temp3d0)/(2.0*temp3));
    temp1dd = (T == 0.0 ? 0.0 : temp10);
    temp1dd0 = (T == 0.0 ? 0.0 : temp6d);
    temp1d = (T == 0.0 ? 0.0 : temp6);
    temp1d0d = temp3dd;
    temp1d0 = temp3d;
    temp1d1 = temp3d0;
    temp1 = temp3;
    temp10 = Td0/(2.0*temp1);
    temp6d = (Td0d1-temp10*2.0*temp1d1)/(2.0*temp1);
    temp6 = temp10;
    temp10 = (Td0d0-2.0*temp6*temp1d0)/(2.0*temp1);
    temp3dd = (Td0d0d-2.0*(temp1d0*temp6d+temp6*temp1d0d)-temp10*2.0*temp1d1)/
        (2.0*temp1);
    temp3d = temp10;
    temp3d0 = temp6d;
    temp3 = temp6;
    temp10 = (Td0d-2.0*temp3*temp1d)/(2.0*temp1);
    temp6d = (Td0dd0-2.0*(temp1d*temp3d0+temp3*temp1dd0)-temp10*2.0*temp1d1)/(
        2.0*temp1);
    temp6 = temp10;
    temp10 = (Td0dd-2.0*(temp1d*temp3d+temp3*temp1dd)-2.0*temp6*temp1d0)/(2.0*
        temp1);
    tempdddd = (T == 0.0 ? 0.0 : (Td0ddd-2.0*(temp3d*temp1dd0+temp1d*temp3dd+
        temp1dd*temp3d0+temp3*temp1ddd)-2.0*(temp1d0*temp6d+temp6*temp1d0d)-
        temp10*2.0*temp1d1)/(2.0*temp1));
    tempddd = (T == 0.0 ? 0.0 : temp10);
    tempddd0 = (T == 0.0 ? 0.0 : temp6d);
    tempdd = (T == 0.0 ? 0.0 : temp6);
    tempdd0d = (T == 0.0 ? 0.0 : temp3dd);
    tempdd0 = (T == 0.0 ? 0.0 : temp3d);
    tempdd1 = (T == 0.0 ? 0.0 : temp3d0);
    tempd = (T == 0.0 ? 0.0 : temp3);
    tempd0dd = temp1ddd;
    tempd0d = temp1dd;
    tempd0d0 = temp1dd0;
    tempd0 = temp1d;
    tempd1d = temp1d0d;
    tempd1 = temp1d0;
    tempd2 = temp1d1;
    temp = temp1;
    temp10 = Td/(2.0*temp);
    temp6d = (Tdd2-temp10*2.0*tempd2)/(2.0*temp);
    temp6 = temp10;
    temp10 = (Tdd1-2.0*temp6*tempd1)/(2.0*temp);
    temp3dd = (Tdd1d-2.0*(tempd1*temp6d+temp6*tempd1d)-temp10*2.0*tempd2)/(2.0
        *temp);
    temp3d = temp10;
    temp3d0 = temp6d;
    temp3 = temp6;
    temp10 = (Tdd0-2.0*temp3*tempd0)/(2.0*temp);
    temp6d = (Tdd0d0-2.0*(tempd0*temp3d0+temp3*tempd0d0)-temp10*2.0*tempd2)/(
        2.0*temp);
    temp6 = temp10;
    temp10 = (Tdd0d-2.0*(tempd0*temp3d+temp3*tempd0d)-2.0*temp6*tempd1)/(2.0*
        temp);
    temp1ddd = (Tdd0dd-2.0*(temp3d*tempd0d0+tempd0*temp3dd+tempd0d*temp3d0+
        temp3*tempd0dd)-2.0*(tempd1*temp6d+temp6*tempd1d)-temp10*2.0*tempd2)/(
        2.0*temp);
    temp1dd = temp10;
    temp1dd0 = temp6d;
    temp1d = temp6;
    temp1d0d = temp3dd;
    temp1d0 = temp3d;
    temp1d1 = temp3d0;
    temp1 = temp3;
    temp10 = (Tdd-2.0*temp1*tempd)/(2.0*temp);
    temp6d = (Tddd1-2.0*(tempd*temp1d1+temp1*tempdd1)-temp10*2.0*tempd2)/(2.0*
        temp);
    temp6 = temp10;
    temp10 = (Tddd0-2.0*(tempd*temp1d0+temp1*tempdd0)-2.0*temp6*tempd1)/(2.0*
        temp);
    temp3dd = (Tddd0d-2.0*(temp1d0*tempdd1+tempd*temp1d0d+tempdd0*temp1d1+
        temp1*tempdd0d)-2.0*(tempd1*temp6d+temp6*tempd1d)-temp10*2.0*tempd2)/(
        2.0*temp);
    temp3d = temp10;
    temp3d0 = temp6d;
    temp3 = temp6;
    temp10 = (Tddd-2.0*(tempd*temp1d+temp1*tempdd)-2.0*temp3*tempd0)/(2.0*temp
        );
    temp6d = (Tdddd0-2.0*(temp1d*tempdd1+tempd*temp1dd0+tempdd*temp1d1+temp1*
        tempddd0)-2.0*(tempd0*temp3d0+temp3*tempd0d0)-temp10*2.0*tempd2)/(2.0*
        temp);
    temp6 = temp10;
    temp10 = (Tdddd-2.0*(temp1d*tempdd0+tempd*temp1dd+tempdd*temp1d0+temp1*
        tempddd)-2.0*(tempd0*temp3d+temp3*tempd0d)-2.0*temp6*tempd1)/(2.0*temp
        );
    result1ddddd = (T == 0.0 ? 0.0 : (Tddddd-2.0*(tempdd0*temp1dd0+temp1d*
        tempdd0d+temp1dd*tempdd1+tempd*temp1ddd+temp1d0*tempddd0+tempdd*
        temp1d0d+tempddd*temp1d1+temp1*tempdddd)-2.0*(temp3d*tempd0d0+tempd0*
        temp3dd+tempd0d*temp3d0+temp3*tempd0dd)-2.0*(tempd1*temp6d+temp6*
        tempd1d)-temp10*2.0*tempd2)/(2.0*temp));
    result1dddd = (T == 0.0 ? 0.0 : temp10);
    result1dddd0 = (T == 0.0 ? 0.0 : temp6d);
    result1ddd = (T == 0.0 ? 0.0 : temp6);
    result1ddd0d = (T == 0.0 ? 0.0 : temp3dd);
    result1ddd0 = (T == 0.0 ? 0.0 : temp3d);
    result1ddd1 = (T == 0.0 ? 0.0 : temp3d0);
    result1dd = (T == 0.0 ? 0.0 : temp3);
    result1dd0dd = (T == 0.0 ? 0.0 : temp1ddd);
    result1dd0d = (T == 0.0 ? 0.0 : temp1dd);
    result1dd0d0 = (T == 0.0 ? 0.0 : temp1dd0);
    result1dd0 = (T == 0.0 ? 0.0 : temp1d);
    result1dd1d = (T == 0.0 ? 0.0 : temp1d0d);
    result1dd1 = (T == 0.0 ? 0.0 : temp1d0);
    result1dd2 = (T == 0.0 ? 0.0 : temp1d1);
    result1d = (T == 0.0 ? 0.0 : temp1);
    result1d0ddd = tempdddd;
    result1d0dd = tempddd;
    result1d0dd0 = tempddd0;
    result1d0d = tempdd;
    result1d0d0d = tempdd0d;
    result1d0d0 = tempdd0;
    result1d0d1 = tempdd1;
    result1d0 = tempd;
    result1d1dd = tempd0dd;
    result1d1d = tempd0d;
    result1d1d0 = tempd0d0;
    result1d1 = tempd0;
    result1d2d = tempd1d;
    result1d2 = tempd1;
    result1d3 = tempd2;
    result1 = temp;
    totalvolddddd = result1d0d0*vdd0d0 + vdd0*result1d0d0d + vdd0d*result1d0d1
        + result1d0*vdd0dd + vdd1*result1d0dd0 + result1d0d*vdd1d + 
        result1d0dd*vdd2 + vd*result1d0ddd + vddd0*result1d1d0 + result1d1*
        vddd0d + result1d1d*vddd1 + vdd*result1d1dd + result1d2*vdddd0 + vddd*
        result1d2d + vdddd*result1d3 + result1*vddddd + vd0d0*result1dd0d0 + 
        result1dd0*vd0d0d + result1dd0d*vd0d1 + vd0*result1dd0dd + result1dd1*
        vd0dd0 + vd0d*result1dd1d + vd0dd*result1dd2 + result1d*vd0ddd + 
        result1ddd0*vd1d0 + vd1*result1ddd0d + vd1d*result1ddd1 + result1dd*
        vd1dd + vd2*result1dddd0 + result1ddd*vd2d + result1dddd*vd3 + v*
        result1ddddd;
    totalvoldddd = vdd0*result1d0d0 + result1d0*vdd0d + result1d0d*vdd1 + vd*
        result1d0dd + result1d1*vddd0 + vdd*result1d1d + vddd*result1d2 + 
        result1*vdddd + result1dd0*vd0d0 + vd0*result1dd0d + vd0d*result1dd1 +
        result1d*vd0dd + vd1*result1ddd0 + result1dd*vd1d + result1ddd*vd2 + v
        *result1dddd;
    totalvoldddd0 = vdd0*result1d0d1 + result1d0*vdd0d0 + result1d0d*vdd2 + vd
        *result1d0dd0 + result1d1*vddd1 + vdd*result1d1d0 + vddd*result1d3 + 
        result1*vdddd0 + result1dd0*vd0d1 + vd0*result1dd0d0 + vd0d*result1dd2
        + result1d*vd0dd0 + vd1*result1ddd1 + result1dd*vd1d0 + result1ddd*vd3
        + v*result1dddd0;
    totalvolddd = result1d0*vdd0 + vd*result1d0d + vdd*result1d1 + result1*
        vddd + vd0*result1dd0 + result1d*vd0d + result1dd*vd1 + v*result1ddd;
    totalvolddd0d = vdd1*result1d0d1 + result1d0*vdd1d + result1d0d0*vdd2 + vd
        *result1d0d0d + result1d2*vddd1 + vdd*result1d2d + vddd0*result1d3 + 
        result1*vddd0d + result1dd1*vd0d1 + vd0*result1dd1d + vd0d0*result1dd2
        + result1d*vd0d0d + vd2*result1ddd1 + result1dd*vd2d + result1ddd0*vd3
        + v*result1ddd0d;
    totalvolddd0 = result1d0*vdd1 + vd*result1d0d0 + vdd*result1d2 + result1*
        vddd0 + vd0*result1dd1 + result1d*vd0d0 + result1dd*vd2 + v*
        result1ddd0;
    totalvolddd1 = result1d0*vdd2 + vd*result1d0d1 + vdd*result1d3 + result1*
        vddd1 + vd0*result1dd2 + result1d*vd0d1 + result1dd*vd3 + v*
        result1ddd1;
    totalvoldd = vd*result1d0 + result1*vdd + result1d*vd0 + v*result1dd;
    totalvoldd0dd = vdd1*result1d1d0 + result1d1*vdd1d + result1d1d*vdd2 + vd*
        result1d1dd + result1d2*vdd0d0 + vdd0*result1d2d + vdd0d*result1d3 + 
        result1*vdd0dd + result1dd1*vd1d0 + vd1*result1dd1d + vd1d*result1dd2 
        + result1d*vd1dd + vd2*result1dd0d0 + result1dd0*vd2d + result1dd0d*
        vd3 + v*result1dd0dd;
    totalvoldd0d = result1d1*vdd1 + vd*result1d1d + vdd0*result1d2 + result1*
        vdd0d + vd1*result1dd1 + result1d*vd1d + result1dd0*vd2 + v*
        result1dd0d;
    totalvoldd0d0 = result1d1*vdd2 + vd*result1d1d0 + vdd0*result1d3 + result1
        *vdd0d0 + vd1*result1dd2 + result1d*vd1d0 + result1dd0*vd3 + v*
        result1dd0d0;
    totalvoldd0 = vd*result1d1 + result1*vdd0 + result1d*vd1 + v*result1dd0;
    totalvoldd1d = result1d2*vdd2 + vd*result1d2d + vdd1*result1d3 + result1*
        vdd1d + vd2*result1dd2 + result1d*vd2d + result1dd1*vd3 + v*
        result1dd1d;
    totalvoldd1 = vd*result1d2 + result1*vdd1 + result1d*vd2 + v*result1dd1;
    totalvoldd2 = vd*result1d3 + result1*vdd2 + result1d*vd3 + v*result1dd2;
    totalvold = result1*vd + v*result1d;
    totalvold0ddd = vd0d0*result1d1d0 + result1d1*vd0d0d + result1d1d*vd0d1 + 
        vd0*result1d1dd + result1d2*vd0dd0 + vd0d*result1d2d + vd0dd*result1d3
        + result1*vd0ddd + result1d0d0*vd1d0 + vd1*result1d0d0d + vd1d*
        result1d0d1 + result1d0*vd1dd + vd2*result1d0dd0 + result1d0d*vd2d + 
        result1d0dd*vd3 + v*result1d0ddd;
    totalvold0dd = result1d1*vd0d0 + vd0*result1d1d + vd0d*result1d2 + result1
        *vd0dd + vd1*result1d0d0 + result1d0*vd1d + result1d0d*vd2 + v*
        result1d0dd;
    totalvold0dd0 = result1d1*vd0d1 + vd0*result1d1d0 + vd0d*result1d3 + 
        result1*vd0dd0 + vd1*result1d0d1 + result1d0*vd1d0 + result1d0d*vd3 + 
        v*result1d0dd0;
    totalvold0d = vd0*result1d1 + result1*vd0d + result1d0*vd1 + v*result1d0d;
    totalvold0d0d = result1d2*vd0d1 + vd0*result1d2d + vd0d0*result1d3 + 
        result1*vd0d0d + vd2*result1d0d1 + result1d0*vd2d + result1d0d0*vd3 + 
        v*result1d0d0d;
    totalvold0d0 = vd0*result1d2 + result1*vd0d0 + result1d0*vd2 + v*
        result1d0d0;
    totalvold0d1 = vd0*result1d3 + result1*vd0d1 + result1d0*vd3 + v*
        result1d0d1;
    totalvold0 = result1*vd0 + v*result1d0;
    totalvold1dd = result1d2*vd1d0 + vd1*result1d2d + vd1d*result1d3 + result1
        *vd1dd + vd2*result1d1d0 + result1d1*vd2d + result1d1d*vd3 + v*
        result1d1dd;
    totalvold1d = vd1*result1d2 + result1*vd1d + result1d1*vd2 + v*result1d1d;
    totalvold1d0 = vd1*result1d3 + result1*vd1d0 + result1d1*vd3 + v*
        result1d1d0;
    totalvold1 = result1*vd1 + v*result1d1;
    totalvold2d = vd2*result1d3 + result1*vd2d + result1d2*vd3 + v*result1d2d;
    totalvold2 = result1*vd2 + v*result1d2;
    totalvold3 = result1*vd3 + v*result1d3;
    totalvol = v*result1;
    temp10 = S*Kd0/K;
    temp6d = (Kd0*Sd3+S*Kd0d1-temp10*Kd3)/K;
    temp6 = temp10;
    temp10 = (Kd0*Sd2+S*Kd0d0-temp6*Kd2)/K;
    temp3dd = (Sd2*Kd0d1+Kd0*Sd2d+Kd0d0*Sd3+S*Kd0d0d-Kd2*temp6d-temp6*Kd2d-
        temp10*Kd3)/K;
    temp3d = temp10;
    temp3d0 = temp6d;
    temp3 = temp6;
    temp10 = (Sd0-temp3)/K;
    temp6d = (Sd0d1-temp3d0-temp10*Kd3)/K;
    temp6 = temp10;
    temp10 = (Sd0d0-temp3d-temp6*Kd2)/K;
    temp4dd = (Sd0d0d-temp3dd-Kd2*temp6d-temp6*Kd2d-temp10*Kd3)/K;
    temp4d = temp10;
    temp4d0 = temp6d;
    temp4 = temp6;
    temp10 = (Kd0*Sd1+S*Kd0d-temp3*Kd1)/K;
    temp6d = (Sd1*Kd0d1+Kd0*Sd1d0+Kd0d*Sd3+S*Kd0dd0-Kd1*temp3d0-temp3*Kd1d0-
        temp10*Kd3)/K;
    temp6 = temp10;
    temp10 = (Sd0d-temp6-temp4*Kd1)/K;
    temp7d = (Sd0dd0-temp6d-Kd1*temp4d0-temp4*Kd1d0-temp10*Kd3)/K;
    temp7 = temp10;
    temp10 = (Sd1*Kd0d0+Kd0*Sd1d+Kd0d*Sd2+S*Kd0dd-Kd1*temp3d-temp3*Kd1d-temp6*
        Kd2)/K;
    temp11 = (Sd0dd-temp10-Kd1*temp4d-temp4*Kd1d-temp7*Kd2)/K;
    tempdddd = (Sd0ddd-(Kd0d0*Sd1d0+Sd1*Kd0d0d+Sd1d*Kd0d1+Kd0*Sd1dd+Sd2*Kd0dd0
        +Kd0d*Sd2d+Kd0dd*Sd3+S*Kd0ddd-temp3d*Kd1d0-Kd1*temp3dd-Kd1d*temp3d0-
        temp3*Kd1dd-Kd2*temp6d-temp6*Kd2d-temp10*Kd3)/K-temp4d*Kd1d0-Kd1*
        temp4dd-Kd1d*temp4d0-temp4*Kd1dd-Kd2*temp7d-temp7*Kd2d-temp11*Kd3)/K;
    tempddd = temp11;
    tempddd0 = temp7d;
    tempdd = temp7;
    tempdd0d = temp4dd;
    tempdd0 = temp4d;
    tempdd1 = temp4d0;
    tempd = temp4;
    temp11 = S*Kd1/K;
    temp7d = (Kd1*Sd3+S*Kd1d0-temp11*Kd3)/K;
    temp7 = temp11;
    temp11 = (Sd1-temp7)/K;
    temp6d = (Sd1d0-temp7d-temp11*Kd3)/K;
    temp6 = temp11;
    temp11 = (Kd1*Sd2+S*Kd1d-temp7*Kd2)/K;
    temp10 = (Sd1d-temp11-temp6*Kd2)/K;
    tempd0dd = (Sd1dd-(Sd2*Kd1d0+Kd1*Sd2d+Kd1d*Sd3+S*Kd1dd-Kd2*temp7d-temp7*
        Kd2d-temp11*Kd3)/K-Kd2*temp6d-temp6*Kd2d-temp10*Kd3)/K;
    tempd0d = temp10;
    tempd0d0 = temp6d;
    tempd0 = temp6;
    temp11 = S*Kd2/K;
    temp10 = (Sd2-temp11)/K;
    tempd1d = (Sd2d-(Kd2*Sd3+S*Kd2d-temp11*Kd3)/K-temp10*Kd3)/K;
    tempd1 = temp10;
    tempd2 = (Sd3-S*Kd3/K)/K;
    temp = S/K;
    temp11 = log(temp)/totalvol;
    temp7d = (tempd2/temp-temp11*totalvold3)/totalvol;
    temp7 = temp11;
    temp11 = (tempd1/temp-temp7*totalvold2)/totalvol;
    temp4dd = ((tempd1d-tempd1*tempd2/temp)/temp-totalvold2*temp7d-temp7*
        totalvold2d-temp11*totalvold3)/totalvol;
    temp4d = temp11;
    temp4d0 = temp7d;
    temp4 = temp7;
    temp11 = (tempd0/temp-temp4*totalvold1)/totalvol;
    temp7d = ((tempd0d0-tempd0*tempd2/temp)/temp-totalvold1*temp4d0-temp4*
        totalvold1d0-temp11*totalvold3)/totalvol;
    temp7 = temp11;
    temp11 = tempd0*tempd1/temp;
    temp10 = (tempd0d-temp11)/temp;
    temp12 = (temp10-totalvold1*temp4d-temp4*totalvold1d-temp7*totalvold2)/
        totalvol;
    temp1ddd = ((tempd0dd-(tempd1*tempd0d0+tempd0*tempd1d-temp11*tempd2)/temp-
        temp10*tempd2)/temp-temp4d*totalvold1d0-totalvold1*temp4dd-totalvold1d
        *temp4d0-temp4*totalvold1dd-totalvold2*temp7d-temp7*totalvold2d-temp12
        *totalvold3)/totalvol;
    temp1dd = temp12;
    temp1dd0 = temp7d;
    temp1d = temp7;
    temp1d0d = temp4dd;
    temp1d0 = temp4d;
    temp1d1 = temp4d0;
    temp1 = temp4;
    temp12 = (tempd/temp-temp1*totalvold0)/totalvol;
    temp7d = ((tempdd1-tempd*tempd2/temp)/temp-totalvold0*temp1d1-temp1*
        totalvold0d1-temp12*totalvold3)/totalvol;
    temp7 = temp12;
    temp12 = tempd*tempd1/temp;
    temp11 = (tempdd0-temp12)/temp;
    temp10 = (temp11-totalvold0*temp1d0-temp1*totalvold0d0-temp7*totalvold2)/
        totalvol;
    temp4dd = ((tempdd0d-(tempd1*tempdd1+tempd*tempd1d-temp12*tempd2)/temp-
        temp11*tempd2)/temp-temp1d0*totalvold0d1-totalvold0*temp1d0d-
        totalvold0d0*temp1d1-temp1*totalvold0d0d-totalvold2*temp7d-temp7*
        totalvold2d-temp10*totalvold3)/totalvol;
    temp4d = temp10;
    temp4d0 = temp7d;
    temp4 = temp7;
    temp12 = tempd*tempd0/temp;
    temp7d = (tempd0*tempdd1+tempd*tempd0d0-temp12*tempd2)/temp;
    temp7 = temp12;
    temp12 = (tempdd-temp7)/temp;
    temp6d = (tempddd0-temp7d-temp12*tempd2)/temp;
    temp6 = temp12;
    temp12 = (temp6-totalvold0*temp1d-temp1*totalvold0d-temp4*totalvold1)/
        totalvol;
    temp8d = (temp6d-temp1d*totalvold0d1-totalvold0*temp1dd0-totalvold0d*
        temp1d1-temp1*totalvold0dd0-totalvold1*temp4d0-temp4*totalvold1d0-
        temp12*totalvold3)/totalvol;
    temp8 = temp12;
    temp12 = (tempd0*tempdd0+tempd*tempd0d-temp7*tempd1)/temp;
    temp11 = (tempddd-temp12-temp6*tempd1)/temp;
    temp10 = (temp11-temp1d*totalvold0d0-totalvold0*temp1dd-totalvold0d*
        temp1d0-temp1*totalvold0dd-totalvold1*temp4d-temp4*totalvold1d-temp8*
        totalvold2)/totalvol;
    temp0dddd = ((tempdddd-(tempdd0*tempd0d0+tempd0*tempdd0d+tempd0d*tempdd1+
        tempd*tempd0dd-tempd1*temp7d-temp7*tempd1d-temp12*tempd2)/temp-tempd1*
        temp6d-temp6*tempd1d-temp11*tempd2)/temp-totalvold0d0*temp1dd0-temp1d*
        totalvold0d0d-temp1dd*totalvold0d1-totalvold0*temp1ddd-temp1d0*
        totalvold0dd0-totalvold0d*temp1d0d-totalvold0dd*temp1d1-temp1*
        totalvold0ddd-temp4d*totalvold1d0-totalvold1*temp4dd-totalvold1d*
        temp4d0-temp4*totalvold1dd-totalvold2*temp8d-temp8*totalvold2d-temp10*
        totalvold3)/totalvol;
    temp0ddd = temp10;
    temp0ddd0 = temp8d;
    temp0dd = temp8;
    temp0dd0d = temp4dd;
    temp0dd0 = temp4d;
    temp0dd1 = temp4d0;
    temp0d = temp4;
    temp0d0dd = temp1ddd;
    temp0d0d = temp1dd;
    temp0d0d0 = temp1dd0;
    temp0d0 = temp1d;
    temp0d1d = temp1d0d;
    temp0d1 = temp1d0;
    temp0d2 = temp1d1;
    temp0 = temp1;
    double d1 = temp0 + 0.5*totalvol;
    double d1d3 = temp0d2 + 0.5*totalvold3;
    double d1d2 = temp0d1 + 0.5*totalvold2;
    double d1d2d = temp0d1d + 0.5*totalvold2d;
    double d1d1 = temp0d0 + 0.5*totalvold1;
    double d1d1d0 = temp0d0d0 + 0.5*totalvold1d0;
    double d1d1d = temp0d0d + 0.5*totalvold1d;
    double d1d1dd = temp0d0dd + 0.5*totalvold1dd;
    double d1d0 = temp0d + 0.5*totalvold0;
    double d1d0d1 = temp0dd1 + 0.5*totalvold0d1;
    double d1d0d0 = temp0dd0 + 0.5*totalvold0d0;
    double d1d0d0d = temp0dd0d + 0.5*totalvold0d0d;
    double d1d0d = temp0dd + 0.5*totalvold0d;
    double d1d0dd0 = temp0ddd0 + 0.5*totalvold0dd0;
    double d1d0dd = temp0ddd + 0.5*totalvold0dd;
    double d1d0ddd = temp0dddd + 0.5*totalvold0ddd;
    temp12 = (Sd-temp*Kd)/(temp*K);
    temp8d = (Sdd2-Kd*tempd2-temp*Kdd2-temp12*(K*tempd2+temp*Kd3))/(temp*K);
    temp8 = temp12;
    temp12 = K*tempd1 + temp*Kd2;
    temp11 = (Sdd1-Kd*tempd1-temp*Kdd1-temp8*temp12)/(temp*K);
    temp4dd = (Sdd1d-tempd1*Kdd2-Kd*tempd1d-Kdd1*tempd2-temp*Kdd1d-temp12*
        temp8d-temp8*(tempd1*Kd3+K*tempd1d+Kd2*tempd2+temp*Kd2d)-temp11*(K*
        tempd2+temp*Kd3))/(temp*K);
    temp4d = temp11;
    temp4d0 = temp8d;
    temp4 = temp8;
    temp8d = tempd0*Kd3 + K*tempd0d0 + Kd1*tempd2 + temp*Kd1d0;
    temp8 = K*tempd0 + temp*Kd1;
    temp12 = (Sdd0-Kd*tempd0-temp*Kdd0-temp4*temp8)/(temp*K);
    temp7d = (Sdd0d0-tempd0*Kdd2-Kd*tempd0d0-Kdd0*tempd2-temp*Kdd0d0-temp8*
        temp4d0-temp4*temp8d-temp12*(K*tempd2+temp*Kd3))/(temp*K);
    temp7 = temp12;
    temp12 = tempd0*Kd2 + K*tempd0d + Kd1*tempd1 + temp*Kd1d;
    temp11 = K*tempd1 + temp*Kd2;
    temp10 = (Sdd0d-tempd0*Kdd1-Kd*tempd0d-Kdd0*tempd1-temp*Kdd0d-temp8*temp4d
        -temp4*temp12-temp7*temp11)/(temp*K);
    temp1ddd = (Sdd0dd-Kdd1*tempd0d0-tempd0*Kdd1d-tempd0d*Kdd2-Kd*tempd0dd-
        tempd1*Kdd0d0-Kdd0*tempd1d-Kdd0d*tempd2-temp*Kdd0dd-temp4d*temp8d-
        temp8*temp4dd-temp12*temp4d0-temp4*(Kd2*tempd0d0+tempd0*Kd2d+tempd0d*
        Kd3+K*tempd0dd+tempd1*Kd1d0+Kd1*tempd1d+Kd1d*tempd2+temp*Kd1dd)-temp11
        *temp7d-temp7*(tempd1*Kd3+K*tempd1d+Kd2*tempd2+temp*Kd2d)-temp10*(K*
        tempd2+temp*Kd3))/(temp*K);
    temp1dd = temp10;
    temp1dd0 = temp7d;
    temp1d = temp7;
    temp1d0d = temp4dd;
    temp1d0 = temp4d;
    temp1d1 = temp4d0;
    temp1 = temp4;
    temp12 = (temp1-temp0*totalvold)/totalvol;
    temp8d = (temp1d1-totalvold*temp0d2-temp0*totalvoldd2-temp12*totalvold3)/
        totalvol;
    temp8 = temp12;
    temp12 = (temp1d0-totalvold*temp0d1-temp0*totalvoldd1-temp8*totalvold2)/
        totalvol;
    temp4dd = (temp1d0d-temp0d1*totalvoldd2-totalvold*temp0d1d-totalvoldd1*
        temp0d2-temp0*totalvoldd1d-totalvold2*temp8d-temp8*totalvold2d-temp12*
        totalvold3)/totalvol;
    temp4d = temp12;
    temp4d0 = temp8d;
    temp4 = temp8;
    temp12 = (temp1d-totalvold*temp0d0-temp0*totalvoldd0-temp4*totalvold1)/
        totalvol;
    temp8d = (temp1dd0-temp0d0*totalvoldd2-totalvold*temp0d0d0-totalvoldd0*
        temp0d2-temp0*totalvoldd0d0-totalvold1*temp4d0-temp4*totalvold1d0-
        temp12*totalvold3)/totalvol;
    temp8 = temp12;
    temp12 = (temp1dd-temp0d0*totalvoldd1-totalvold*temp0d0d-totalvoldd0*
        temp0d1-temp0*totalvoldd0d-totalvold1*temp4d-temp4*totalvold1d-temp8*
        totalvold2)/totalvol;
    temp2ddd = (temp1ddd-totalvoldd1*temp0d0d0-temp0d0*totalvoldd1d-temp0d0d*
        totalvoldd2-totalvold*temp0d0dd-temp0d1*totalvoldd0d0-totalvoldd0*
        temp0d1d-totalvoldd0d*temp0d2-temp0*totalvoldd0dd-temp4d*totalvold1d0-
        totalvold1*temp4dd-totalvold1d*temp4d0-temp4*totalvold1dd-totalvold2*
        temp8d-temp8*totalvold2d-temp12*totalvold3)/totalvol;
    temp2dd = temp12;
    temp2dd0 = temp8d;
    temp2d = temp8;
    temp2d0d = temp4dd;
    temp2d0 = temp4d;
    temp2d1 = temp4d0;
    temp2 = temp4;
    double d1d = temp2 + 0.5*totalvold;
    double d1dd2 = temp2d1 + 0.5*totalvoldd2;
    double d1dd1 = temp2d0 + 0.5*totalvoldd1;
    double d1dd1d = temp2d0d + 0.5*totalvoldd1d;
    double d1dd0 = temp2d + 0.5*totalvoldd0;
    double d1dd0d0 = temp2dd0 + 0.5*totalvoldd0d0;
    double d1dd0d = temp2dd + 0.5*totalvoldd0d;
    double d1dd0dd = temp2ddd + 0.5*totalvoldd0dd;
    temp4dd = Kd2*tempdd1 + tempd*Kd2d + tempdd0*Kd3 + K*tempdd0d + tempd1*
        Kd0d1 + Kd0*tempd1d + Kd0d0*tempd2 + temp*Kd0d0d;
    temp4d = tempd*Kd2 + K*tempdd0 + Kd0*tempd1 + temp*Kd0d0;
    temp4d0 = tempd*Kd3 + K*tempdd1 + Kd0*tempd2 + temp*Kd0d1;
    temp4 = K*tempd + temp*Kd0;
    temp12 = (Sdd-Kd*tempd-temp*Kdd-temp1*temp4)/(temp*K);
    temp8d = (Sddd1-tempd*Kdd2-Kd*tempdd1-Kdd*tempd2-temp*Kddd1-temp4*temp1d1-
        temp1*temp4d0-temp12*(K*tempd2+temp*Kd3))/(temp*K);
    temp8 = temp12;
    temp12 = K*tempd1 + temp*Kd2;
    temp11 = (Sddd0-tempd*Kdd1-Kd*tempdd0-Kdd*tempd1-temp*Kddd0-temp4*temp1d0-
        temp1*temp4d-temp8*temp12)/(temp*K);
    temp3dd = (Sddd0d-Kdd1*tempdd1-tempd*Kdd1d-tempdd0*Kdd2-Kd*tempdd0d-tempd1
        *Kddd1-Kdd*tempd1d-Kddd0*tempd2-temp*Kddd0d-temp1d0*temp4d0-temp4*
        temp1d0d-temp4d*temp1d1-temp1*temp4dd-temp12*temp8d-temp8*(tempd1*Kd3+
        K*tempd1d+Kd2*tempd2+temp*Kd2d)-temp11*(K*tempd2+temp*Kd3))/(temp*K);
    temp3d = temp11;
    temp3d0 = temp8d;
    temp3 = temp8;
    temp12 = (temp3-totalvold*temp0d-temp0*totalvoldd-temp2*totalvold0)/
        totalvol;
    temp8d = (temp3d0-temp0d*totalvoldd2-totalvold*temp0dd1-totalvoldd*temp0d2
        -temp0*totalvolddd1-totalvold0*temp2d1-temp2*totalvold0d1-temp12*
        totalvold3)/totalvol;
    temp8 = temp12;
    temp12 = (temp3d-temp0d*totalvoldd1-totalvold*temp0dd0-totalvoldd*temp0d1-
        temp0*totalvolddd0-totalvold0*temp2d0-temp2*totalvold0d0-temp8*
        totalvold2)/totalvol;
    temp5dd = (temp3dd-totalvoldd1*temp0dd1-temp0d*totalvoldd1d-temp0dd0*
        totalvoldd2-totalvold*temp0dd0d-temp0d1*totalvolddd1-totalvoldd*
        temp0d1d-totalvolddd0*temp0d2-temp0*totalvolddd0d-temp2d0*totalvold0d1
        -totalvold0*temp2d0d-totalvold0d0*temp2d1-temp2*totalvold0d0d-
        totalvold2*temp8d-temp8*totalvold2d-temp12*totalvold3)/totalvol;
    temp5d = temp12;
    temp5d0 = temp8d;
    temp5 = temp8;
    double d1dd = temp5 + 0.5*totalvoldd;
    double d1ddd1 = temp5d0 + 0.5*totalvolddd1;
    double d1ddd0 = temp5d + 0.5*totalvolddd0;
    double d1ddd0d = temp5dd + 0.5*totalvolddd0d;
    temp8d = Kd1*tempdd1 + tempd*Kd1d0 + tempdd*Kd3 + K*tempddd0 + tempd0*
        Kd0d1 + Kd0*tempd0d0 + Kd0d*tempd2 + temp*Kd0dd0;
    temp8 = tempd*Kd1 + K*tempdd + Kd0*tempd0 + temp*Kd0d;
    temp7d = tempd0*Kd3 + K*tempd0d0 + Kd1*tempd2 + temp*Kd1d0;
    temp7 = K*tempd0 + temp*Kd1;
    temp12 = (Sddd-tempd*Kdd0-Kd*tempdd-Kdd*tempd0-temp*Kddd-temp4*temp1d-
        temp1*temp8-temp3*temp7)/(temp*K);
    temp6d = (Sdddd0-Kdd0*tempdd1-tempd*Kdd0d0-tempdd*Kdd2-Kd*tempddd0-tempd0*
        Kddd1-Kdd*tempd0d0-Kddd*tempd2-temp*Kdddd0-temp1d*temp4d0-temp4*
        temp1dd0-temp8*temp1d1-temp1*temp8d-temp7*temp3d0-temp3*temp7d-temp12*
        (K*tempd2+temp*Kd3))/(temp*K);
    temp6 = temp12;
    temp12 = (temp6-temp0d*totalvoldd0-totalvold*temp0dd-totalvoldd*temp0d0-
        temp0*totalvolddd-totalvold0*temp2d-temp2*totalvold0d-temp5*totalvold1
        )/totalvol;
    temp9d = (temp6d-totalvoldd0*temp0dd1-temp0d*totalvoldd0d0-temp0dd*
        totalvoldd2-totalvold*temp0ddd0-temp0d0*totalvolddd1-totalvoldd*
        temp0d0d0-totalvolddd*temp0d2-temp0*totalvoldddd0-temp2d*totalvold0d1-
        totalvold0*temp2dd0-totalvold0d*temp2d1-temp2*totalvold0dd0-totalvold1
        *temp5d0-temp5*totalvold1d0-temp12*totalvold3)/totalvol;
    temp9 = temp12;
    double d1ddd = temp9 + 0.5*totalvolddd;
    double d1dddd0 = temp9d + 0.5*totalvoldddd0;
    temp12 = Kd1*tempdd0 + tempd*Kd1d + tempdd*Kd2 + K*tempddd + tempd0*Kd0d0 
        + Kd0*tempd0d + Kd0d*tempd1 + temp*Kd0dd;
    temp11 = tempd0*Kd2 + K*tempd0d + Kd1*tempd1 + temp*Kd1d;
    temp10 = K*tempd1 + temp*Kd2;
    temp13 = (Sdddd-Kdd0*tempdd0-tempd*Kdd0d-tempdd*Kdd1-Kd*tempddd-tempd0*
        Kddd0-Kdd*tempd0d-Kddd*tempd1-temp*Kdddd-temp1d*temp4d-temp4*temp1dd-
        temp8*temp1d0-temp1*temp12-temp7*temp3d-temp3*temp11-temp6*temp10)/(
        temp*K);
    temp14 = (temp13-totalvoldd0*temp0dd0-temp0d*totalvoldd0d-temp0dd*
        totalvoldd1-totalvold*temp0ddd-temp0d0*totalvolddd0-totalvoldd*
        temp0d0d-totalvolddd*temp0d1-temp0*totalvoldddd-temp2d*totalvold0d0-
        totalvold0*temp2dd-totalvold0d*temp2d0-temp2*totalvold0dd-totalvold1*
        temp5d-temp5*totalvold1d-temp9*totalvold2)/totalvol;
    double d1dddd = temp14 + 0.5*totalvoldddd;
    double d1ddddd = ((Sddddd-tempdd0*Kdd0d0-Kdd0*tempdd0d-Kdd0d*tempdd1-tempd
    *Kdd0dd-Kdd1*tempddd0-tempdd*Kdd1d-tempddd*Kdd2-Kd*tempdddd-Kddd0*tempd0d0
    -tempd0*Kddd0d-tempd0d*Kddd1-Kdd*tempd0dd-tempd1*Kdddd0-Kddd*tempd1d-Kdddd
    *tempd2-temp*Kddddd-temp4d*temp1dd0-temp1d*temp4dd-temp1dd*temp4d0-temp4*
    temp1ddd-temp1d0*temp8d-temp8*temp1d0d-temp12*temp1d1-temp1*(tempdd0*Kd1d0
    +Kd1*tempdd0d+Kd1d*tempdd1+tempd*Kd1dd+Kd2*tempddd0+tempdd*Kd2d+tempddd*
    Kd3+K*tempdddd+Kd0d0*tempd0d0+tempd0*Kd0d0d+tempd0d*Kd0d1+Kd0*tempd0dd+
    tempd1*Kd0dd0+Kd0d*tempd1d+Kd0dd*tempd2+temp*Kd0ddd)-temp3d*temp7d-temp7*
    temp3dd-temp11*temp3d0-temp3*(Kd2*tempd0d0+tempd0*Kd2d+tempd0d*Kd3+K*
    tempd0dd+tempd1*Kd1d0+Kd1*tempd1d+Kd1d*tempd2+temp*Kd1dd)-temp10*temp6d-
    temp6*(tempd1*Kd3+K*tempd1d+Kd2*tempd2+temp*Kd2d)-temp13*(K*tempd2+temp*
    Kd3))/(temp*K)-temp0dd0*totalvoldd0d0-totalvoldd0*temp0dd0d-totalvoldd0d*
    temp0dd1-temp0d*totalvoldd0dd-totalvoldd1*temp0ddd0-temp0dd*totalvoldd1d-
    temp0ddd*totalvoldd2-totalvold*temp0dddd-totalvolddd0*temp0d0d0-temp0d0*
    totalvolddd0d-temp0d0d*totalvolddd1-totalvoldd*temp0d0dd-temp0d1*
    totalvoldddd0-totalvolddd*temp0d1d-totalvoldddd*temp0d2-temp0*
    totalvolddddd-totalvold0d0*temp2dd0-temp2d*totalvold0d0d-temp2dd*
    totalvold0d1-totalvold0*temp2ddd-temp2d0*totalvold0dd0-totalvold0d*
    temp2d0d-totalvold0dd*temp2d1-temp2*totalvold0ddd-temp5d*totalvold1d0-
    totalvold1*temp5dd-totalvold1d*temp5d0-temp5*totalvold1dd-totalvold2*
    temp9d-temp9*totalvold2d-temp14*totalvold3)/totalvol + 0.5*totalvolddddd;
    double d2 = d1 - totalvol;
    double d2d3 = d1d3 - totalvold3;
    double d2d2 = d1d2 - totalvold2;
    double d2d2d = d1d2d - totalvold2d;
    double d2d1 = d1d1 - totalvold1;
    double d2d1d0 = d1d1d0 - totalvold1d0;
    double d2d1d = d1d1d - totalvold1d;
    double d2d1dd = d1d1dd - totalvold1dd;
    double d2d0 = d1d0 - totalvold0;
    double d2d0d1 = d1d0d1 - totalvold0d1;
    double d2d0d0 = d1d0d0 - totalvold0d0;
    double d2d0d0d = d1d0d0d - totalvold0d0d;
    double d2d0d = d1d0d - totalvold0d;
    double d2d0dd0 = d1d0dd0 - totalvold0dd0;
    double d2d0dd = d1d0dd - totalvold0dd;
    double d2d0ddd = d1d0ddd - totalvold0ddd;
    double d2d = d1d - totalvold;
    double d2dd2 = d1dd2 - totalvoldd2;
    double d2dd1 = d1dd1 - totalvoldd1;
    double d2dd1d = d1dd1d - totalvoldd1d;
    double d2dd0 = d1dd0 - totalvoldd0;
    double d2dd0d0 = d1dd0d0 - totalvoldd0d0;
    double d2dd0d = d1dd0d - totalvoldd0d;
    double d2dd0dd = d1dd0dd - totalvoldd0dd;
    double d2dd = d1dd - totalvoldd;
    double d2ddd1 = d1ddd1 - totalvolddd1;
    double d2ddd0 = d1ddd0 - totalvolddd0;
    double d2ddd0d = d1ddd0d - totalvolddd0d;
    double d2ddd = d1ddd - totalvolddd;
    double d2dddd0 = d1dddd0 - totalvoldddd0;
    double d2dddd = d1dddd - totalvoldddd;
    double d2ddddd = d1ddddd - totalvolddddd;
    result1ddddd = cdf_n_d_d_d_d_d(d1, d1d3, d1d2, d1d2d, d1d1, d1d1d0, d1d1d,
                                   d1d1dd, d1d0, d1d0d1, d1d0d0, d1d0d0d, 
                                   d1d0d, d1d0dd0, d1d0dd, d1d0ddd, d1d, d1dd2
                                   , d1dd1, d1dd1d, d1dd0, d1dd0d0, d1dd0d, 
                                   d1dd0dd, d1dd, d1ddd1, d1ddd0, d1ddd0d, 
                                   d1ddd, d1dddd0, d1dddd, d1ddddd, &result1, 
                                   &result1d3, &result1d2, &result1d2d, &
                                   result1d1, &result1d1d0, &result1d1d, &
                                   result1d1dd, &result1d0, &result1d0d1, &
                                   result1d0d0, &result1d0d0d, &result1d0d, &
                                   result1d0dd0, &result1d0dd, &result1d0ddd, 
                                   &result1d, &result1dd2, &result1dd1, &
                                   result1dd1d, &result1dd0, &result1dd0d0, &
                                   result1dd0d, &result1dd0dd, &result1dd, &
                                   result1ddd1, &result1ddd0, &result1ddd0d, &
                                   result1ddd, &result1dddd0, &result1dddd);
    result2d0d = 0.0;
    result2d0d0 = 0.0;
    result2d0d1 = 0.0;
    result2d0 = 0.0;
    result2dd0d = 0.0;
    result2dd0d0 = 0.0;
    result2dd0 = 0.0;
    result2d0dd = 0.0;
    result2d0dd0 = 0.0;
    result2d0d = 0.0;
    result2d1d = 0.0;
    result2d1d0 = 0.0;
    result2d1 = 0.0;
    result2ddd0d = 0.0;
    result2ddd0 = 0.0;
    result2dd0dd = 0.0;
    result2dd0d = 0.0;
    result2dd1d = 0.0;
    result2dd1 = 0.0;
    result2d0ddd = 0.0;
    result2d0dd = 0.0;
    result2d0d0d = 0.0;
    result2d0d0 = 0.0;
    result2d1dd = 0.0;
    result2d1d = 0.0;
    result2d2d = 0.0;
    result2d2 = 0.0;
    result2dddd0 = 0.0;
    result2ddd0d = 0.0;
    result2ddd1 = 0.0;
    result2dd0dd = 0.0;
    result2dd0d0 = 0.0;
    result2dd1d = 0.0;
    result2dd2 = 0.0;
    result2d0ddd = 0.0;
    result2d0dd0 = 0.0;
    result2d0d0d = 0.0;
    result2d0d1 = 0.0;
    result2d1dd = 0.0;
    result2d1d0 = 0.0;
    result2d2d = 0.0;
    result2d3 = 0.0;
    result2ddddd = cdf_n_d_d_d_d_d(d2, d2d3, d2d2, d2d2d, d2d1, d2d1d0, d2d1d,
                                   d2d1dd, d2d0, d2d0d1, d2d0d0, d2d0d0d, 
                                   d2d0d, d2d0dd0, d2d0dd, d2d0ddd, d2d, d2dd2
                                   , d2dd1, d2dd1d, d2dd0, d2dd0d0, d2dd0d, 
                                   d2dd0dd, d2dd, d2ddd1, d2ddd0, d2ddd0d, 
                                   d2ddd, d2dddd0, d2dddd, d2ddddd, &result2, 
                                   &result2d3, &result2d2, &result2d2d, &
                                   result2d1, &result2d1d0, &result2d1d, &
                                   result2d1dd, &result2d0, &result2d0d1, &
                                   result2d0d0, &result2d0d0d, &result2d0d, &
                                   result2d0dd0, &result2d0dd, &result2d0ddd, 
                                   &result2d, &result2dd2, &result2dd1, &
                                   result2dd1d, &result2dd0, &result2dd0d0, &
                                   result2dd0d, &result2dd0dd, &result2dd, &
                                   result2ddd1, &result2ddd0, &result2ddd0d, &
                                   result2ddd, &result2dddd0, &result2dddd);
    *call_pricedddd = Sd0d0*result1d1d0 + result1d1*Sd0d0d + result1d1d*Sd0d1 
        + Sd0*result1d1dd + result1d2*Sd0dd0 + Sd0d*result1d2d + Sd0dd*
        result1d3 + result1*Sd0ddd + result1d0d0*Sd1d0 + Sd1*result1d0d0d + 
        Sd1d*result1d0d1 + result1d0*Sd1dd + Sd2*result1d0dd0 + result1d0d*
        Sd2d + result1d0dd*Sd3 + S*result1d0ddd - Kd0d0*result2d1d0 - 
        result2d1*Kd0d0d - result2d1d*Kd0d1 - Kd0*result2d1dd - result2d2*
        Kd0dd0 - Kd0d*result2d2d - Kd0dd*result2d3 - result2*Kd0ddd - 
        result2d0d0*Kd1d0 - Kd1*result2d0d0d - Kd1d*result2d0d1 - result2d0*
        Kd1dd - Kd2*result2d0dd0 - result2d0d*Kd2d - result2d0dd*Kd3 - K*
        result2d0ddd;
    *call_priceddd = result1d1*Sd0d0 + Sd0*result1d1d + Sd0d*result1d2 + 
        result1*Sd0dd + Sd1*result1d0d0 + result1d0*Sd1d + result1d0d*Sd2 + S*
        result1d0dd - result2d1*Kd0d0 - Kd0*result2d1d - Kd0d*result2d2 - 
        result2*Kd0dd - Kd1*result2d0d0 - result2d0*Kd1d - result2d0d*Kd2 - K*
        result2d0dd;
    *call_priceddd0 = result1d1*Sd0d1 + Sd0*result1d1d0 + Sd0d*result1d3 + 
        result1*Sd0dd0 + Sd1*result1d0d1 + result1d0*Sd1d0 + result1d0d*Sd3 + 
        S*result1d0dd0 - result2d1*Kd0d1 - Kd0*result2d1d0 - Kd0d*result2d3 - 
        result2*Kd0dd0 - Kd1*result2d0d1 - result2d0*Kd1d0 - result2d0d*Kd3 - 
        K*result2d0dd0;
    *call_pricedd = Sd0*result1d1 + result1*Sd0d + result1d0*Sd1 + S*
        result1d0d - Kd0*result2d1 - result2*Kd0d - result2d0*Kd1 - K*
        result2d0d;
    *call_pricedd0d = result1d2*Sd0d1 + Sd0*result1d2d + Sd0d0*result1d3 + 
        result1*Sd0d0d + Sd2*result1d0d1 + result1d0*Sd2d + result1d0d0*Sd3 + 
        S*result1d0d0d - result2d2*Kd0d1 - Kd0*result2d2d - Kd0d0*result2d3 - 
        result2*Kd0d0d - Kd2*result2d0d1 - result2d0*Kd2d - result2d0d0*Kd3 - 
        K*result2d0d0d;
    *call_pricedd0 = Sd0*result1d2 + result1*Sd0d0 + result1d0*Sd2 + S*
        result1d0d0 - Kd0*result2d2 - result2*Kd0d0 - result2d0*Kd2 - K*
        result2d0d0;
    *call_pricedd1 = Sd0*result1d3 + result1*Sd0d1 + result1d0*Sd3 + S*
        result1d0d1 - Kd0*result2d3 - result2*Kd0d1 - result2d0*Kd3 - K*
        result2d0d1;
    *call_priced = result1*Sd0 + S*result1d0 - result2*Kd0 - K*result2d0;
    *call_priced0dd = result1d2*Sd1d0 + Sd1*result1d2d + Sd1d*result1d3 + 
        result1*Sd1dd + Sd2*result1d1d0 + result1d1*Sd2d + result1d1d*Sd3 + S*
        result1d1dd - result2d2*Kd1d0 - Kd1*result2d2d - Kd1d*result2d3 - 
        result2*Kd1dd - Kd2*result2d1d0 - result2d1*Kd2d - result2d1d*Kd3 - K*
        result2d1dd;
    *call_priced0d = Sd1*result1d2 + result1*Sd1d + result1d1*Sd2 + S*
        result1d1d - Kd1*result2d2 - result2*Kd1d - result2d1*Kd2 - K*
        result2d1d;
    *call_priced0d0 = Sd1*result1d3 + result1*Sd1d0 + result1d1*Sd3 + S*
        result1d1d0 - Kd1*result2d3 - result2*Kd1d0 - result2d1*Kd3 - K*
        result2d1d0;
    *call_priced0 = result1*Sd1 + S*result1d1 - result2*Kd1 - K*result2d1;
    *call_priced1d = Sd2*result1d3 + result1*Sd2d + result1d2*Sd3 + S*
        result1d2d - Kd2*result2d3 - result2*Kd2d - result2d2*Kd3 - K*
        result2d2d;
    *call_priced1 = result1*Sd2 + S*result1d2 - result2*Kd2 - K*result2d2;
    *call_priced2 = result1*Sd3 + S*result1d3 - result2*Kd3 - K*result2d3;
    *call_price = S*result1 - K*result2;
    *call_price_dddd = Sdd1*result1d1d0 + result1d1*Sdd1d + result1d1d*Sdd2 + 
        Sd*result1d1dd + result1d2*Sdd0d0 + Sdd0*result1d2d + Sdd0d*result1d3 
        + result1*Sdd0dd + result1dd1*Sd1d0 + Sd1*result1dd1d + Sd1d*
        result1dd2 + result1d*Sd1dd + Sd2*result1dd0d0 + result1dd0*Sd2d + 
        result1dd0d*Sd3 + S*result1dd0dd - Kdd1*result2d1d0 - result2d1*Kdd1d 
        - result2d1d*Kdd2 - Kd*result2d1dd - result2d2*Kdd0d0 - Kdd0*
        result2d2d - Kdd0d*result2d3 - result2*Kdd0dd - result2dd1*Kd1d0 - Kd1
        *result2dd1d - Kd1d*result2dd2 - result2d*Kd1dd - Kd2*result2dd0d0 - 
        result2dd0*Kd2d - result2dd0d*Kd3 - K*result2dd0dd;
    *call_price_ddd = result1d1*Sdd1 + Sd*result1d1d + Sdd0*result1d2 + 
        result1*Sdd0d + Sd1*result1dd1 + result1d*Sd1d + result1dd0*Sd2 + S*
        result1dd0d - result2d1*Kdd1 - Kd*result2d1d - Kdd0*result2d2 - 
        result2*Kdd0d - Kd1*result2dd1 - result2d*Kd1d - result2dd0*Kd2 - K*
        result2dd0d;
    *call_price_ddd0 = result1d1*Sdd2 + Sd*result1d1d0 + Sdd0*result1d3 + 
        result1*Sdd0d0 + Sd1*result1dd2 + result1d*Sd1d0 + result1dd0*Sd3 + S*
        result1dd0d0 - result2d1*Kdd2 - Kd*result2d1d0 - Kdd0*result2d3 - 
        result2*Kdd0d0 - Kd1*result2dd2 - result2d*Kd1d0 - result2dd0*Kd3 - K*
        result2dd0d0;
    *call_price_dd = Sd*result1d1 + result1*Sdd0 + result1d*Sd1 + S*result1dd0
        - Kd*result2d1 - result2*Kdd0 - result2d*Kd1 - K*result2dd0;
    *call_price_dd0d = result1d2*Sdd2 + Sd*result1d2d + Sdd1*result1d3 + 
        result1*Sdd1d + Sd2*result1dd2 + result1d*Sd2d + result1dd1*Sd3 + S*
        result1dd1d - result2d2*Kdd2 - Kd*result2d2d - Kdd1*result2d3 - 
        result2*Kdd1d - Kd2*result2dd2 - result2d*Kd2d - result2dd1*Kd3 - K*
        result2dd1d;
    *call_price_dd0 = Sd*result1d2 + result1*Sdd1 + result1d*Sd2 + S*
        result1dd1 - Kd*result2d2 - result2*Kdd1 - result2d*Kd2 - K*result2dd1
    ;
    *call_price_dd1 = Sd*result1d3 + result1*Sdd2 + result1d*Sd3 + S*
        result1dd2 - Kd*result2d3 - result2*Kdd2 - result2d*Kd3 - K*result2dd2
    ;
    *call_price_d = result1*Sd + S*result1d - result2*Kd - K*result2d;
    *call_price_d_ddd = Sdd1*result1d0d1 + result1d0*Sdd1d + result1d0d0*Sdd2 
        + Sd*result1d0d0d + result1d2*Sddd1 + Sdd*result1d2d + Sddd0*result1d3
        + result1*Sddd0d + result1dd1*Sd0d1 + Sd0*result1dd1d + Sd0d0*
        result1dd2 + result1d*Sd0d0d + Sd2*result1ddd1 + result1dd*Sd2d + 
        result1ddd0*Sd3 + S*result1ddd0d - Kdd1*result2d0d1 - result2d0*Kdd1d 
        - result2d0d0*Kdd2 - Kd*result2d0d0d - result2d2*Kddd1 - Kdd*
        result2d2d - Kddd0*result2d3 - result2*Kddd0d - result2dd1*Kd0d1 - Kd0
        *result2dd1d - Kd0d0*result2dd2 - result2d*Kd0d0d - Kd2*result2ddd1 - 
        result2dd*Kd2d - result2ddd0*Kd3 - K*result2ddd0d;
    *call_price_d_dd = result1d0*Sdd1 + Sd*result1d0d0 + Sdd*result1d2 + 
        result1*Sddd0 + Sd0*result1dd1 + result1d*Sd0d0 + result1dd*Sd2 + S*
        result1ddd0 - result2d0*Kdd1 - Kd*result2d0d0 - Kdd*result2d2 - 
        result2*Kddd0 - Kd0*result2dd1 - result2d*Kd0d0 - result2dd*Kd2 - K*
        result2ddd0;
    *call_price_d_dd0 = result1d0*Sdd2 + Sd*result1d0d1 + Sdd*result1d3 + 
        result1*Sddd1 + Sd0*result1dd2 + result1d*Sd0d1 + result1dd*Sd3 + S*
        result1ddd1 - result2d0*Kdd2 - Kd*result2d0d1 - Kdd*result2d3 - 
        result2*Kddd1 - Kd0*result2dd2 - result2d*Kd0d1 - result2dd*Kd3 - K*
        result2ddd1;
    *call_price_d_d = Sd*result1d0 + result1*Sdd + result1d*Sd0 + S*result1dd 
        - Kd*result2d0 - result2*Kdd - result2d*Kd0 - K*result2dd;
    *call_price_d_d_dd = Sdd0*result1d0d1 + result1d0*Sdd0d0 + result1d0d*Sdd2
        + Sd*result1d0dd0 + result1d1*Sddd1 + Sdd*result1d1d0 + Sddd*result1d3
        + result1*Sdddd0 + result1dd0*Sd0d1 + Sd0*result1dd0d0 + Sd0d*
        result1dd2 + result1d*Sd0dd0 + Sd1*result1ddd1 + result1dd*Sd1d0 + 
        result1ddd*Sd3 + S*result1dddd0 - Kdd0*result2d0d1 - result2d0*Kdd0d0 
        - result2d0d*Kdd2 - Kd*result2d0dd0 - result2d1*Kddd1 - Kdd*
        result2d1d0 - Kddd*result2d3 - result2*Kdddd0 - result2dd0*Kd0d1 - Kd0
        *result2dd0d0 - Kd0d*result2dd2 - result2d*Kd0dd0 - Kd1*result2ddd1 - 
        result2dd*Kd1d0 - result2ddd*Kd3 - K*result2dddd0;
    *call_price_d_d_d = result1d0*Sdd0 + Sd*result1d0d + Sdd*result1d1 + 
        result1*Sddd + Sd0*result1dd0 + result1d*Sd0d + result1dd*Sd1 + S*
        result1ddd - result2d0*Kdd0 - Kd*result2d0d - Kdd*result2d1 - result2*
        Kddd - Kd0*result2dd0 - result2d*Kd0d - result2dd*Kd1 - K*result2ddd;
    *call_price_d_d_d_d = Sdd0*result1d0d0 + result1d0*Sdd0d + result1d0d*Sdd1
        + Sd*result1d0dd + result1d1*Sddd0 + Sdd*result1d1d + Sddd*result1d2 +
        result1*Sdddd + result1dd0*Sd0d0 + Sd0*result1dd0d + Sd0d*result1dd1 +
        result1d*Sd0dd + Sd1*result1ddd0 + result1dd*Sd1d + result1ddd*Sd2 + S
        *result1dddd - Kdd0*result2d0d0 - result2d0*Kdd0d - result2d0d*Kdd1 - 
        Kd*result2d0dd - result2d1*Kddd0 - Kdd*result2d1d - Kddd*result2d2 - 
        result2*Kdddd - result2dd0*Kd0d0 - Kd0*result2dd0d - Kd0d*result2dd1 -
        result2d*Kd0dd - Kd1*result2ddd0 - result2dd*Kd1d - result2ddd*Kd2 - K
        *result2dddd;
    return result1d0d0*Sdd0d0 + Sdd0*result1d0d0d + Sdd0d*result1d0d1 + 
    result1d0*Sdd0dd + Sdd1*result1d0dd0 + result1d0d*Sdd1d + result1d0dd*Sdd2
    + Sd*result1d0ddd + Sddd0*result1d1d0 + result1d1*Sddd0d + result1d1d*
    Sddd1 + Sdd*result1d1dd + result1d2*Sdddd0 + Sddd*result1d2d + Sdddd*
    result1d3 + result1*Sddddd + Sd0d0*result1dd0d0 + result1dd0*Sd0d0d + 
    result1dd0d*Sd0d1 + Sd0*result1dd0dd + result1dd1*Sd0dd0 + Sd0d*
    result1dd1d + Sd0dd*result1dd2 + result1d*Sd0ddd + result1ddd0*Sd1d0 + Sd1
    *result1ddd0d + Sd1d*result1ddd1 + result1dd*Sd1dd + Sd2*result1dddd0 + 
    result1ddd*Sd2d + result1dddd*Sd3 + S*result1ddddd - result2d0d0*Kdd0d0 - 
    Kdd0*result2d0d0d - Kdd0d*result2d0d1 - result2d0*Kdd0dd - Kdd1*
    result2d0dd0 - result2d0d*Kdd1d - result2d0dd*Kdd2 - Kd*result2d0ddd - 
    Kddd0*result2d1d0 - result2d1*Kddd0d - result2d1d*Kddd1 - Kdd*result2d1dd 
    - result2d2*Kdddd0 - Kddd*result2d2d - Kdddd*result2d3 - result2*Kddddd - 
    Kd0d0*result2dd0d0 - result2dd0*Kd0d0d - result2dd0d*Kd0d1 - Kd0*
    result2dd0dd - result2dd1*Kd0dd0 - Kd0d*result2dd1d - Kd0dd*result2dd2 - 
    result2d*Kd0ddd - result2ddd0*Kd1d0 - Kd1*result2ddd0d - Kd1d*result2ddd1 
    - result2dd*Kd1dd - Kd2*result2dddd0 - result2ddd*Kd2d - result2dddd*Kd3 -
    K*result2ddddd;
}
