/*        Generated by TAPENADE     (INRIA, Ecuador team)
    Tapenade 3.16 (feature_julia) - 28 Oct 2024 17:01
*/
/*        Generated by TAPENADE     (INRIA, Ecuador team)
    Tapenade 3.16 (feature_julia) - 28 Oct 2024 17:01
*/
#include "adStack.h"
#include <math.h>
#include <stdio.h>

/*
  Differentiation of cdf_n_b in forward (tangent) mode:
   variations   of useful results: *xb
   with respect to varying inputs: x cdf_nb
   Plus diff mem management of: xb:in


  Differentiation of cdf_n in reverse (adjoint) mode:
   gradient     of useful results: cdf_n
   with respect to varying inputs: x
*/
void cdf_n_b_d(double x, double xd, double *xb, double *xbd, double cdf_nb,
               double cdf_nbd) {
    double arg1;
    double arg1d;
    double temp;
    arg1d = -(0.70710678118654746 * 0.70710678118654746 * 2 * x * xd);
    arg1 = -(-(0.70710678118654746 * x) * -(0.70710678118654746 * x));
    temp = exp(arg1);
    *xbd = 1.1283791671 * 0.5 * 0.70710678118654746 *
           (cdf_nb * exp(arg1) * arg1d + temp * cdf_nbd);
    *xb = 1.1283791671 * 0.5 * 0.70710678118654746 * (temp * cdf_nb);
}

/*
  Differentiation of cdf_n_nodiff in forward (tangent) mode:
   variations   of useful results: cdf_n_nodiff
   with respect to varying inputs: x
*/
double cdf_n_nodiff_d(double x, double xd, double *cdf_n_nodiff) {
    *cdf_n_nodiff = 0.5 * erfc(x * -0.70710678118654746);
    return 0.5 * 1.1283791671 *
           exp(-(-(0.70710678118654746 * x) * -(0.70710678118654746 * x))) *
           0.70710678118654746 * xd;
}

/*
  Differentiation of call_price_b in forward (tangent) mode:
   variations   of useful results: *Tb *Kb *vb *Sb
   with respect to varying inputs: *Tb v *Kb *vb call_priceb *Sb
                K S T
   RW status of diff variables: Tb:(loc) *Tb:in-out v:in Kb:(loc)
                *Kb:in-out vb:(loc) *vb:in-out call_priceb:in
                Sb:(loc) *Sb:in-out K:in S:in T:in
   Plus diff mem management of: Tb:in Kb:in vb:in Sb:in


  Differentiation of call_price in reverse (adjoint) mode:
   gradient     of useful results: v call_price K S T
   with respect to varying inputs: v K S T
   RW status of diff variables: v:incr call_price:in-killed K:incr
                S:incr T:incr
*/
void call_price_b_d(double S, double Sd, double *Sb, double *Sbd, double K,
                    double Kd, double *Kb, double *Kbd, double v, double vd,
                    double *vb, double *vbd, double T, double Td, double *Tb,
                    double *Tbd, double call_priceb, double call_pricebd) {
    double totalvol;
    double totalvold;
    double result10;
    double result10d;
    double temp0;
    double temp1;
    temp0 = sqrt(T);
    result10d = (T == 0.0 ? 0.0 : Td / (2.0 * temp0));
    result10 = temp0;
    totalvold = result10 * vd + v * result10d;
    totalvol = v * result10;
    double totalvolb = 0.0;
    double totalvolbd;
    temp0 = S / K;
    temp1 = log(temp0) / totalvol;
    double d1 = temp1 + 0.5 * totalvol;
    double d1d =
        ((Sd - temp0 * Kd) / (temp0 * K) - temp1 * totalvold) / totalvol +
        0.5 * totalvold;
    double d1b = 0.0;
    double d1bd;
    double d2 = d1 - totalvol;
    double d2d = d1d - totalvold;
    double d2b = 0.0;
    double d2bd;
    double result1;
    double result1d;
    double result1b;
    double result1bd;
    double result2;
    double result2d;
    double result2b;
    double result2bd;
    double temp;
    double tempd;
    double tempb;
    double tempbd;
    result1d = cdf_n_nodiff_d(d1, d1d, &result1);
    result2d = cdf_n_nodiff_d(d2, d2d, &result2);
    result1bd = call_priceb * Sd + S * call_pricebd;
    result1b = S * call_priceb;
    result2bd = -(call_priceb * Kd + K * call_pricebd);
    result2b = -(K * call_priceb);
    d2bd = 0.0;
    d2b = 0.0;
    cdf_n_b_d(d2, d2d, &d2b, &d2bd, result2b, result2bd);
    d1bd = 0.0;
    d1b = 0.0;
    cdf_n_b_d(d1, d1d, &d1b, &d1bd, result1b, result1bd);
    d1bd = d1bd + d2bd;
    d1b = d1b + d2b;
    tempd = (Sd - S * Kd / K) / K;
    temp = S / K;
    temp1 = K * temp * totalvol;
    tempbd =
        (d1bd -
         d1b * (totalvol * (temp * Kd + K * tempd) + K * temp * totalvold) /
             temp1) /
        temp1;
    tempb = d1b / temp1;
    *Sbd = *Sbd + call_priceb * result1d + result1 * call_pricebd + tempbd;
    *Sb = *Sb + result1 * call_priceb + tempb;
    *Kbd = *Kbd - call_priceb * result2d - result2 * call_pricebd -
           tempb * tempd - temp * tempbd;
    *Kb = *Kb - result2 * call_priceb - temp * tempb;
    temp1 = log(temp) / (totalvol * totalvol);
    totalvolbd = (0.5 - temp1) * d1bd -
                 d1b * (tempd / temp - temp1 * 2 * totalvol * totalvold) /
                     (totalvol * totalvol) -
                 d2bd;
    totalvolb = (0.5 - temp1) * d1b - d2b;
    temp1 = sqrt(T);
    tempd = (T == 0.0 ? 0.0 : Td / (2.0 * temp1));
    temp = temp1;
    *vbd = *vbd + totalvolb * tempd + temp * totalvolbd;
    *vb = *vb + temp * totalvolb;
    if (!(T == 0.0)) {
        temp1 = v * totalvolb / (2.0 * temp);
        *Tbd = *Tbd + (totalvolb * vd + v * totalvolbd - temp1 * 2.0 * tempd) /
                          (2.0 * temp);
        *Tb = *Tb + temp1;
    }
}
