from sympy import *
import mpmath
mpmath.mp.dps = 20

S = Symbol('S')
K = Symbol('K')
v = Symbol('v')
T = Symbol('T')

def cdf(x):
    return 0.5 * erfc(x * -0.70710678118654746)

totalvol = v * sqrt(T)
d1 = log(S / K) / totalvol + totalvol * 0.5
d2 = d1 - totalvol
result = S * cdf(d1) - K * cdf(d2)

def diff(f, diffs):
    fdiff = f
    for i in diffs:
        fdiff = fdiff.diff(i)

    return fdiff

# values generated by RNG in c++
S0 = mpmath.mpf('104.25910643160562')
K0 = mpmath.mpf('98.569418500578678')
v0 = mpmath.mpf('0.22272121285943147')
T0 = mpmath.mpf('1.2191503088807956')
# S0 = 104.25910643160562
# K0 = 98.569418500578678
# v0 = 0.22272121285943147
# T0 = 1.2191503088807956


print("sympy verification values for first iteration of Black-Scholes:")
# value
print(lambdify([S, K, v, T], result, modules="mpmath")(S0, K0, v0, T0))

# order 1
print(lambdify([S, K, v, T], diff(result, (S,)), modules="mpmath")(S0, K0, v0, T0))
print(lambdify([S, K, v, T], diff(result, (K,)), modules="mpmath")(S0, K0, v0, T0))
print(lambdify([S, K, v, T], diff(result, (v,)), modules="mpmath")(S0, K0, v0, T0))
print(lambdify([S, K, v, T], diff(result, (T,)), modules="mpmath")(S0, K0, v0, T0))

# order 2
print(lambdify([S, K, v, T], diff(result, (S, S)), modules="mpmath")(S0, K0, v0, T0))
print(lambdify([S, K, v, T], diff(result, (S, K)), modules="mpmath")(S0, K0, v0, T0))
print(lambdify([S, K, v, T], diff(result, (S, v)), modules="mpmath")(S0, K0, v0, T0))
print(lambdify([S, K, v, T], diff(result, (S, T)), modules="mpmath")(S0, K0, v0, T0))
print(lambdify([S, K, v, T], diff(result, (K, K)), modules="mpmath")(S0, K0, v0, T0))
print(lambdify([S, K, v, T], diff(result, (K, v)), modules="mpmath")(S0, K0, v0, T0))
print(lambdify([S, K, v, T], diff(result, (K, T)), modules="mpmath")(S0, K0, v0, T0))
print(lambdify([S, K, v, T], diff(result, (v, v)), modules="mpmath")(S0, K0, v0, T0))
print(lambdify([S, K, v, T], diff(result, (v, T)), modules="mpmath")(S0, K0, v0, T0))
print(lambdify([S, K, v, T], diff(result, (T, T)), modules="mpmath")(S0, K0, v0, T0))

# order 3
print(lambdify([S, K, v, T], diff(result, (S, S, S)), modules="mpmath")(S0, K0, v0, T0))
print(lambdify([S, K, v, T], diff(result, (S, S, K)), modules="mpmath")(S0, K0, v0, T0))
print(lambdify([S, K, v, T], diff(result, (S, S, v)), modules="mpmath")(S0, K0, v0, T0))
print(lambdify([S, K, v, T], diff(result, (S, S, T)), modules="mpmath")(S0, K0, v0, T0))
print(lambdify([S, K, v, T], diff(result, (S, K, K)), modules="mpmath")(S0, K0, v0, T0))
print(lambdify([S, K, v, T], diff(result, (S, K, v)), modules="mpmath")(S0, K0, v0, T0))
print(lambdify([S, K, v, T], diff(result, (S, K, T)), modules="mpmath")(S0, K0, v0, T0))
print(lambdify([S, K, v, T], diff(result, (S, v, v)), modules="mpmath")(S0, K0, v0, T0))
print(lambdify([S, K, v, T], diff(result, (S, v, T)), modules="mpmath")(S0, K0, v0, T0))
print(lambdify([S, K, v, T], diff(result, (S, T, T)), modules="mpmath")(S0, K0, v0, T0))
print(lambdify([S, K, v, T], diff(result, (K, K, K)), modules="mpmath")(S0, K0, v0, T0))
print(lambdify([S, K, v, T], diff(result, (K, K, v)), modules="mpmath")(S0, K0, v0, T0))
print(lambdify([S, K, v, T], diff(result, (K, K, T)), modules="mpmath")(S0, K0, v0, T0))
print(lambdify([S, K, v, T], diff(result, (K, v, v)), modules="mpmath")(S0, K0, v0, T0))
print(lambdify([S, K, v, T], diff(result, (K, v, T)), modules="mpmath")(S0, K0, v0, T0))
print(lambdify([S, K, v, T], diff(result, (K, T, T)), modules="mpmath")(S0, K0, v0, T0))
print(lambdify([S, K, v, T], diff(result, (v, v, v)), modules="mpmath")(S0, K0, v0, T0))
print(lambdify([S, K, v, T], diff(result, (v, v, T)), modules="mpmath")(S0, K0, v0, T0))
print(lambdify([S, K, v, T], diff(result, (v, T, T)), modules="mpmath")(S0, K0, v0, T0))
print(lambdify([S, K, v, T], diff(result, (T, T, T)), modules="mpmath")(S0, K0, v0, T0))

# order 4
print(lambdify([S, K, v, T], diff(result, (S, S, S, S)), modules="mpmath")(S0, K0, v0, T0))
print(lambdify([S, K, v, T], diff(result, (S, S, S, K)), modules="mpmath")(S0, K0, v0, T0))
print(lambdify([S, K, v, T], diff(result, (S, S, S, v)), modules="mpmath")(S0, K0, v0, T0))
print(lambdify([S, K, v, T], diff(result, (S, S, S, T)), modules="mpmath")(S0, K0, v0, T0))
print(lambdify([S, K, v, T], diff(result, (S, S, K, K)), modules="mpmath")(S0, K0, v0, T0))
print(lambdify([S, K, v, T], diff(result, (S, S, K, v)), modules="mpmath")(S0, K0, v0, T0))
print(lambdify([S, K, v, T], diff(result, (S, S, K, T)), modules="mpmath")(S0, K0, v0, T0))
print(lambdify([S, K, v, T], diff(result, (S, S, v, v)), modules="mpmath")(S0, K0, v0, T0))
print(lambdify([S, K, v, T], diff(result, (S, S, v, T)), modules="mpmath")(S0, K0, v0, T0))
print(lambdify([S, K, v, T], diff(result, (S, S, T, T)), modules="mpmath")(S0, K0, v0, T0))
print(lambdify([S, K, v, T], diff(result, (S, K, K, K)), modules="mpmath")(S0, K0, v0, T0))
print(lambdify([S, K, v, T], diff(result, (S, K, K, v)), modules="mpmath")(S0, K0, v0, T0))
print(lambdify([S, K, v, T], diff(result, (S, K, K, T)), modules="mpmath")(S0, K0, v0, T0))
print(lambdify([S, K, v, T], diff(result, (S, K, v, v)), modules="mpmath")(S0, K0, v0, T0))
print(lambdify([S, K, v, T], diff(result, (S, K, v, T)), modules="mpmath")(S0, K0, v0, T0))
print(lambdify([S, K, v, T], diff(result, (S, K, T, T)), modules="mpmath")(S0, K0, v0, T0))
print(lambdify([S, K, v, T], diff(result, (S, v, v, v)), modules="mpmath")(S0, K0, v0, T0))
print(lambdify([S, K, v, T], diff(result, (S, v, v, T)), modules="mpmath")(S0, K0, v0, T0))
print(lambdify([S, K, v, T], diff(result, (S, v, T, T)), modules="mpmath")(S0, K0, v0, T0))
print(lambdify([S, K, v, T], diff(result, (S, T, T, T)), modules="mpmath")(S0, K0, v0, T0))
print(lambdify([S, K, v, T], diff(result, (K, K, K, K)), modules="mpmath")(S0, K0, v0, T0))
print(lambdify([S, K, v, T], diff(result, (K, K, K, v)), modules="mpmath")(S0, K0, v0, T0))
print(lambdify([S, K, v, T], diff(result, (K, K, K, T)), modules="mpmath")(S0, K0, v0, T0))
print(lambdify([S, K, v, T], diff(result, (K, K, v, v)), modules="mpmath")(S0, K0, v0, T0))
print(lambdify([S, K, v, T], diff(result, (K, K, v, T)), modules="mpmath")(S0, K0, v0, T0))
print(lambdify([S, K, v, T], diff(result, (K, K, T, T)), modules="mpmath")(S0, K0, v0, T0))
print(lambdify([S, K, v, T], diff(result, (K, v, v, v)), modules="mpmath")(S0, K0, v0, T0))
print(lambdify([S, K, v, T], diff(result, (K, v, v, T)), modules="mpmath")(S0, K0, v0, T0))
print(lambdify([S, K, v, T], diff(result, (K, v, T, T)), modules="mpmath")(S0, K0, v0, T0))
print(lambdify([S, K, v, T], diff(result, (K, T, T, T)), modules="mpmath")(S0, K0, v0, T0))
print(lambdify([S, K, v, T], diff(result, (v, v, v, v)), modules="mpmath")(S0, K0, v0, T0))
print(lambdify([S, K, v, T], diff(result, (v, v, v, T)), modules="mpmath")(S0, K0, v0, T0))
print(lambdify([S, K, v, T], diff(result, (v, v, T, T)), modules="mpmath")(S0, K0, v0, T0))
print(lambdify([S, K, v, T], diff(result, (v, T, T, T)), modules="mpmath")(S0, K0, v0, T0))
print(lambdify([S, K, v, T], diff(result, (T, T, T, T)), modules="mpmath")(S0, K0, v0, T0))

# order 5
print(lambdify([S, K, v, T], diff(result, (S, S, S, S, S)), modules="mpmath")(S0, K0, v0, T0))
print(lambdify([S, K, v, T], diff(result, (S, S, S, S, K)), modules="mpmath")(S0, K0, v0, T0))
print(lambdify([S, K, v, T], diff(result, (S, S, S, S, v)), modules="mpmath")(S0, K0, v0, T0))
print(lambdify([S, K, v, T], diff(result, (S, S, S, S, T)), modules="mpmath")(S0, K0, v0, T0))
print(lambdify([S, K, v, T], diff(result, (S, S, S, K, K)), modules="mpmath")(S0, K0, v0, T0))
print(lambdify([S, K, v, T], diff(result, (S, S, S, K, v)), modules="mpmath")(S0, K0, v0, T0))
print(lambdify([S, K, v, T], diff(result, (S, S, S, K, T)), modules="mpmath")(S0, K0, v0, T0))
print(lambdify([S, K, v, T], diff(result, (S, S, S, v, v)), modules="mpmath")(S0, K0, v0, T0))
print(lambdify([S, K, v, T], diff(result, (S, S, S, v, T)), modules="mpmath")(S0, K0, v0, T0))
print(lambdify([S, K, v, T], diff(result, (S, S, S, T, T)), modules="mpmath")(S0, K0, v0, T0))
print(lambdify([S, K, v, T], diff(result, (S, S, K, K, K)), modules="mpmath")(S0, K0, v0, T0))
print(lambdify([S, K, v, T], diff(result, (S, S, K, K, v)), modules="mpmath")(S0, K0, v0, T0))
print(lambdify([S, K, v, T], diff(result, (S, S, K, K, T)), modules="mpmath")(S0, K0, v0, T0))
print(lambdify([S, K, v, T], diff(result, (S, S, K, v, v)), modules="mpmath")(S0, K0, v0, T0))
print(lambdify([S, K, v, T], diff(result, (S, S, K, v, T)), modules="mpmath")(S0, K0, v0, T0))
print(lambdify([S, K, v, T], diff(result, (S, S, K, T, T)), modules="mpmath")(S0, K0, v0, T0))
print(lambdify([S, K, v, T], diff(result, (S, S, v, v, v)), modules="mpmath")(S0, K0, v0, T0))
print(lambdify([S, K, v, T], diff(result, (S, S, v, v, T)), modules="mpmath")(S0, K0, v0, T0))
print(lambdify([S, K, v, T], diff(result, (S, S, v, T, T)), modules="mpmath")(S0, K0, v0, T0))
print(lambdify([S, K, v, T], diff(result, (S, S, T, T, T)), modules="mpmath")(S0, K0, v0, T0))
print(lambdify([S, K, v, T], diff(result, (S, K, K, K, K)), modules="mpmath")(S0, K0, v0, T0))
print(lambdify([S, K, v, T], diff(result, (S, K, K, K, v)), modules="mpmath")(S0, K0, v0, T0))
print(lambdify([S, K, v, T], diff(result, (S, K, K, K, T)), modules="mpmath")(S0, K0, v0, T0))
print(lambdify([S, K, v, T], diff(result, (S, K, K, v, v)), modules="mpmath")(S0, K0, v0, T0))
print(lambdify([S, K, v, T], diff(result, (S, K, K, v, T)), modules="mpmath")(S0, K0, v0, T0))
print(lambdify([S, K, v, T], diff(result, (S, K, K, T, T)), modules="mpmath")(S0, K0, v0, T0))
print(lambdify([S, K, v, T], diff(result, (S, K, v, v, v)), modules="mpmath")(S0, K0, v0, T0))
print(lambdify([S, K, v, T], diff(result, (S, K, v, v, T)), modules="mpmath")(S0, K0, v0, T0))
print(lambdify([S, K, v, T], diff(result, (S, K, v, T, T)), modules="mpmath")(S0, K0, v0, T0))
print(lambdify([S, K, v, T], diff(result, (S, K, T, T, T)), modules="mpmath")(S0, K0, v0, T0))
print(lambdify([S, K, v, T], diff(result, (S, v, v, v, v)), modules="mpmath")(S0, K0, v0, T0))
print(lambdify([S, K, v, T], diff(result, (S, v, v, v, T)), modules="mpmath")(S0, K0, v0, T0))
print(lambdify([S, K, v, T], diff(result, (S, v, v, T, T)), modules="mpmath")(S0, K0, v0, T0))
print(lambdify([S, K, v, T], diff(result, (S, v, T, T, T)), modules="mpmath")(S0, K0, v0, T0))
print(lambdify([S, K, v, T], diff(result, (S, T, T, T, T)), modules="mpmath")(S0, K0, v0, T0))
print(lambdify([S, K, v, T], diff(result, (K, K, K, K, K)), modules="mpmath")(S0, K0, v0, T0))
print(lambdify([S, K, v, T], diff(result, (K, K, K, K, v)), modules="mpmath")(S0, K0, v0, T0))
print(lambdify([S, K, v, T], diff(result, (K, K, K, K, T)), modules="mpmath")(S0, K0, v0, T0))
print(lambdify([S, K, v, T], diff(result, (K, K, K, v, v)), modules="mpmath")(S0, K0, v0, T0))
print(lambdify([S, K, v, T], diff(result, (K, K, K, v, T)), modules="mpmath")(S0, K0, v0, T0))
print(lambdify([S, K, v, T], diff(result, (K, K, K, T, T)), modules="mpmath")(S0, K0, v0, T0))
print(lambdify([S, K, v, T], diff(result, (K, K, v, v, v)), modules="mpmath")(S0, K0, v0, T0))
print(lambdify([S, K, v, T], diff(result, (K, K, v, v, T)), modules="mpmath")(S0, K0, v0, T0))
print(lambdify([S, K, v, T], diff(result, (K, K, v, T, T)), modules="mpmath")(S0, K0, v0, T0))
print(lambdify([S, K, v, T], diff(result, (K, K, T, T, T)), modules="mpmath")(S0, K0, v0, T0))
print(lambdify([S, K, v, T], diff(result, (K, v, v, v, v)), modules="mpmath")(S0, K0, v0, T0))
print(lambdify([S, K, v, T], diff(result, (K, v, v, v, T)), modules="mpmath")(S0, K0, v0, T0))
print(lambdify([S, K, v, T], diff(result, (K, v, v, T, T)), modules="mpmath")(S0, K0, v0, T0))
print(lambdify([S, K, v, T], diff(result, (K, v, T, T, T)), modules="mpmath")(S0, K0, v0, T0))
print(lambdify([S, K, v, T], diff(result, (K, T, T, T, T)), modules="mpmath")(S0, K0, v0, T0))
print(lambdify([S, K, v, T], diff(result, (v, v, v, v, v)), modules="mpmath")(S0, K0, v0, T0))
print(lambdify([S, K, v, T], diff(result, (v, v, v, v, T)), modules="mpmath")(S0, K0, v0, T0))
print(lambdify([S, K, v, T], diff(result, (v, v, v, T, T)), modules="mpmath")(S0, K0, v0, T0))
print(lambdify([S, K, v, T], diff(result, (v, v, T, T, T)), modules="mpmath")(S0, K0, v0, T0))
print(lambdify([S, K, v, T], diff(result, (v, T, T, T, T)), modules="mpmath")(S0, K0, v0, T0))
print(lambdify([S, K, v, T], diff(result, (T, T, T, T, T)), modules="mpmath")(S0, K0, v0, T0))
